// Code generated by generate.go: DO NOT EDIT.

package glm

import "unsafe"

type _ = unsafe.Pointer

// Mat4f is a 4x4 matrix.
// The default value is filled with all zero values.
type Mat4f [4][4]float32

func IdentityMat4f() Mat4f {
	var m Mat4f
	m[0][0] = 1
	m[1][1] = 1
	m[2][2] = 1
	m[3][3] = 1
	return m
}

func (m Mat4f) Mul(o Mat4f) Mat4f {

	mat4fMulAssign(
		(*mat4f)(unsafe.Pointer(&m)),
		(*mat4f)(unsafe.Pointer(&o)),
	)

	return m
}

func (m Mat4f) Transpose() Mat4f {
	mv := &m

	return Mat4f{
		{
			mv[0][0],
			mv[1][0],
			mv[2][0],
			mv[3][0],
		},
		{
			mv[0][1],
			mv[1][1],
			mv[2][1],
			mv[3][1],
		},
		{
			mv[0][2],
			mv[1][2],
			mv[2][2],
			mv[3][2],
		},
		{
			mv[0][3],
			mv[1][3],
			mv[2][3],
			mv[3][3],
		},
	}
}

// Column returns a reference to the given column
func (m *Mat4f) Column(idx int) Vec4f {
	return *(*Vec4f)(&m[idx])
}

func TranslationMat4f(x, y, z float32) Mat4f {
	return Mat4f{
		{1, 0, 0, 0},
		{0, 1, 0, 0},
		{0, 0, 1, 0},
		{x, y, z, 1},
	}
}

func ScaleMat4f(x, y, z float32) Mat4f {
	var res Mat4f
	res[0][0] = x
	res[1][1] = y
	res[2][2] = z
	res[3][3] = 1
	return res
}

func (m Mat4f) Translate(x, y, z float32) Mat4f {
	return m.Mul(TranslationMat4f(x, y, z))
}

func (m Mat4f) Scale(x, y, z float32) Mat4f {
	return m.Mul(ScaleMat4f(x, y, z))
}

func RotationZMat4f(angle Rad) Mat4f {
	fs, fc := fastSincos(angle)
	s := float32(fs)
	c := float32(fc)

	return Mat4f{
		{c, s, 0, 0},
		{-s, c, 0, 0},
		{0, 0, 1, 0},
		{0, 0, 0, 1},
	}
}

func RotationXMat4f(angle Rad) Mat4f {
	fs, fc := fastSincos(angle)
	s := float32(fs)
	c := float32(fc)

	return Mat4f{
		{1, 0, 0, 0},
		{0, c, s, 0},
		{0, -s, c, 0},
		{0, 0, 0, 1},
	}
}

func RotationYMat4f(angle Rad) Mat4f {
	fs, fc := fastSincos(angle)
	s := float32(fs)
	c := float32(fc)

	return Mat4f{
		{c, 0, s, 0},
		{0, 1, 0, 0},
		{-s, 0, c, 0},
		{0, 0, 0, 1},
	}
}

func (m Mat4f) RotateX(angle Rad) Mat4f {
	return m.Mul(RotationXMat4f(angle))
}

func (m Mat4f) RotateY(angle Rad) Mat4f {
	return m.Mul(RotationYMat4f(angle))
}

func (m Mat4f) RotateZ(angle Rad) Mat4f {
	return m.Mul(RotationZMat4f(angle))
}

func (m Mat4f) Transform(vec Vec4f) Vec4f {
	return Vec4f{
		(m[0][0])*vec[0] + (m[1][0])*vec[1] + (m[2][0])*vec[2] + (m[3][0])*vec[3],
		(m[0][1])*vec[0] + (m[1][1])*vec[1] + (m[2][1])*vec[2] + (m[3][1])*vec[3],
		(m[0][2])*vec[0] + (m[1][2])*vec[1] + (m[2][2])*vec[2] + (m[3][2])*vec[3],
		(m[0][3])*vec[0] + (m[1][3])*vec[1] + (m[2][3])*vec[2] + (m[3][3])*vec[3],
	}
}

func (m Mat4f) Transform3(vec Vec3f) Vec3f {
	return Vec3f{
		(m[0][0])*vec[0] + (m[1][0])*vec[1] + (m[2][0] * vec[2]) + m[3][0],
		(m[0][1])*vec[0] + (m[1][1])*vec[1] + (m[2][1] * vec[2]) + m[3][1],
		(m[0][2])*vec[0] + (m[1][2])*vec[1] + (m[2][2] * vec[2]) + m[3][2],
	}
}

func (m Mat4f) Transform2(vec Vec2f) Vec2f {
	return Vec2f{
		(m[0][0])*vec[0] + (m[1][0])*vec[1] + m[3][0],
		(m[0][1])*vec[0] + (m[1][1])*vec[1] + m[3][1],
	}
}

func (m Mat4f) TranslateZ() float32 {
	return m[3][2]
}
