// Code generated by generate.go: DO NOT EDIT.

package glm

import "fmt"
import "math"

// Vec3f is a vector of dimension 3.
type Vec3f [3]float32

func (lhs Vec3f) Dot(rhs Vec3f) float32 {
	return lhs[0]*rhs[0] + lhs[1]*rhs[1] + lhs[2]*rhs[2]
}

func (lhs Vec3f) LengthSqr() float32 {
	return lhs.Dot(lhs)
}

func (lhs Vec3f) Length() float32 {
	return float32(math.Sqrt(float64(lhs.Dot(lhs))))
}

func (lhs Vec3f) Normalize() Vec3f {
	return lhs.Scale(1.0 / lhs.Length())
}

func (lhs Vec3f) Scale(s float32) Vec3f {
	return Vec3f{
		lhs[0] * s,
		lhs[1] * s,
		lhs[2] * s,
	}
}

func (lhs Vec3f) Reciprocal() Vec3f {
	return Vec3f{
		1.0 / lhs[0],
		1.0 / lhs[1],
		1.0 / lhs[2],
	}
}

func (lhs Vec3f) Add(rhs Vec3f) Vec3f {
	return Vec3f{
		lhs[0] + rhs[0],
		lhs[1] + rhs[1],
		lhs[2] + rhs[2],
	}
}

func (lhs Vec3f) Sub(rhs Vec3f) Vec3f {
	return Vec3f{
		lhs[0] - rhs[0],
		lhs[1] - rhs[1],
		lhs[2] - rhs[2],
	}
}

func (lhs Vec3f) Mul(rhs Vec3f) Vec3f {
	return Vec3f{
		lhs[0] * rhs[0],
		lhs[1] * rhs[1],
		lhs[2] * rhs[2],
	}
}

func (lhs Vec3f) Div(rhs Vec3f) Vec3f {
	return Vec3f{
		lhs[0] / rhs[0],
		lhs[1] / rhs[1],
		lhs[2] / rhs[2],
	}
}

func (lhs Vec3f) Min(rhs Vec3f) Vec3f {
	return Vec3f{
		min(lhs[0], rhs[0]),
		min(lhs[1], rhs[1]),
		min(lhs[2], rhs[2]),
	}
}

func (lhs Vec3f) Max(rhs Vec3f) Vec3f {
	return Vec3f{
		max(lhs[0], rhs[0]),
		max(lhs[1], rhs[1]),
		max(lhs[2], rhs[2]),
	}
}

func (lhs Vec3f) Extend(w float32) Vec4f {
	return Vec4f{
		lhs[0],
		lhs[1],
		lhs[2],
		w,
	}
}

func (lhs Vec3f) Truncate() Vec2f {
	return Vec2f{
		lhs[0],
		lhs[1],
	}
}

// SwizzleXX returns a new vector with the components of this
// vector in the order of XX.
func (lhs Vec3f) SwizzleXX() Vec2f {
	return Vec2f{
		lhs[0],
		lhs[0],
	}
}

// SwizzleXY returns a new vector with the components of this
// vector in the order of XY.
func (lhs Vec3f) SwizzleXY() Vec2f {
	return Vec2f{
		lhs[0],
		lhs[1],
	}
}

// SwizzleXZ returns a new vector with the components of this
// vector in the order of XZ.
func (lhs Vec3f) SwizzleXZ() Vec2f {
	return Vec2f{
		lhs[0],
		lhs[2],
	}
}

// SwizzleYX returns a new vector with the components of this
// vector in the order of YX.
func (lhs Vec3f) SwizzleYX() Vec2f {
	return Vec2f{
		lhs[1],
		lhs[0],
	}
}

// SwizzleYY returns a new vector with the components of this
// vector in the order of YY.
func (lhs Vec3f) SwizzleYY() Vec2f {
	return Vec2f{
		lhs[1],
		lhs[1],
	}
}

// SwizzleYZ returns a new vector with the components of this
// vector in the order of YZ.
func (lhs Vec3f) SwizzleYZ() Vec2f {
	return Vec2f{
		lhs[1],
		lhs[2],
	}
}

// SwizzleZX returns a new vector with the components of this
// vector in the order of ZX.
func (lhs Vec3f) SwizzleZX() Vec2f {
	return Vec2f{
		lhs[2],
		lhs[0],
	}
}

// SwizzleZY returns a new vector with the components of this
// vector in the order of ZY.
func (lhs Vec3f) SwizzleZY() Vec2f {
	return Vec2f{
		lhs[2],
		lhs[1],
	}
}

// SwizzleZZ returns a new vector with the components of this
// vector in the order of ZZ.
func (lhs Vec3f) SwizzleZZ() Vec2f {
	return Vec2f{
		lhs[2],
		lhs[2],
	}
}

// SwizzleXXX returns a new vector with the components of this
// vector in the order of XXX.
func (lhs Vec3f) SwizzleXXX() Vec3f {
	return Vec3f{
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXXY returns a new vector with the components of this
// vector in the order of XXY.
func (lhs Vec3f) SwizzleXXY() Vec3f {
	return Vec3f{
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXXZ returns a new vector with the components of this
// vector in the order of XXZ.
func (lhs Vec3f) SwizzleXXZ() Vec3f {
	return Vec3f{
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXYX returns a new vector with the components of this
// vector in the order of XYX.
func (lhs Vec3f) SwizzleXYX() Vec3f {
	return Vec3f{
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXYY returns a new vector with the components of this
// vector in the order of XYY.
func (lhs Vec3f) SwizzleXYY() Vec3f {
	return Vec3f{
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXYZ returns a new vector with the components of this
// vector in the order of XYZ.
func (lhs Vec3f) SwizzleXYZ() Vec3f {
	return Vec3f{
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXZX returns a new vector with the components of this
// vector in the order of XZX.
func (lhs Vec3f) SwizzleXZX() Vec3f {
	return Vec3f{
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXZY returns a new vector with the components of this
// vector in the order of XZY.
func (lhs Vec3f) SwizzleXZY() Vec3f {
	return Vec3f{
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXZZ returns a new vector with the components of this
// vector in the order of XZZ.
func (lhs Vec3f) SwizzleXZZ() Vec3f {
	return Vec3f{
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYXX returns a new vector with the components of this
// vector in the order of YXX.
func (lhs Vec3f) SwizzleYXX() Vec3f {
	return Vec3f{
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYXY returns a new vector with the components of this
// vector in the order of YXY.
func (lhs Vec3f) SwizzleYXY() Vec3f {
	return Vec3f{
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYXZ returns a new vector with the components of this
// vector in the order of YXZ.
func (lhs Vec3f) SwizzleYXZ() Vec3f {
	return Vec3f{
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYYX returns a new vector with the components of this
// vector in the order of YYX.
func (lhs Vec3f) SwizzleYYX() Vec3f {
	return Vec3f{
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYYY returns a new vector with the components of this
// vector in the order of YYY.
func (lhs Vec3f) SwizzleYYY() Vec3f {
	return Vec3f{
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYYZ returns a new vector with the components of this
// vector in the order of YYZ.
func (lhs Vec3f) SwizzleYYZ() Vec3f {
	return Vec3f{
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYZX returns a new vector with the components of this
// vector in the order of YZX.
func (lhs Vec3f) SwizzleYZX() Vec3f {
	return Vec3f{
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYZY returns a new vector with the components of this
// vector in the order of YZY.
func (lhs Vec3f) SwizzleYZY() Vec3f {
	return Vec3f{
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYZZ returns a new vector with the components of this
// vector in the order of YZZ.
func (lhs Vec3f) SwizzleYZZ() Vec3f {
	return Vec3f{
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZXX returns a new vector with the components of this
// vector in the order of ZXX.
func (lhs Vec3f) SwizzleZXX() Vec3f {
	return Vec3f{
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZXY returns a new vector with the components of this
// vector in the order of ZXY.
func (lhs Vec3f) SwizzleZXY() Vec3f {
	return Vec3f{
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZXZ returns a new vector with the components of this
// vector in the order of ZXZ.
func (lhs Vec3f) SwizzleZXZ() Vec3f {
	return Vec3f{
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZYX returns a new vector with the components of this
// vector in the order of ZYX.
func (lhs Vec3f) SwizzleZYX() Vec3f {
	return Vec3f{
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZYY returns a new vector with the components of this
// vector in the order of ZYY.
func (lhs Vec3f) SwizzleZYY() Vec3f {
	return Vec3f{
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZYZ returns a new vector with the components of this
// vector in the order of ZYZ.
func (lhs Vec3f) SwizzleZYZ() Vec3f {
	return Vec3f{
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZZX returns a new vector with the components of this
// vector in the order of ZZX.
func (lhs Vec3f) SwizzleZZX() Vec3f {
	return Vec3f{
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZZY returns a new vector with the components of this
// vector in the order of ZZY.
func (lhs Vec3f) SwizzleZZY() Vec3f {
	return Vec3f{
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZZZ returns a new vector with the components of this
// vector in the order of ZZZ.
func (lhs Vec3f) SwizzleZZZ() Vec3f {
	return Vec3f{
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

func (lhs Vec3f) XY() (x, y float32) {
	x = lhs[0]
	y = lhs[1]
	return
}

func (lhs Vec3f) XYZ() (x, y, z float32) {
	x = lhs[0]
	y = lhs[1]
	z = lhs[2]
	return
}

func (lhs Vec3f) ToVec3f() Vec3f {
	return Vec3f{
		float32(lhs[0]),
		float32(lhs[1]),
		float32(lhs[2]),
	}
}

func (lhs Vec3f) ToWGPU() [4]float32 {
	return [4]float32{
		float32(lhs[0]),
		float32(lhs[1]),
		float32(lhs[2]),
	}
}

func (lhs Vec3f) String() string {
	return fmt.Sprintf(
		"vec3(%v, %v, %v)",
		lhs[0],
		lhs[1],
		lhs[2],
	)
}
