// Code generated by generate.go: DO NOT EDIT.

package glm

// Mat3d is a 3x3 matrix.
// The default value is the identity matrix.
type Mat3d struct {
	values [3][3]float64
}

func Mat3dOf(values [3][3]float64) Mat3d {
	return Mat3d{
		values: [3][3]float64{
			{
				values[0][0] - 1,
				values[0][1],
				values[0][2],
			},
			{
				values[1][0],
				values[1][1] - 1,
				values[1][2],
			},
			{
				values[2][0],
				values[2][1],
				values[2][2] - 1,
			},
		},
	}
}

func IdentityMat3d() Mat3d {
	return Mat3d{}
}

func (m Mat3d) Mul(o Mat3d) Mat3d {
	mv := &m.values
	ov := &o.values

	return Mat3d{
		values: [3][3]float64{
			{
				(mv[0][0]+1)*(ov[0][0]+1) + mv[1][0]*ov[0][1] + mv[2][0]*ov[0][2] - 1,
				mv[0][1]*(ov[0][0]+1) + (mv[1][1]+1)*ov[0][1] + mv[2][1]*ov[0][2],
				mv[0][2]*(ov[0][0]+1) + mv[1][2]*ov[0][1] + (mv[2][2]+1)*ov[0][2],
			},
			{
				(mv[0][0]+1)*ov[1][0] + mv[1][0]*(ov[1][1]+1) + mv[2][0]*ov[1][2],
				mv[0][1]*ov[1][0] + (mv[1][1]+1)*(ov[1][1]+1) + mv[2][1]*ov[1][2] - 1,
				mv[0][2]*ov[1][0] + mv[1][2]*(ov[1][1]+1) + (mv[2][2]+1)*ov[1][2],
			},
			{
				(mv[0][0]+1)*ov[2][0] + mv[1][0]*ov[2][1] + mv[2][0]*(ov[2][2]+1),
				mv[0][1]*ov[2][0] + (mv[1][1]+1)*ov[2][1] + mv[2][1]*(ov[2][2]+1),
				mv[0][2]*ov[2][0] + mv[1][2]*ov[2][1] + (mv[2][2]+1)*(ov[2][2]+1) - 1,
			},
		},
	}
}

func (m Mat3d) Transpose() Mat3d {
	mv := &m.values

	return Mat3d{
		values: [3][3]float64{
			{
				mv[0][0],
				mv[1][0],
				mv[2][0],
			},
			{
				mv[0][1],
				mv[1][1],
				mv[2][1],
			},
			{
				mv[0][2],
				mv[1][2],
				mv[2][2],
			},
		},
	}
}

func (m Mat3d) Components() [3][3]float64 {
	values := m.values
	values[0][0] += 1
	values[1][1] += 1
	values[2][2] += 1
	return values
}

func (m *Mat3d) m00() float64 {
	return (m.values[0][0] + 1)
}

func (m *Mat3d) m01() float64 {
	return m.values[0][1]
}

func (m *Mat3d) m02() float64 {
	return m.values[0][2]
}

func (m *Mat3d) m10() float64 {
	return m.values[1][0]
}

func (m *Mat3d) m11() float64 {
	return (m.values[1][1] + 1)
}

func (m *Mat3d) m12() float64 {
	return m.values[1][2]
}

func (m *Mat3d) m20() float64 {
	return m.values[2][0]
}

func (m *Mat3d) m21() float64 {
	return m.values[2][1]
}

func (m *Mat3d) m22() float64 {
	return (m.values[2][2] + 1)
}

func TranslationMat3d(x, y float64) Mat3d {
	return Mat3dOf([3][3]float64{
		{1, 0, 0},
		{0, 1, 0},
		{x, y, 1},
	})
}

func ScaleMat3d(x, y float64) Mat3d {
	return Mat3dOf([3][3]float64{
		{x, 0, 0},
		{0, y, 0},
		{0, 0, 1},
	})
}

func (m Mat3d) Translate(x, y float64) Mat3d {
	return m.Mul(TranslationMat3d(x, y))
}

func (m Mat3d) Scale(x, y float64) Mat3d {
	return m.Mul(ScaleMat3d(x, y))
}

func RotationMat3d(angle Rad) Mat3d {
	s, c := fastSincos(angle)

	return Mat3dOf([3][3]float64{
		{float64(c), float64(s), 0},
		{-float64(s), float64(c), 0},
		{0, 0, 1},
	})
}

func (m Mat3d) Rotate(angle Rad) Mat3d {
	return m.Mul(RotationMat3d(angle))
}

func (m Mat3d) Row(i int) Vec3d {
	if i == 0 {
		return Vec3d{
			m.m00(),
			m.m10(),
			m.m20(),
		}
	}
	if i == 1 {
		return Vec3d{m.m01(), m.m11(), m.m21()}
	}
	if i == 2 {
		return Vec3d{
			m.m02(),
			m.m12(),
			m.m22(),
		}
	}

	panic(i)
}

func (m Mat3d) ToWGPU() [12]float32 {
	return [12]float32{
		float32(m.m00()), float32(m.m01()), float32(m.m02()), 0,
		float32(m.m10()), float32(m.m11()), float32(m.m12()), 0,
		float32(m.m20()), float32(m.m21()), float32(m.m22()), 0,
	}
}

func (m Mat3d) Invert() Mat3d {
	inv, ok := m.TryInvert()
	if !ok {
		panic("matrix not invertible")
	}

	return inv
}

func (m Mat3d) TryInvert() (Mat3d, bool) {
	var inv [3][3]float64

	// determinant
	det := m.m00()*(m.m11()*m.m22()-m.m12()*m.m21()) -
		m.m01()*(m.m10()*m.m22()-m.m12()*m.m20()) +
		m.m02()*(m.m10()*m.m21()-m.m11()*m.m20())

	if det == 0 {
		// singular
		return Mat3d{}, false
	}

	inv[0][0] = (m.m11()*m.m22() - m.m12()*m.m21()) / det
	inv[0][1] = (m.m02()*m.m21() - m.m01()*m.m22()) / det
	inv[0][2] = (m.m01()*m.m12() - m.m02()*m.m11()) / det

	inv[1][0] = (m.m12()*m.m20() - m.m10()*m.m22()) / det
	inv[1][1] = (m.m00()*m.m22() - m.m02()*m.m20()) / det
	inv[1][2] = (m.m02()*m.m10() - m.m00()*m.m12()) / det

	inv[2][0] = (m.m10()*m.m21() - m.m11()*m.m20()) / det
	inv[2][1] = (m.m01()*m.m20() - m.m00()*m.m21()) / det
	inv[2][2] = (m.m00()*m.m11() - m.m01()*m.m10()) / det

	return Mat3dOf(inv), true
}

func (m Mat3d) Transform(vec Vec3d) Vec3d {
	return Vec3d{
		(m.m00())*vec[0] + (m.m10())*vec[1] + (m.m20())*vec[2],
		(m.m01())*vec[0] + (m.m11())*vec[1] + (m.m21())*vec[2],
		(m.m02())*vec[0] + (m.m12())*vec[1] + (m.m22())*vec[2],
	}
}

func (m Mat3d) Transform2(vec Vec2d) Vec2d {
	return Vec2d{
		(m.m00())*vec[0] + (m.m10())*vec[1] + (m.m20()),
		(m.m01())*vec[0] + (m.m11())*vec[1] + (m.m21()),
	}
}
