// Code generated by generate.go: DO NOT EDIT.

package glm

import (
	"fmt"
)

type Rectu struct {
	Min Vec2u
	Max Vec2u
}

func RectuFromSize(pos Vec2u, size Vec2u) Rectu {
	return RectuFromPoints(pos, pos.Add(size))
}

func RectuFromXYWH(x, y, w, h uint32) Rectu {
	pos := Vec2u{x, y}
	size := Vec2u{w, h}
	return RectuFromSize(pos, size)
}

func RectuFromPoints(a, b Vec2u) Rectu {
	return Rectu{
		Min: Vec2u{
			min(a[0], b[0]),
			min(a[1], b[1]),
		},
		Max: Vec2u{
			max(a[0], b[0]),
			max(a[1], b[1]),
		},
	}
}

func (r Rectu) Extend(point Vec2u) Rectu {
	minX := min(r.Min[0], point[0])
	minY := min(r.Min[1], point[1])

	maxX := max(r.Max[0], point[0])
	maxY := max(r.Max[1], point[1])

	return Rectu{
		Min: Vec2u{minX, minY},
		Max: Vec2u{maxX, maxY},
	}
}

func (r Rectu) Union(other Rectu) Rectu {
	return r.Extend(other.Min).Extend(other.Max)
}

func (r Rectu) Contains(other Rectu) bool {
	return r.Min[0] <= other.Min[0] && r.Min[1] <= other.Min[1] &&
		r.Max[0] >= other.Max[0] && r.Max[1] >= other.Max[1]
}

func (r Rectu) Center() Vec2u {
	return r.Min.Add(r.Max).Div(Vec2u{2, 2})
}

func (r Rectu) Offset() Vec2u {
	return r.Min
}

func (r Rectu) Size() Vec2u {
	return r.Max.Sub(r.Min)
}

func (r Rectu) Width() uint32 {
	return r.Max[0] - r.Min[0]
}

func (r Rectu) Height() uint32 {
	return r.Max[1] - r.Min[1]
}

func (r Rectu) XYWH() (uint32, uint32, uint32, uint32) {
	x, y := r.Min.XY()
	w, h := r.Size().XY()
	return x, y, w, h
}

func (r Rectu) String() string {
	x, y, w, h := r.XYWH()
	return fmt.Sprintf("Rect(x=%v, y=%v, w=%v, h=%v)", x, y, w, h)
}
