// Code generated by generate.go: DO NOT EDIT.

package glm

import "unsafe"

type _ = unsafe.Pointer

// Mat2d is a 2x2 matrix.
// The default value is filled with all zero values.
type Mat2d [2][2]float64

func IdentityMat2d() Mat2d {
	var m Mat2d
	m[0][0] = 1
	m[1][1] = 1
	return m
}

func (m Mat2d) Mul(o Mat2d) Mat2d {
	mv := &m
	ov := &o

	return Mat2d{
		{
			mv[0][0]*ov[0][0] + mv[1][0]*ov[0][1],
			mv[0][1]*ov[0][0] + mv[1][1]*ov[0][1],
		},
		{
			mv[0][0]*ov[1][0] + mv[1][0]*ov[1][1],
			mv[0][1]*ov[1][0] + mv[1][1]*ov[1][1],
		},
	}
}

func (m Mat2d) Transpose() Mat2d {
	mv := &m

	return Mat2d{
		{
			mv[0][0],
			mv[1][0],
		},
		{
			mv[0][1],
			mv[1][1],
		},
	}
}

// Column returns a reference to the given column
func (m *Mat2d) Column(idx int) Vec2d {
	return *(*Vec2d)(&m[idx])
}
