// Code generated by generate.go: DO NOT EDIT.

package glm

import "unsafe"

type _ = unsafe.Pointer

// Mat2u is a 2x2 matrix.
// The default value is filled with all zero values.
type Mat2u [2][2]uint32

func IdentityMat2u() Mat2u {
	var m Mat2u
	m[0][0] = 1
	m[1][1] = 1
	return m
}

func (m Mat2u) Mul(o Mat2u) Mat2u {
	mv := &m
	ov := &o

	return Mat2u{
		{
			mv[0][0]*ov[0][0] + mv[1][0]*ov[0][1],
			mv[0][1]*ov[0][0] + mv[1][1]*ov[0][1],
		},
		{
			mv[0][0]*ov[1][0] + mv[1][0]*ov[1][1],
			mv[0][1]*ov[1][0] + mv[1][1]*ov[1][1],
		},
	}
}

func (m Mat2u) Transpose() Mat2u {
	mv := &m

	return Mat2u{
		{
			mv[0][0],
			mv[1][0],
		},
		{
			mv[0][1],
			mv[1][1],
		},
	}
}

// Column returns a reference to the given column
func (m *Mat2u) Column(idx int) Vec2u {
	return *(*Vec2u)(&m[idx])
}
