// Code generated by generate.go: DO NOT EDIT.

package glm

import "fmt"
import "math"

// Vec4d is a vector of dimension 4.
type Vec4d [4]float64

func (lhs Vec4d) Dot(rhs Vec4d) float64 {
	return lhs[0]*rhs[0] + lhs[1]*rhs[1] + lhs[2]*rhs[2] + lhs[3]*rhs[3]
}

func (lhs Vec4d) LengthSqr() float64 {
	return lhs.Dot(lhs)
}

func (lhs Vec4d) Length() float64 {
	return float64(math.Sqrt(float64(lhs.Dot(lhs))))
}

func (lhs Vec4d) Normalize() Vec4d {
	return lhs.Scale(1.0 / lhs.Length())
}

func (lhs Vec4d) Scale(s float64) Vec4d {
	return Vec4d{
		lhs[0] * s,
		lhs[1] * s,
		lhs[2] * s,
		lhs[3] * s,
	}
}

func (lhs Vec4d) Reciprocal() Vec4d {
	return Vec4d{
		1.0 / lhs[0],
		1.0 / lhs[1],
		1.0 / lhs[2],
		1.0 / lhs[3],
	}
}

func (lhs Vec4d) Add(rhs Vec4d) Vec4d {
	return Vec4d{
		lhs[0] + rhs[0],
		lhs[1] + rhs[1],
		lhs[2] + rhs[2],
		lhs[3] + rhs[3],
	}
}

func (lhs Vec4d) Sub(rhs Vec4d) Vec4d {
	return Vec4d{
		lhs[0] - rhs[0],
		lhs[1] - rhs[1],
		lhs[2] - rhs[2],
		lhs[3] - rhs[3],
	}
}

func (lhs Vec4d) Mul(rhs Vec4d) Vec4d {
	return Vec4d{
		lhs[0] * rhs[0],
		lhs[1] * rhs[1],
		lhs[2] * rhs[2],
		lhs[3] * rhs[3],
	}
}

func (lhs Vec4d) Div(rhs Vec4d) Vec4d {
	return Vec4d{
		lhs[0] / rhs[0],
		lhs[1] / rhs[1],
		lhs[2] / rhs[2],
		lhs[3] / rhs[3],
	}
}

func (lhs Vec4d) Min(rhs Vec4d) Vec4d {
	return Vec4d{
		min(lhs[0], rhs[0]),
		min(lhs[1], rhs[1]),
		min(lhs[2], rhs[2]),
		min(lhs[3], rhs[3]),
	}
}

func (lhs Vec4d) Max(rhs Vec4d) Vec4d {
	return Vec4d{
		max(lhs[0], rhs[0]),
		max(lhs[1], rhs[1]),
		max(lhs[2], rhs[2]),
		max(lhs[3], rhs[3]),
	}
}

func (lhs Vec4d) Truncate() Vec3d {
	return Vec3d{
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXX returns a new vector with the components of this
// vector in the order of XX.
func (lhs Vec4d) SwizzleXX() Vec2d {
	return Vec2d{
		lhs[0],
		lhs[0],
	}
}

// SwizzleXY returns a new vector with the components of this
// vector in the order of XY.
func (lhs Vec4d) SwizzleXY() Vec2d {
	return Vec2d{
		lhs[0],
		lhs[1],
	}
}

// SwizzleXZ returns a new vector with the components of this
// vector in the order of XZ.
func (lhs Vec4d) SwizzleXZ() Vec2d {
	return Vec2d{
		lhs[0],
		lhs[2],
	}
}

// SwizzleXW returns a new vector with the components of this
// vector in the order of XW.
func (lhs Vec4d) SwizzleXW() Vec2d {
	return Vec2d{
		lhs[0],
		lhs[3],
	}
}

// SwizzleYX returns a new vector with the components of this
// vector in the order of YX.
func (lhs Vec4d) SwizzleYX() Vec2d {
	return Vec2d{
		lhs[1],
		lhs[0],
	}
}

// SwizzleYY returns a new vector with the components of this
// vector in the order of YY.
func (lhs Vec4d) SwizzleYY() Vec2d {
	return Vec2d{
		lhs[1],
		lhs[1],
	}
}

// SwizzleYZ returns a new vector with the components of this
// vector in the order of YZ.
func (lhs Vec4d) SwizzleYZ() Vec2d {
	return Vec2d{
		lhs[1],
		lhs[2],
	}
}

// SwizzleYW returns a new vector with the components of this
// vector in the order of YW.
func (lhs Vec4d) SwizzleYW() Vec2d {
	return Vec2d{
		lhs[1],
		lhs[3],
	}
}

// SwizzleZX returns a new vector with the components of this
// vector in the order of ZX.
func (lhs Vec4d) SwizzleZX() Vec2d {
	return Vec2d{
		lhs[2],
		lhs[0],
	}
}

// SwizzleZY returns a new vector with the components of this
// vector in the order of ZY.
func (lhs Vec4d) SwizzleZY() Vec2d {
	return Vec2d{
		lhs[2],
		lhs[1],
	}
}

// SwizzleZZ returns a new vector with the components of this
// vector in the order of ZZ.
func (lhs Vec4d) SwizzleZZ() Vec2d {
	return Vec2d{
		lhs[2],
		lhs[2],
	}
}

// SwizzleZW returns a new vector with the components of this
// vector in the order of ZW.
func (lhs Vec4d) SwizzleZW() Vec2d {
	return Vec2d{
		lhs[2],
		lhs[3],
	}
}

// SwizzleWX returns a new vector with the components of this
// vector in the order of WX.
func (lhs Vec4d) SwizzleWX() Vec2d {
	return Vec2d{
		lhs[3],
		lhs[0],
	}
}

// SwizzleWY returns a new vector with the components of this
// vector in the order of WY.
func (lhs Vec4d) SwizzleWY() Vec2d {
	return Vec2d{
		lhs[3],
		lhs[1],
	}
}

// SwizzleWZ returns a new vector with the components of this
// vector in the order of WZ.
func (lhs Vec4d) SwizzleWZ() Vec2d {
	return Vec2d{
		lhs[3],
		lhs[2],
	}
}

// SwizzleWW returns a new vector with the components of this
// vector in the order of WW.
func (lhs Vec4d) SwizzleWW() Vec2d {
	return Vec2d{
		lhs[3],
		lhs[3],
	}
}

// SwizzleXXX returns a new vector with the components of this
// vector in the order of XXX.
func (lhs Vec4d) SwizzleXXX() Vec3d {
	return Vec3d{
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXXY returns a new vector with the components of this
// vector in the order of XXY.
func (lhs Vec4d) SwizzleXXY() Vec3d {
	return Vec3d{
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXXZ returns a new vector with the components of this
// vector in the order of XXZ.
func (lhs Vec4d) SwizzleXXZ() Vec3d {
	return Vec3d{
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXXW returns a new vector with the components of this
// vector in the order of XXW.
func (lhs Vec4d) SwizzleXXW() Vec3d {
	return Vec3d{
		lhs[0],
		lhs[0],
		lhs[3],
	}
}

// SwizzleXYX returns a new vector with the components of this
// vector in the order of XYX.
func (lhs Vec4d) SwizzleXYX() Vec3d {
	return Vec3d{
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXYY returns a new vector with the components of this
// vector in the order of XYY.
func (lhs Vec4d) SwizzleXYY() Vec3d {
	return Vec3d{
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXYZ returns a new vector with the components of this
// vector in the order of XYZ.
func (lhs Vec4d) SwizzleXYZ() Vec3d {
	return Vec3d{
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXYW returns a new vector with the components of this
// vector in the order of XYW.
func (lhs Vec4d) SwizzleXYW() Vec3d {
	return Vec3d{
		lhs[0],
		lhs[1],
		lhs[3],
	}
}

// SwizzleXZX returns a new vector with the components of this
// vector in the order of XZX.
func (lhs Vec4d) SwizzleXZX() Vec3d {
	return Vec3d{
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXZY returns a new vector with the components of this
// vector in the order of XZY.
func (lhs Vec4d) SwizzleXZY() Vec3d {
	return Vec3d{
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXZZ returns a new vector with the components of this
// vector in the order of XZZ.
func (lhs Vec4d) SwizzleXZZ() Vec3d {
	return Vec3d{
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleXZW returns a new vector with the components of this
// vector in the order of XZW.
func (lhs Vec4d) SwizzleXZW() Vec3d {
	return Vec3d{
		lhs[0],
		lhs[2],
		lhs[3],
	}
}

// SwizzleXWX returns a new vector with the components of this
// vector in the order of XWX.
func (lhs Vec4d) SwizzleXWX() Vec3d {
	return Vec3d{
		lhs[0],
		lhs[3],
		lhs[0],
	}
}

// SwizzleXWY returns a new vector with the components of this
// vector in the order of XWY.
func (lhs Vec4d) SwizzleXWY() Vec3d {
	return Vec3d{
		lhs[0],
		lhs[3],
		lhs[1],
	}
}

// SwizzleXWZ returns a new vector with the components of this
// vector in the order of XWZ.
func (lhs Vec4d) SwizzleXWZ() Vec3d {
	return Vec3d{
		lhs[0],
		lhs[3],
		lhs[2],
	}
}

// SwizzleXWW returns a new vector with the components of this
// vector in the order of XWW.
func (lhs Vec4d) SwizzleXWW() Vec3d {
	return Vec3d{
		lhs[0],
		lhs[3],
		lhs[3],
	}
}

// SwizzleYXX returns a new vector with the components of this
// vector in the order of YXX.
func (lhs Vec4d) SwizzleYXX() Vec3d {
	return Vec3d{
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYXY returns a new vector with the components of this
// vector in the order of YXY.
func (lhs Vec4d) SwizzleYXY() Vec3d {
	return Vec3d{
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYXZ returns a new vector with the components of this
// vector in the order of YXZ.
func (lhs Vec4d) SwizzleYXZ() Vec3d {
	return Vec3d{
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYXW returns a new vector with the components of this
// vector in the order of YXW.
func (lhs Vec4d) SwizzleYXW() Vec3d {
	return Vec3d{
		lhs[1],
		lhs[0],
		lhs[3],
	}
}

// SwizzleYYX returns a new vector with the components of this
// vector in the order of YYX.
func (lhs Vec4d) SwizzleYYX() Vec3d {
	return Vec3d{
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYYY returns a new vector with the components of this
// vector in the order of YYY.
func (lhs Vec4d) SwizzleYYY() Vec3d {
	return Vec3d{
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYYZ returns a new vector with the components of this
// vector in the order of YYZ.
func (lhs Vec4d) SwizzleYYZ() Vec3d {
	return Vec3d{
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYYW returns a new vector with the components of this
// vector in the order of YYW.
func (lhs Vec4d) SwizzleYYW() Vec3d {
	return Vec3d{
		lhs[1],
		lhs[1],
		lhs[3],
	}
}

// SwizzleYZX returns a new vector with the components of this
// vector in the order of YZX.
func (lhs Vec4d) SwizzleYZX() Vec3d {
	return Vec3d{
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYZY returns a new vector with the components of this
// vector in the order of YZY.
func (lhs Vec4d) SwizzleYZY() Vec3d {
	return Vec3d{
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYZZ returns a new vector with the components of this
// vector in the order of YZZ.
func (lhs Vec4d) SwizzleYZZ() Vec3d {
	return Vec3d{
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYZW returns a new vector with the components of this
// vector in the order of YZW.
func (lhs Vec4d) SwizzleYZW() Vec3d {
	return Vec3d{
		lhs[1],
		lhs[2],
		lhs[3],
	}
}

// SwizzleYWX returns a new vector with the components of this
// vector in the order of YWX.
func (lhs Vec4d) SwizzleYWX() Vec3d {
	return Vec3d{
		lhs[1],
		lhs[3],
		lhs[0],
	}
}

// SwizzleYWY returns a new vector with the components of this
// vector in the order of YWY.
func (lhs Vec4d) SwizzleYWY() Vec3d {
	return Vec3d{
		lhs[1],
		lhs[3],
		lhs[1],
	}
}

// SwizzleYWZ returns a new vector with the components of this
// vector in the order of YWZ.
func (lhs Vec4d) SwizzleYWZ() Vec3d {
	return Vec3d{
		lhs[1],
		lhs[3],
		lhs[2],
	}
}

// SwizzleYWW returns a new vector with the components of this
// vector in the order of YWW.
func (lhs Vec4d) SwizzleYWW() Vec3d {
	return Vec3d{
		lhs[1],
		lhs[3],
		lhs[3],
	}
}

// SwizzleZXX returns a new vector with the components of this
// vector in the order of ZXX.
func (lhs Vec4d) SwizzleZXX() Vec3d {
	return Vec3d{
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZXY returns a new vector with the components of this
// vector in the order of ZXY.
func (lhs Vec4d) SwizzleZXY() Vec3d {
	return Vec3d{
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZXZ returns a new vector with the components of this
// vector in the order of ZXZ.
func (lhs Vec4d) SwizzleZXZ() Vec3d {
	return Vec3d{
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZXW returns a new vector with the components of this
// vector in the order of ZXW.
func (lhs Vec4d) SwizzleZXW() Vec3d {
	return Vec3d{
		lhs[2],
		lhs[0],
		lhs[3],
	}
}

// SwizzleZYX returns a new vector with the components of this
// vector in the order of ZYX.
func (lhs Vec4d) SwizzleZYX() Vec3d {
	return Vec3d{
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZYY returns a new vector with the components of this
// vector in the order of ZYY.
func (lhs Vec4d) SwizzleZYY() Vec3d {
	return Vec3d{
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZYZ returns a new vector with the components of this
// vector in the order of ZYZ.
func (lhs Vec4d) SwizzleZYZ() Vec3d {
	return Vec3d{
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZYW returns a new vector with the components of this
// vector in the order of ZYW.
func (lhs Vec4d) SwizzleZYW() Vec3d {
	return Vec3d{
		lhs[2],
		lhs[1],
		lhs[3],
	}
}

// SwizzleZZX returns a new vector with the components of this
// vector in the order of ZZX.
func (lhs Vec4d) SwizzleZZX() Vec3d {
	return Vec3d{
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZZY returns a new vector with the components of this
// vector in the order of ZZY.
func (lhs Vec4d) SwizzleZZY() Vec3d {
	return Vec3d{
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZZZ returns a new vector with the components of this
// vector in the order of ZZZ.
func (lhs Vec4d) SwizzleZZZ() Vec3d {
	return Vec3d{
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZZW returns a new vector with the components of this
// vector in the order of ZZW.
func (lhs Vec4d) SwizzleZZW() Vec3d {
	return Vec3d{
		lhs[2],
		lhs[2],
		lhs[3],
	}
}

// SwizzleZWX returns a new vector with the components of this
// vector in the order of ZWX.
func (lhs Vec4d) SwizzleZWX() Vec3d {
	return Vec3d{
		lhs[2],
		lhs[3],
		lhs[0],
	}
}

// SwizzleZWY returns a new vector with the components of this
// vector in the order of ZWY.
func (lhs Vec4d) SwizzleZWY() Vec3d {
	return Vec3d{
		lhs[2],
		lhs[3],
		lhs[1],
	}
}

// SwizzleZWZ returns a new vector with the components of this
// vector in the order of ZWZ.
func (lhs Vec4d) SwizzleZWZ() Vec3d {
	return Vec3d{
		lhs[2],
		lhs[3],
		lhs[2],
	}
}

// SwizzleZWW returns a new vector with the components of this
// vector in the order of ZWW.
func (lhs Vec4d) SwizzleZWW() Vec3d {
	return Vec3d{
		lhs[2],
		lhs[3],
		lhs[3],
	}
}

// SwizzleWXX returns a new vector with the components of this
// vector in the order of WXX.
func (lhs Vec4d) SwizzleWXX() Vec3d {
	return Vec3d{
		lhs[3],
		lhs[0],
		lhs[0],
	}
}

// SwizzleWXY returns a new vector with the components of this
// vector in the order of WXY.
func (lhs Vec4d) SwizzleWXY() Vec3d {
	return Vec3d{
		lhs[3],
		lhs[0],
		lhs[1],
	}
}

// SwizzleWXZ returns a new vector with the components of this
// vector in the order of WXZ.
func (lhs Vec4d) SwizzleWXZ() Vec3d {
	return Vec3d{
		lhs[3],
		lhs[0],
		lhs[2],
	}
}

// SwizzleWXW returns a new vector with the components of this
// vector in the order of WXW.
func (lhs Vec4d) SwizzleWXW() Vec3d {
	return Vec3d{
		lhs[3],
		lhs[0],
		lhs[3],
	}
}

// SwizzleWYX returns a new vector with the components of this
// vector in the order of WYX.
func (lhs Vec4d) SwizzleWYX() Vec3d {
	return Vec3d{
		lhs[3],
		lhs[1],
		lhs[0],
	}
}

// SwizzleWYY returns a new vector with the components of this
// vector in the order of WYY.
func (lhs Vec4d) SwizzleWYY() Vec3d {
	return Vec3d{
		lhs[3],
		lhs[1],
		lhs[1],
	}
}

// SwizzleWYZ returns a new vector with the components of this
// vector in the order of WYZ.
func (lhs Vec4d) SwizzleWYZ() Vec3d {
	return Vec3d{
		lhs[3],
		lhs[1],
		lhs[2],
	}
}

// SwizzleWYW returns a new vector with the components of this
// vector in the order of WYW.
func (lhs Vec4d) SwizzleWYW() Vec3d {
	return Vec3d{
		lhs[3],
		lhs[1],
		lhs[3],
	}
}

// SwizzleWZX returns a new vector with the components of this
// vector in the order of WZX.
func (lhs Vec4d) SwizzleWZX() Vec3d {
	return Vec3d{
		lhs[3],
		lhs[2],
		lhs[0],
	}
}

// SwizzleWZY returns a new vector with the components of this
// vector in the order of WZY.
func (lhs Vec4d) SwizzleWZY() Vec3d {
	return Vec3d{
		lhs[3],
		lhs[2],
		lhs[1],
	}
}

// SwizzleWZZ returns a new vector with the components of this
// vector in the order of WZZ.
func (lhs Vec4d) SwizzleWZZ() Vec3d {
	return Vec3d{
		lhs[3],
		lhs[2],
		lhs[2],
	}
}

// SwizzleWZW returns a new vector with the components of this
// vector in the order of WZW.
func (lhs Vec4d) SwizzleWZW() Vec3d {
	return Vec3d{
		lhs[3],
		lhs[2],
		lhs[3],
	}
}

// SwizzleWWX returns a new vector with the components of this
// vector in the order of WWX.
func (lhs Vec4d) SwizzleWWX() Vec3d {
	return Vec3d{
		lhs[3],
		lhs[3],
		lhs[0],
	}
}

// SwizzleWWY returns a new vector with the components of this
// vector in the order of WWY.
func (lhs Vec4d) SwizzleWWY() Vec3d {
	return Vec3d{
		lhs[3],
		lhs[3],
		lhs[1],
	}
}

// SwizzleWWZ returns a new vector with the components of this
// vector in the order of WWZ.
func (lhs Vec4d) SwizzleWWZ() Vec3d {
	return Vec3d{
		lhs[3],
		lhs[3],
		lhs[2],
	}
}

// SwizzleWWW returns a new vector with the components of this
// vector in the order of WWW.
func (lhs Vec4d) SwizzleWWW() Vec3d {
	return Vec3d{
		lhs[3],
		lhs[3],
		lhs[3],
	}
}

// SwizzleXXXX returns a new vector with the components of this
// vector in the order of XXXX.
func (lhs Vec4d) SwizzleXXXX() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXXXY returns a new vector with the components of this
// vector in the order of XXXY.
func (lhs Vec4d) SwizzleXXXY() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXXXZ returns a new vector with the components of this
// vector in the order of XXXZ.
func (lhs Vec4d) SwizzleXXXZ() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXXXW returns a new vector with the components of this
// vector in the order of XXXW.
func (lhs Vec4d) SwizzleXXXW() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[0],
		lhs[0],
		lhs[3],
	}
}

// SwizzleXXYX returns a new vector with the components of this
// vector in the order of XXYX.
func (lhs Vec4d) SwizzleXXYX() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXXYY returns a new vector with the components of this
// vector in the order of XXYY.
func (lhs Vec4d) SwizzleXXYY() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXXYZ returns a new vector with the components of this
// vector in the order of XXYZ.
func (lhs Vec4d) SwizzleXXYZ() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXXYW returns a new vector with the components of this
// vector in the order of XXYW.
func (lhs Vec4d) SwizzleXXYW() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[0],
		lhs[1],
		lhs[3],
	}
}

// SwizzleXXZX returns a new vector with the components of this
// vector in the order of XXZX.
func (lhs Vec4d) SwizzleXXZX() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXXZY returns a new vector with the components of this
// vector in the order of XXZY.
func (lhs Vec4d) SwizzleXXZY() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXXZZ returns a new vector with the components of this
// vector in the order of XXZZ.
func (lhs Vec4d) SwizzleXXZZ() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleXXZW returns a new vector with the components of this
// vector in the order of XXZW.
func (lhs Vec4d) SwizzleXXZW() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[0],
		lhs[2],
		lhs[3],
	}
}

// SwizzleXXWX returns a new vector with the components of this
// vector in the order of XXWX.
func (lhs Vec4d) SwizzleXXWX() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[0],
		lhs[3],
		lhs[0],
	}
}

// SwizzleXXWY returns a new vector with the components of this
// vector in the order of XXWY.
func (lhs Vec4d) SwizzleXXWY() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[0],
		lhs[3],
		lhs[1],
	}
}

// SwizzleXXWZ returns a new vector with the components of this
// vector in the order of XXWZ.
func (lhs Vec4d) SwizzleXXWZ() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[0],
		lhs[3],
		lhs[2],
	}
}

// SwizzleXXWW returns a new vector with the components of this
// vector in the order of XXWW.
func (lhs Vec4d) SwizzleXXWW() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[0],
		lhs[3],
		lhs[3],
	}
}

// SwizzleXYXX returns a new vector with the components of this
// vector in the order of XYXX.
func (lhs Vec4d) SwizzleXYXX() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXYXY returns a new vector with the components of this
// vector in the order of XYXY.
func (lhs Vec4d) SwizzleXYXY() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXYXZ returns a new vector with the components of this
// vector in the order of XYXZ.
func (lhs Vec4d) SwizzleXYXZ() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXYXW returns a new vector with the components of this
// vector in the order of XYXW.
func (lhs Vec4d) SwizzleXYXW() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[1],
		lhs[0],
		lhs[3],
	}
}

// SwizzleXYYX returns a new vector with the components of this
// vector in the order of XYYX.
func (lhs Vec4d) SwizzleXYYX() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXYYY returns a new vector with the components of this
// vector in the order of XYYY.
func (lhs Vec4d) SwizzleXYYY() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXYYZ returns a new vector with the components of this
// vector in the order of XYYZ.
func (lhs Vec4d) SwizzleXYYZ() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXYYW returns a new vector with the components of this
// vector in the order of XYYW.
func (lhs Vec4d) SwizzleXYYW() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[1],
		lhs[1],
		lhs[3],
	}
}

// SwizzleXYZX returns a new vector with the components of this
// vector in the order of XYZX.
func (lhs Vec4d) SwizzleXYZX() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXYZY returns a new vector with the components of this
// vector in the order of XYZY.
func (lhs Vec4d) SwizzleXYZY() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXYZZ returns a new vector with the components of this
// vector in the order of XYZZ.
func (lhs Vec4d) SwizzleXYZZ() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleXYZW returns a new vector with the components of this
// vector in the order of XYZW.
func (lhs Vec4d) SwizzleXYZW() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[1],
		lhs[2],
		lhs[3],
	}
}

// SwizzleXYWX returns a new vector with the components of this
// vector in the order of XYWX.
func (lhs Vec4d) SwizzleXYWX() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[1],
		lhs[3],
		lhs[0],
	}
}

// SwizzleXYWY returns a new vector with the components of this
// vector in the order of XYWY.
func (lhs Vec4d) SwizzleXYWY() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[1],
		lhs[3],
		lhs[1],
	}
}

// SwizzleXYWZ returns a new vector with the components of this
// vector in the order of XYWZ.
func (lhs Vec4d) SwizzleXYWZ() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[1],
		lhs[3],
		lhs[2],
	}
}

// SwizzleXYWW returns a new vector with the components of this
// vector in the order of XYWW.
func (lhs Vec4d) SwizzleXYWW() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[1],
		lhs[3],
		lhs[3],
	}
}

// SwizzleXZXX returns a new vector with the components of this
// vector in the order of XZXX.
func (lhs Vec4d) SwizzleXZXX() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXZXY returns a new vector with the components of this
// vector in the order of XZXY.
func (lhs Vec4d) SwizzleXZXY() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXZXZ returns a new vector with the components of this
// vector in the order of XZXZ.
func (lhs Vec4d) SwizzleXZXZ() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXZXW returns a new vector with the components of this
// vector in the order of XZXW.
func (lhs Vec4d) SwizzleXZXW() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[2],
		lhs[0],
		lhs[3],
	}
}

// SwizzleXZYX returns a new vector with the components of this
// vector in the order of XZYX.
func (lhs Vec4d) SwizzleXZYX() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXZYY returns a new vector with the components of this
// vector in the order of XZYY.
func (lhs Vec4d) SwizzleXZYY() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXZYZ returns a new vector with the components of this
// vector in the order of XZYZ.
func (lhs Vec4d) SwizzleXZYZ() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXZYW returns a new vector with the components of this
// vector in the order of XZYW.
func (lhs Vec4d) SwizzleXZYW() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[2],
		lhs[1],
		lhs[3],
	}
}

// SwizzleXZZX returns a new vector with the components of this
// vector in the order of XZZX.
func (lhs Vec4d) SwizzleXZZX() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXZZY returns a new vector with the components of this
// vector in the order of XZZY.
func (lhs Vec4d) SwizzleXZZY() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXZZZ returns a new vector with the components of this
// vector in the order of XZZZ.
func (lhs Vec4d) SwizzleXZZZ() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

// SwizzleXZZW returns a new vector with the components of this
// vector in the order of XZZW.
func (lhs Vec4d) SwizzleXZZW() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[2],
		lhs[2],
		lhs[3],
	}
}

// SwizzleXZWX returns a new vector with the components of this
// vector in the order of XZWX.
func (lhs Vec4d) SwizzleXZWX() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[2],
		lhs[3],
		lhs[0],
	}
}

// SwizzleXZWY returns a new vector with the components of this
// vector in the order of XZWY.
func (lhs Vec4d) SwizzleXZWY() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[2],
		lhs[3],
		lhs[1],
	}
}

// SwizzleXZWZ returns a new vector with the components of this
// vector in the order of XZWZ.
func (lhs Vec4d) SwizzleXZWZ() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[2],
		lhs[3],
		lhs[2],
	}
}

// SwizzleXZWW returns a new vector with the components of this
// vector in the order of XZWW.
func (lhs Vec4d) SwizzleXZWW() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[2],
		lhs[3],
		lhs[3],
	}
}

// SwizzleXWXX returns a new vector with the components of this
// vector in the order of XWXX.
func (lhs Vec4d) SwizzleXWXX() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[3],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXWXY returns a new vector with the components of this
// vector in the order of XWXY.
func (lhs Vec4d) SwizzleXWXY() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[3],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXWXZ returns a new vector with the components of this
// vector in the order of XWXZ.
func (lhs Vec4d) SwizzleXWXZ() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[3],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXWXW returns a new vector with the components of this
// vector in the order of XWXW.
func (lhs Vec4d) SwizzleXWXW() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[3],
		lhs[0],
		lhs[3],
	}
}

// SwizzleXWYX returns a new vector with the components of this
// vector in the order of XWYX.
func (lhs Vec4d) SwizzleXWYX() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[3],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXWYY returns a new vector with the components of this
// vector in the order of XWYY.
func (lhs Vec4d) SwizzleXWYY() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[3],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXWYZ returns a new vector with the components of this
// vector in the order of XWYZ.
func (lhs Vec4d) SwizzleXWYZ() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[3],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXWYW returns a new vector with the components of this
// vector in the order of XWYW.
func (lhs Vec4d) SwizzleXWYW() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[3],
		lhs[1],
		lhs[3],
	}
}

// SwizzleXWZX returns a new vector with the components of this
// vector in the order of XWZX.
func (lhs Vec4d) SwizzleXWZX() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[3],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXWZY returns a new vector with the components of this
// vector in the order of XWZY.
func (lhs Vec4d) SwizzleXWZY() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[3],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXWZZ returns a new vector with the components of this
// vector in the order of XWZZ.
func (lhs Vec4d) SwizzleXWZZ() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[3],
		lhs[2],
		lhs[2],
	}
}

// SwizzleXWZW returns a new vector with the components of this
// vector in the order of XWZW.
func (lhs Vec4d) SwizzleXWZW() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[3],
		lhs[2],
		lhs[3],
	}
}

// SwizzleXWWX returns a new vector with the components of this
// vector in the order of XWWX.
func (lhs Vec4d) SwizzleXWWX() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[3],
		lhs[3],
		lhs[0],
	}
}

// SwizzleXWWY returns a new vector with the components of this
// vector in the order of XWWY.
func (lhs Vec4d) SwizzleXWWY() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[3],
		lhs[3],
		lhs[1],
	}
}

// SwizzleXWWZ returns a new vector with the components of this
// vector in the order of XWWZ.
func (lhs Vec4d) SwizzleXWWZ() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[3],
		lhs[3],
		lhs[2],
	}
}

// SwizzleXWWW returns a new vector with the components of this
// vector in the order of XWWW.
func (lhs Vec4d) SwizzleXWWW() Vec4d {
	return Vec4d{
		lhs[0],
		lhs[3],
		lhs[3],
		lhs[3],
	}
}

// SwizzleYXXX returns a new vector with the components of this
// vector in the order of YXXX.
func (lhs Vec4d) SwizzleYXXX() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYXXY returns a new vector with the components of this
// vector in the order of YXXY.
func (lhs Vec4d) SwizzleYXXY() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYXXZ returns a new vector with the components of this
// vector in the order of YXXZ.
func (lhs Vec4d) SwizzleYXXZ() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYXXW returns a new vector with the components of this
// vector in the order of YXXW.
func (lhs Vec4d) SwizzleYXXW() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[0],
		lhs[0],
		lhs[3],
	}
}

// SwizzleYXYX returns a new vector with the components of this
// vector in the order of YXYX.
func (lhs Vec4d) SwizzleYXYX() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYXYY returns a new vector with the components of this
// vector in the order of YXYY.
func (lhs Vec4d) SwizzleYXYY() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYXYZ returns a new vector with the components of this
// vector in the order of YXYZ.
func (lhs Vec4d) SwizzleYXYZ() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYXYW returns a new vector with the components of this
// vector in the order of YXYW.
func (lhs Vec4d) SwizzleYXYW() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[0],
		lhs[1],
		lhs[3],
	}
}

// SwizzleYXZX returns a new vector with the components of this
// vector in the order of YXZX.
func (lhs Vec4d) SwizzleYXZX() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYXZY returns a new vector with the components of this
// vector in the order of YXZY.
func (lhs Vec4d) SwizzleYXZY() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYXZZ returns a new vector with the components of this
// vector in the order of YXZZ.
func (lhs Vec4d) SwizzleYXZZ() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYXZW returns a new vector with the components of this
// vector in the order of YXZW.
func (lhs Vec4d) SwizzleYXZW() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[0],
		lhs[2],
		lhs[3],
	}
}

// SwizzleYXWX returns a new vector with the components of this
// vector in the order of YXWX.
func (lhs Vec4d) SwizzleYXWX() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[0],
		lhs[3],
		lhs[0],
	}
}

// SwizzleYXWY returns a new vector with the components of this
// vector in the order of YXWY.
func (lhs Vec4d) SwizzleYXWY() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[0],
		lhs[3],
		lhs[1],
	}
}

// SwizzleYXWZ returns a new vector with the components of this
// vector in the order of YXWZ.
func (lhs Vec4d) SwizzleYXWZ() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[0],
		lhs[3],
		lhs[2],
	}
}

// SwizzleYXWW returns a new vector with the components of this
// vector in the order of YXWW.
func (lhs Vec4d) SwizzleYXWW() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[0],
		lhs[3],
		lhs[3],
	}
}

// SwizzleYYXX returns a new vector with the components of this
// vector in the order of YYXX.
func (lhs Vec4d) SwizzleYYXX() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYYXY returns a new vector with the components of this
// vector in the order of YYXY.
func (lhs Vec4d) SwizzleYYXY() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYYXZ returns a new vector with the components of this
// vector in the order of YYXZ.
func (lhs Vec4d) SwizzleYYXZ() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYYXW returns a new vector with the components of this
// vector in the order of YYXW.
func (lhs Vec4d) SwizzleYYXW() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[1],
		lhs[0],
		lhs[3],
	}
}

// SwizzleYYYX returns a new vector with the components of this
// vector in the order of YYYX.
func (lhs Vec4d) SwizzleYYYX() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYYYY returns a new vector with the components of this
// vector in the order of YYYY.
func (lhs Vec4d) SwizzleYYYY() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYYYZ returns a new vector with the components of this
// vector in the order of YYYZ.
func (lhs Vec4d) SwizzleYYYZ() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYYYW returns a new vector with the components of this
// vector in the order of YYYW.
func (lhs Vec4d) SwizzleYYYW() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[1],
		lhs[1],
		lhs[3],
	}
}

// SwizzleYYZX returns a new vector with the components of this
// vector in the order of YYZX.
func (lhs Vec4d) SwizzleYYZX() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYYZY returns a new vector with the components of this
// vector in the order of YYZY.
func (lhs Vec4d) SwizzleYYZY() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYYZZ returns a new vector with the components of this
// vector in the order of YYZZ.
func (lhs Vec4d) SwizzleYYZZ() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYYZW returns a new vector with the components of this
// vector in the order of YYZW.
func (lhs Vec4d) SwizzleYYZW() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[1],
		lhs[2],
		lhs[3],
	}
}

// SwizzleYYWX returns a new vector with the components of this
// vector in the order of YYWX.
func (lhs Vec4d) SwizzleYYWX() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[1],
		lhs[3],
		lhs[0],
	}
}

// SwizzleYYWY returns a new vector with the components of this
// vector in the order of YYWY.
func (lhs Vec4d) SwizzleYYWY() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[1],
		lhs[3],
		lhs[1],
	}
}

// SwizzleYYWZ returns a new vector with the components of this
// vector in the order of YYWZ.
func (lhs Vec4d) SwizzleYYWZ() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[1],
		lhs[3],
		lhs[2],
	}
}

// SwizzleYYWW returns a new vector with the components of this
// vector in the order of YYWW.
func (lhs Vec4d) SwizzleYYWW() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[1],
		lhs[3],
		lhs[3],
	}
}

// SwizzleYZXX returns a new vector with the components of this
// vector in the order of YZXX.
func (lhs Vec4d) SwizzleYZXX() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYZXY returns a new vector with the components of this
// vector in the order of YZXY.
func (lhs Vec4d) SwizzleYZXY() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYZXZ returns a new vector with the components of this
// vector in the order of YZXZ.
func (lhs Vec4d) SwizzleYZXZ() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYZXW returns a new vector with the components of this
// vector in the order of YZXW.
func (lhs Vec4d) SwizzleYZXW() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[2],
		lhs[0],
		lhs[3],
	}
}

// SwizzleYZYX returns a new vector with the components of this
// vector in the order of YZYX.
func (lhs Vec4d) SwizzleYZYX() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYZYY returns a new vector with the components of this
// vector in the order of YZYY.
func (lhs Vec4d) SwizzleYZYY() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYZYZ returns a new vector with the components of this
// vector in the order of YZYZ.
func (lhs Vec4d) SwizzleYZYZ() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYZYW returns a new vector with the components of this
// vector in the order of YZYW.
func (lhs Vec4d) SwizzleYZYW() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[2],
		lhs[1],
		lhs[3],
	}
}

// SwizzleYZZX returns a new vector with the components of this
// vector in the order of YZZX.
func (lhs Vec4d) SwizzleYZZX() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYZZY returns a new vector with the components of this
// vector in the order of YZZY.
func (lhs Vec4d) SwizzleYZZY() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYZZZ returns a new vector with the components of this
// vector in the order of YZZZ.
func (lhs Vec4d) SwizzleYZZZ() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYZZW returns a new vector with the components of this
// vector in the order of YZZW.
func (lhs Vec4d) SwizzleYZZW() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[2],
		lhs[2],
		lhs[3],
	}
}

// SwizzleYZWX returns a new vector with the components of this
// vector in the order of YZWX.
func (lhs Vec4d) SwizzleYZWX() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[2],
		lhs[3],
		lhs[0],
	}
}

// SwizzleYZWY returns a new vector with the components of this
// vector in the order of YZWY.
func (lhs Vec4d) SwizzleYZWY() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[2],
		lhs[3],
		lhs[1],
	}
}

// SwizzleYZWZ returns a new vector with the components of this
// vector in the order of YZWZ.
func (lhs Vec4d) SwizzleYZWZ() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[2],
		lhs[3],
		lhs[2],
	}
}

// SwizzleYZWW returns a new vector with the components of this
// vector in the order of YZWW.
func (lhs Vec4d) SwizzleYZWW() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[2],
		lhs[3],
		lhs[3],
	}
}

// SwizzleYWXX returns a new vector with the components of this
// vector in the order of YWXX.
func (lhs Vec4d) SwizzleYWXX() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[3],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYWXY returns a new vector with the components of this
// vector in the order of YWXY.
func (lhs Vec4d) SwizzleYWXY() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[3],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYWXZ returns a new vector with the components of this
// vector in the order of YWXZ.
func (lhs Vec4d) SwizzleYWXZ() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[3],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYWXW returns a new vector with the components of this
// vector in the order of YWXW.
func (lhs Vec4d) SwizzleYWXW() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[3],
		lhs[0],
		lhs[3],
	}
}

// SwizzleYWYX returns a new vector with the components of this
// vector in the order of YWYX.
func (lhs Vec4d) SwizzleYWYX() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[3],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYWYY returns a new vector with the components of this
// vector in the order of YWYY.
func (lhs Vec4d) SwizzleYWYY() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[3],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYWYZ returns a new vector with the components of this
// vector in the order of YWYZ.
func (lhs Vec4d) SwizzleYWYZ() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[3],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYWYW returns a new vector with the components of this
// vector in the order of YWYW.
func (lhs Vec4d) SwizzleYWYW() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[3],
		lhs[1],
		lhs[3],
	}
}

// SwizzleYWZX returns a new vector with the components of this
// vector in the order of YWZX.
func (lhs Vec4d) SwizzleYWZX() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[3],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYWZY returns a new vector with the components of this
// vector in the order of YWZY.
func (lhs Vec4d) SwizzleYWZY() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[3],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYWZZ returns a new vector with the components of this
// vector in the order of YWZZ.
func (lhs Vec4d) SwizzleYWZZ() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[3],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYWZW returns a new vector with the components of this
// vector in the order of YWZW.
func (lhs Vec4d) SwizzleYWZW() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[3],
		lhs[2],
		lhs[3],
	}
}

// SwizzleYWWX returns a new vector with the components of this
// vector in the order of YWWX.
func (lhs Vec4d) SwizzleYWWX() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[3],
		lhs[3],
		lhs[0],
	}
}

// SwizzleYWWY returns a new vector with the components of this
// vector in the order of YWWY.
func (lhs Vec4d) SwizzleYWWY() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[3],
		lhs[3],
		lhs[1],
	}
}

// SwizzleYWWZ returns a new vector with the components of this
// vector in the order of YWWZ.
func (lhs Vec4d) SwizzleYWWZ() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[3],
		lhs[3],
		lhs[2],
	}
}

// SwizzleYWWW returns a new vector with the components of this
// vector in the order of YWWW.
func (lhs Vec4d) SwizzleYWWW() Vec4d {
	return Vec4d{
		lhs[1],
		lhs[3],
		lhs[3],
		lhs[3],
	}
}

// SwizzleZXXX returns a new vector with the components of this
// vector in the order of ZXXX.
func (lhs Vec4d) SwizzleZXXX() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZXXY returns a new vector with the components of this
// vector in the order of ZXXY.
func (lhs Vec4d) SwizzleZXXY() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZXXZ returns a new vector with the components of this
// vector in the order of ZXXZ.
func (lhs Vec4d) SwizzleZXXZ() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZXXW returns a new vector with the components of this
// vector in the order of ZXXW.
func (lhs Vec4d) SwizzleZXXW() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[0],
		lhs[0],
		lhs[3],
	}
}

// SwizzleZXYX returns a new vector with the components of this
// vector in the order of ZXYX.
func (lhs Vec4d) SwizzleZXYX() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZXYY returns a new vector with the components of this
// vector in the order of ZXYY.
func (lhs Vec4d) SwizzleZXYY() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZXYZ returns a new vector with the components of this
// vector in the order of ZXYZ.
func (lhs Vec4d) SwizzleZXYZ() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZXYW returns a new vector with the components of this
// vector in the order of ZXYW.
func (lhs Vec4d) SwizzleZXYW() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[0],
		lhs[1],
		lhs[3],
	}
}

// SwizzleZXZX returns a new vector with the components of this
// vector in the order of ZXZX.
func (lhs Vec4d) SwizzleZXZX() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZXZY returns a new vector with the components of this
// vector in the order of ZXZY.
func (lhs Vec4d) SwizzleZXZY() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZXZZ returns a new vector with the components of this
// vector in the order of ZXZZ.
func (lhs Vec4d) SwizzleZXZZ() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZXZW returns a new vector with the components of this
// vector in the order of ZXZW.
func (lhs Vec4d) SwizzleZXZW() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[0],
		lhs[2],
		lhs[3],
	}
}

// SwizzleZXWX returns a new vector with the components of this
// vector in the order of ZXWX.
func (lhs Vec4d) SwizzleZXWX() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[0],
		lhs[3],
		lhs[0],
	}
}

// SwizzleZXWY returns a new vector with the components of this
// vector in the order of ZXWY.
func (lhs Vec4d) SwizzleZXWY() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[0],
		lhs[3],
		lhs[1],
	}
}

// SwizzleZXWZ returns a new vector with the components of this
// vector in the order of ZXWZ.
func (lhs Vec4d) SwizzleZXWZ() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[0],
		lhs[3],
		lhs[2],
	}
}

// SwizzleZXWW returns a new vector with the components of this
// vector in the order of ZXWW.
func (lhs Vec4d) SwizzleZXWW() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[0],
		lhs[3],
		lhs[3],
	}
}

// SwizzleZYXX returns a new vector with the components of this
// vector in the order of ZYXX.
func (lhs Vec4d) SwizzleZYXX() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZYXY returns a new vector with the components of this
// vector in the order of ZYXY.
func (lhs Vec4d) SwizzleZYXY() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZYXZ returns a new vector with the components of this
// vector in the order of ZYXZ.
func (lhs Vec4d) SwizzleZYXZ() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZYXW returns a new vector with the components of this
// vector in the order of ZYXW.
func (lhs Vec4d) SwizzleZYXW() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[1],
		lhs[0],
		lhs[3],
	}
}

// SwizzleZYYX returns a new vector with the components of this
// vector in the order of ZYYX.
func (lhs Vec4d) SwizzleZYYX() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZYYY returns a new vector with the components of this
// vector in the order of ZYYY.
func (lhs Vec4d) SwizzleZYYY() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZYYZ returns a new vector with the components of this
// vector in the order of ZYYZ.
func (lhs Vec4d) SwizzleZYYZ() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZYYW returns a new vector with the components of this
// vector in the order of ZYYW.
func (lhs Vec4d) SwizzleZYYW() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[1],
		lhs[1],
		lhs[3],
	}
}

// SwizzleZYZX returns a new vector with the components of this
// vector in the order of ZYZX.
func (lhs Vec4d) SwizzleZYZX() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZYZY returns a new vector with the components of this
// vector in the order of ZYZY.
func (lhs Vec4d) SwizzleZYZY() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZYZZ returns a new vector with the components of this
// vector in the order of ZYZZ.
func (lhs Vec4d) SwizzleZYZZ() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZYZW returns a new vector with the components of this
// vector in the order of ZYZW.
func (lhs Vec4d) SwizzleZYZW() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[1],
		lhs[2],
		lhs[3],
	}
}

// SwizzleZYWX returns a new vector with the components of this
// vector in the order of ZYWX.
func (lhs Vec4d) SwizzleZYWX() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[1],
		lhs[3],
		lhs[0],
	}
}

// SwizzleZYWY returns a new vector with the components of this
// vector in the order of ZYWY.
func (lhs Vec4d) SwizzleZYWY() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[1],
		lhs[3],
		lhs[1],
	}
}

// SwizzleZYWZ returns a new vector with the components of this
// vector in the order of ZYWZ.
func (lhs Vec4d) SwizzleZYWZ() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[1],
		lhs[3],
		lhs[2],
	}
}

// SwizzleZYWW returns a new vector with the components of this
// vector in the order of ZYWW.
func (lhs Vec4d) SwizzleZYWW() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[1],
		lhs[3],
		lhs[3],
	}
}

// SwizzleZZXX returns a new vector with the components of this
// vector in the order of ZZXX.
func (lhs Vec4d) SwizzleZZXX() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZZXY returns a new vector with the components of this
// vector in the order of ZZXY.
func (lhs Vec4d) SwizzleZZXY() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZZXZ returns a new vector with the components of this
// vector in the order of ZZXZ.
func (lhs Vec4d) SwizzleZZXZ() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZZXW returns a new vector with the components of this
// vector in the order of ZZXW.
func (lhs Vec4d) SwizzleZZXW() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[2],
		lhs[0],
		lhs[3],
	}
}

// SwizzleZZYX returns a new vector with the components of this
// vector in the order of ZZYX.
func (lhs Vec4d) SwizzleZZYX() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZZYY returns a new vector with the components of this
// vector in the order of ZZYY.
func (lhs Vec4d) SwizzleZZYY() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZZYZ returns a new vector with the components of this
// vector in the order of ZZYZ.
func (lhs Vec4d) SwizzleZZYZ() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZZYW returns a new vector with the components of this
// vector in the order of ZZYW.
func (lhs Vec4d) SwizzleZZYW() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[2],
		lhs[1],
		lhs[3],
	}
}

// SwizzleZZZX returns a new vector with the components of this
// vector in the order of ZZZX.
func (lhs Vec4d) SwizzleZZZX() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZZZY returns a new vector with the components of this
// vector in the order of ZZZY.
func (lhs Vec4d) SwizzleZZZY() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZZZZ returns a new vector with the components of this
// vector in the order of ZZZZ.
func (lhs Vec4d) SwizzleZZZZ() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZZZW returns a new vector with the components of this
// vector in the order of ZZZW.
func (lhs Vec4d) SwizzleZZZW() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[2],
		lhs[2],
		lhs[3],
	}
}

// SwizzleZZWX returns a new vector with the components of this
// vector in the order of ZZWX.
func (lhs Vec4d) SwizzleZZWX() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[2],
		lhs[3],
		lhs[0],
	}
}

// SwizzleZZWY returns a new vector with the components of this
// vector in the order of ZZWY.
func (lhs Vec4d) SwizzleZZWY() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[2],
		lhs[3],
		lhs[1],
	}
}

// SwizzleZZWZ returns a new vector with the components of this
// vector in the order of ZZWZ.
func (lhs Vec4d) SwizzleZZWZ() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[2],
		lhs[3],
		lhs[2],
	}
}

// SwizzleZZWW returns a new vector with the components of this
// vector in the order of ZZWW.
func (lhs Vec4d) SwizzleZZWW() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[2],
		lhs[3],
		lhs[3],
	}
}

// SwizzleZWXX returns a new vector with the components of this
// vector in the order of ZWXX.
func (lhs Vec4d) SwizzleZWXX() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[3],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZWXY returns a new vector with the components of this
// vector in the order of ZWXY.
func (lhs Vec4d) SwizzleZWXY() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[3],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZWXZ returns a new vector with the components of this
// vector in the order of ZWXZ.
func (lhs Vec4d) SwizzleZWXZ() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[3],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZWXW returns a new vector with the components of this
// vector in the order of ZWXW.
func (lhs Vec4d) SwizzleZWXW() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[3],
		lhs[0],
		lhs[3],
	}
}

// SwizzleZWYX returns a new vector with the components of this
// vector in the order of ZWYX.
func (lhs Vec4d) SwizzleZWYX() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[3],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZWYY returns a new vector with the components of this
// vector in the order of ZWYY.
func (lhs Vec4d) SwizzleZWYY() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[3],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZWYZ returns a new vector with the components of this
// vector in the order of ZWYZ.
func (lhs Vec4d) SwizzleZWYZ() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[3],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZWYW returns a new vector with the components of this
// vector in the order of ZWYW.
func (lhs Vec4d) SwizzleZWYW() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[3],
		lhs[1],
		lhs[3],
	}
}

// SwizzleZWZX returns a new vector with the components of this
// vector in the order of ZWZX.
func (lhs Vec4d) SwizzleZWZX() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[3],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZWZY returns a new vector with the components of this
// vector in the order of ZWZY.
func (lhs Vec4d) SwizzleZWZY() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[3],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZWZZ returns a new vector with the components of this
// vector in the order of ZWZZ.
func (lhs Vec4d) SwizzleZWZZ() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[3],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZWZW returns a new vector with the components of this
// vector in the order of ZWZW.
func (lhs Vec4d) SwizzleZWZW() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[3],
		lhs[2],
		lhs[3],
	}
}

// SwizzleZWWX returns a new vector with the components of this
// vector in the order of ZWWX.
func (lhs Vec4d) SwizzleZWWX() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[3],
		lhs[3],
		lhs[0],
	}
}

// SwizzleZWWY returns a new vector with the components of this
// vector in the order of ZWWY.
func (lhs Vec4d) SwizzleZWWY() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[3],
		lhs[3],
		lhs[1],
	}
}

// SwizzleZWWZ returns a new vector with the components of this
// vector in the order of ZWWZ.
func (lhs Vec4d) SwizzleZWWZ() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[3],
		lhs[3],
		lhs[2],
	}
}

// SwizzleZWWW returns a new vector with the components of this
// vector in the order of ZWWW.
func (lhs Vec4d) SwizzleZWWW() Vec4d {
	return Vec4d{
		lhs[2],
		lhs[3],
		lhs[3],
		lhs[3],
	}
}

// SwizzleWXXX returns a new vector with the components of this
// vector in the order of WXXX.
func (lhs Vec4d) SwizzleWXXX() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleWXXY returns a new vector with the components of this
// vector in the order of WXXY.
func (lhs Vec4d) SwizzleWXXY() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleWXXZ returns a new vector with the components of this
// vector in the order of WXXZ.
func (lhs Vec4d) SwizzleWXXZ() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleWXXW returns a new vector with the components of this
// vector in the order of WXXW.
func (lhs Vec4d) SwizzleWXXW() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[0],
		lhs[0],
		lhs[3],
	}
}

// SwizzleWXYX returns a new vector with the components of this
// vector in the order of WXYX.
func (lhs Vec4d) SwizzleWXYX() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleWXYY returns a new vector with the components of this
// vector in the order of WXYY.
func (lhs Vec4d) SwizzleWXYY() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleWXYZ returns a new vector with the components of this
// vector in the order of WXYZ.
func (lhs Vec4d) SwizzleWXYZ() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleWXYW returns a new vector with the components of this
// vector in the order of WXYW.
func (lhs Vec4d) SwizzleWXYW() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[0],
		lhs[1],
		lhs[3],
	}
}

// SwizzleWXZX returns a new vector with the components of this
// vector in the order of WXZX.
func (lhs Vec4d) SwizzleWXZX() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleWXZY returns a new vector with the components of this
// vector in the order of WXZY.
func (lhs Vec4d) SwizzleWXZY() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleWXZZ returns a new vector with the components of this
// vector in the order of WXZZ.
func (lhs Vec4d) SwizzleWXZZ() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleWXZW returns a new vector with the components of this
// vector in the order of WXZW.
func (lhs Vec4d) SwizzleWXZW() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[0],
		lhs[2],
		lhs[3],
	}
}

// SwizzleWXWX returns a new vector with the components of this
// vector in the order of WXWX.
func (lhs Vec4d) SwizzleWXWX() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[0],
		lhs[3],
		lhs[0],
	}
}

// SwizzleWXWY returns a new vector with the components of this
// vector in the order of WXWY.
func (lhs Vec4d) SwizzleWXWY() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[0],
		lhs[3],
		lhs[1],
	}
}

// SwizzleWXWZ returns a new vector with the components of this
// vector in the order of WXWZ.
func (lhs Vec4d) SwizzleWXWZ() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[0],
		lhs[3],
		lhs[2],
	}
}

// SwizzleWXWW returns a new vector with the components of this
// vector in the order of WXWW.
func (lhs Vec4d) SwizzleWXWW() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[0],
		lhs[3],
		lhs[3],
	}
}

// SwizzleWYXX returns a new vector with the components of this
// vector in the order of WYXX.
func (lhs Vec4d) SwizzleWYXX() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleWYXY returns a new vector with the components of this
// vector in the order of WYXY.
func (lhs Vec4d) SwizzleWYXY() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleWYXZ returns a new vector with the components of this
// vector in the order of WYXZ.
func (lhs Vec4d) SwizzleWYXZ() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleWYXW returns a new vector with the components of this
// vector in the order of WYXW.
func (lhs Vec4d) SwizzleWYXW() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[1],
		lhs[0],
		lhs[3],
	}
}

// SwizzleWYYX returns a new vector with the components of this
// vector in the order of WYYX.
func (lhs Vec4d) SwizzleWYYX() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleWYYY returns a new vector with the components of this
// vector in the order of WYYY.
func (lhs Vec4d) SwizzleWYYY() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleWYYZ returns a new vector with the components of this
// vector in the order of WYYZ.
func (lhs Vec4d) SwizzleWYYZ() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleWYYW returns a new vector with the components of this
// vector in the order of WYYW.
func (lhs Vec4d) SwizzleWYYW() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[1],
		lhs[1],
		lhs[3],
	}
}

// SwizzleWYZX returns a new vector with the components of this
// vector in the order of WYZX.
func (lhs Vec4d) SwizzleWYZX() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleWYZY returns a new vector with the components of this
// vector in the order of WYZY.
func (lhs Vec4d) SwizzleWYZY() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleWYZZ returns a new vector with the components of this
// vector in the order of WYZZ.
func (lhs Vec4d) SwizzleWYZZ() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleWYZW returns a new vector with the components of this
// vector in the order of WYZW.
func (lhs Vec4d) SwizzleWYZW() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[1],
		lhs[2],
		lhs[3],
	}
}

// SwizzleWYWX returns a new vector with the components of this
// vector in the order of WYWX.
func (lhs Vec4d) SwizzleWYWX() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[1],
		lhs[3],
		lhs[0],
	}
}

// SwizzleWYWY returns a new vector with the components of this
// vector in the order of WYWY.
func (lhs Vec4d) SwizzleWYWY() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[1],
		lhs[3],
		lhs[1],
	}
}

// SwizzleWYWZ returns a new vector with the components of this
// vector in the order of WYWZ.
func (lhs Vec4d) SwizzleWYWZ() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[1],
		lhs[3],
		lhs[2],
	}
}

// SwizzleWYWW returns a new vector with the components of this
// vector in the order of WYWW.
func (lhs Vec4d) SwizzleWYWW() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[1],
		lhs[3],
		lhs[3],
	}
}

// SwizzleWZXX returns a new vector with the components of this
// vector in the order of WZXX.
func (lhs Vec4d) SwizzleWZXX() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleWZXY returns a new vector with the components of this
// vector in the order of WZXY.
func (lhs Vec4d) SwizzleWZXY() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleWZXZ returns a new vector with the components of this
// vector in the order of WZXZ.
func (lhs Vec4d) SwizzleWZXZ() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleWZXW returns a new vector with the components of this
// vector in the order of WZXW.
func (lhs Vec4d) SwizzleWZXW() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[2],
		lhs[0],
		lhs[3],
	}
}

// SwizzleWZYX returns a new vector with the components of this
// vector in the order of WZYX.
func (lhs Vec4d) SwizzleWZYX() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleWZYY returns a new vector with the components of this
// vector in the order of WZYY.
func (lhs Vec4d) SwizzleWZYY() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleWZYZ returns a new vector with the components of this
// vector in the order of WZYZ.
func (lhs Vec4d) SwizzleWZYZ() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleWZYW returns a new vector with the components of this
// vector in the order of WZYW.
func (lhs Vec4d) SwizzleWZYW() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[2],
		lhs[1],
		lhs[3],
	}
}

// SwizzleWZZX returns a new vector with the components of this
// vector in the order of WZZX.
func (lhs Vec4d) SwizzleWZZX() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleWZZY returns a new vector with the components of this
// vector in the order of WZZY.
func (lhs Vec4d) SwizzleWZZY() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleWZZZ returns a new vector with the components of this
// vector in the order of WZZZ.
func (lhs Vec4d) SwizzleWZZZ() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

// SwizzleWZZW returns a new vector with the components of this
// vector in the order of WZZW.
func (lhs Vec4d) SwizzleWZZW() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[2],
		lhs[2],
		lhs[3],
	}
}

// SwizzleWZWX returns a new vector with the components of this
// vector in the order of WZWX.
func (lhs Vec4d) SwizzleWZWX() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[2],
		lhs[3],
		lhs[0],
	}
}

// SwizzleWZWY returns a new vector with the components of this
// vector in the order of WZWY.
func (lhs Vec4d) SwizzleWZWY() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[2],
		lhs[3],
		lhs[1],
	}
}

// SwizzleWZWZ returns a new vector with the components of this
// vector in the order of WZWZ.
func (lhs Vec4d) SwizzleWZWZ() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[2],
		lhs[3],
		lhs[2],
	}
}

// SwizzleWZWW returns a new vector with the components of this
// vector in the order of WZWW.
func (lhs Vec4d) SwizzleWZWW() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[2],
		lhs[3],
		lhs[3],
	}
}

// SwizzleWWXX returns a new vector with the components of this
// vector in the order of WWXX.
func (lhs Vec4d) SwizzleWWXX() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[3],
		lhs[0],
		lhs[0],
	}
}

// SwizzleWWXY returns a new vector with the components of this
// vector in the order of WWXY.
func (lhs Vec4d) SwizzleWWXY() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[3],
		lhs[0],
		lhs[1],
	}
}

// SwizzleWWXZ returns a new vector with the components of this
// vector in the order of WWXZ.
func (lhs Vec4d) SwizzleWWXZ() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[3],
		lhs[0],
		lhs[2],
	}
}

// SwizzleWWXW returns a new vector with the components of this
// vector in the order of WWXW.
func (lhs Vec4d) SwizzleWWXW() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[3],
		lhs[0],
		lhs[3],
	}
}

// SwizzleWWYX returns a new vector with the components of this
// vector in the order of WWYX.
func (lhs Vec4d) SwizzleWWYX() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[3],
		lhs[1],
		lhs[0],
	}
}

// SwizzleWWYY returns a new vector with the components of this
// vector in the order of WWYY.
func (lhs Vec4d) SwizzleWWYY() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[3],
		lhs[1],
		lhs[1],
	}
}

// SwizzleWWYZ returns a new vector with the components of this
// vector in the order of WWYZ.
func (lhs Vec4d) SwizzleWWYZ() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[3],
		lhs[1],
		lhs[2],
	}
}

// SwizzleWWYW returns a new vector with the components of this
// vector in the order of WWYW.
func (lhs Vec4d) SwizzleWWYW() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[3],
		lhs[1],
		lhs[3],
	}
}

// SwizzleWWZX returns a new vector with the components of this
// vector in the order of WWZX.
func (lhs Vec4d) SwizzleWWZX() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[3],
		lhs[2],
		lhs[0],
	}
}

// SwizzleWWZY returns a new vector with the components of this
// vector in the order of WWZY.
func (lhs Vec4d) SwizzleWWZY() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[3],
		lhs[2],
		lhs[1],
	}
}

// SwizzleWWZZ returns a new vector with the components of this
// vector in the order of WWZZ.
func (lhs Vec4d) SwizzleWWZZ() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[3],
		lhs[2],
		lhs[2],
	}
}

// SwizzleWWZW returns a new vector with the components of this
// vector in the order of WWZW.
func (lhs Vec4d) SwizzleWWZW() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[3],
		lhs[2],
		lhs[3],
	}
}

// SwizzleWWWX returns a new vector with the components of this
// vector in the order of WWWX.
func (lhs Vec4d) SwizzleWWWX() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[3],
		lhs[3],
		lhs[0],
	}
}

// SwizzleWWWY returns a new vector with the components of this
// vector in the order of WWWY.
func (lhs Vec4d) SwizzleWWWY() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[3],
		lhs[3],
		lhs[1],
	}
}

// SwizzleWWWZ returns a new vector with the components of this
// vector in the order of WWWZ.
func (lhs Vec4d) SwizzleWWWZ() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[3],
		lhs[3],
		lhs[2],
	}
}

// SwizzleWWWW returns a new vector with the components of this
// vector in the order of WWWW.
func (lhs Vec4d) SwizzleWWWW() Vec4d {
	return Vec4d{
		lhs[3],
		lhs[3],
		lhs[3],
		lhs[3],
	}
}

func (lhs Vec4d) XY() (x, y float64) {
	x = lhs[0]
	y = lhs[1]
	return
}

func (lhs Vec4d) XYZ() (x, y, z float64) {
	x = lhs[0]
	y = lhs[1]
	z = lhs[2]
	return
}

func (lhs Vec4d) XYZW() (x, y, z, w float64) {
	x = lhs[0]
	y = lhs[1]
	z = lhs[2]
	w = lhs[3]
	return
}

func (lhs Vec4d) ToVec4f() Vec4f {
	return Vec4f{
		float32(lhs[0]),
		float32(lhs[1]),
		float32(lhs[2]),
		float32(lhs[3]),
	}
}

func (lhs Vec4d) ToWGPU() [4]float32 {
	return [4]float32{
		float32(lhs[0]),
		float32(lhs[1]),
		float32(lhs[2]),
		float32(lhs[3]),
	}
}

func (lhs Vec4d) String() string {
	return fmt.Sprintf(
		"vec4(%v, %v, %v, %v)",
		lhs[0],
		lhs[1],
		lhs[2],
		lhs[3],
	)
}
