// Code generated by generate.go: DO NOT EDIT.

package glm

import "unsafe"

type _ = unsafe.Pointer

// Mat2uh is a 2x2 matrix.
// The default value is filled with all zero values.
type Mat2uh [2][2]uint16

func IdentityMat2uh() Mat2uh {
	var m Mat2uh
	m[0][0] = 1
	m[1][1] = 1
	return m
}

func (m Mat2uh) Mul(o Mat2uh) Mat2uh {
	mv := &m
	ov := &o

	return Mat2uh{
		{
			mv[0][0]*ov[0][0] + mv[1][0]*ov[0][1],
			mv[0][1]*ov[0][0] + mv[1][1]*ov[0][1],
		},
		{
			mv[0][0]*ov[1][0] + mv[1][0]*ov[1][1],
			mv[0][1]*ov[1][0] + mv[1][1]*ov[1][1],
		},
	}
}

func (m Mat2uh) Transpose() Mat2uh {
	mv := &m

	return Mat2uh{
		{
			mv[0][0],
			mv[1][0],
		},
		{
			mv[0][1],
			mv[1][1],
		},
	}
}

// Column returns a reference to the given column
func (m *Mat2uh) Column(idx int) Vec2uh {
	return *(*Vec2uh)(&m[idx])
}
