// Code generated by generate.go: DO NOT EDIT.

package glm

import "unsafe"

type _ = unsafe.Pointer

// Mat4d is a 4x4 matrix.
// The default value is filled with all zero values.
type Mat4d [4][4]float64

func IdentityMat4d() Mat4d {
	var m Mat4d
	m[0][0] = 1
	m[1][1] = 1
	m[2][2] = 1
	m[3][3] = 1
	return m
}

func (m Mat4d) Mul(o Mat4d) Mat4d {
	mv := &m
	ov := &o

	return Mat4d{
		{
			mv[0][0]*ov[0][0] + mv[1][0]*ov[0][1] + mv[2][0]*ov[0][2] + mv[3][0]*ov[0][3],
			mv[0][1]*ov[0][0] + mv[1][1]*ov[0][1] + mv[2][1]*ov[0][2] + mv[3][1]*ov[0][3],
			mv[0][2]*ov[0][0] + mv[1][2]*ov[0][1] + mv[2][2]*ov[0][2] + mv[3][2]*ov[0][3],
			mv[0][3]*ov[0][0] + mv[1][3]*ov[0][1] + mv[2][3]*ov[0][2] + mv[3][3]*ov[0][3],
		},
		{
			mv[0][0]*ov[1][0] + mv[1][0]*ov[1][1] + mv[2][0]*ov[1][2] + mv[3][0]*ov[1][3],
			mv[0][1]*ov[1][0] + mv[1][1]*ov[1][1] + mv[2][1]*ov[1][2] + mv[3][1]*ov[1][3],
			mv[0][2]*ov[1][0] + mv[1][2]*ov[1][1] + mv[2][2]*ov[1][2] + mv[3][2]*ov[1][3],
			mv[0][3]*ov[1][0] + mv[1][3]*ov[1][1] + mv[2][3]*ov[1][2] + mv[3][3]*ov[1][3],
		},
		{
			mv[0][0]*ov[2][0] + mv[1][0]*ov[2][1] + mv[2][0]*ov[2][2] + mv[3][0]*ov[2][3],
			mv[0][1]*ov[2][0] + mv[1][1]*ov[2][1] + mv[2][1]*ov[2][2] + mv[3][1]*ov[2][3],
			mv[0][2]*ov[2][0] + mv[1][2]*ov[2][1] + mv[2][2]*ov[2][2] + mv[3][2]*ov[2][3],
			mv[0][3]*ov[2][0] + mv[1][3]*ov[2][1] + mv[2][3]*ov[2][2] + mv[3][3]*ov[2][3],
		},
		{
			mv[0][0]*ov[3][0] + mv[1][0]*ov[3][1] + mv[2][0]*ov[3][2] + mv[3][0]*ov[3][3],
			mv[0][1]*ov[3][0] + mv[1][1]*ov[3][1] + mv[2][1]*ov[3][2] + mv[3][1]*ov[3][3],
			mv[0][2]*ov[3][0] + mv[1][2]*ov[3][1] + mv[2][2]*ov[3][2] + mv[3][2]*ov[3][3],
			mv[0][3]*ov[3][0] + mv[1][3]*ov[3][1] + mv[2][3]*ov[3][2] + mv[3][3]*ov[3][3],
		},
	}
}

func (m Mat4d) Transpose() Mat4d {
	mv := &m

	return Mat4d{
		{
			mv[0][0],
			mv[1][0],
			mv[2][0],
			mv[3][0],
		},
		{
			mv[0][1],
			mv[1][1],
			mv[2][1],
			mv[3][1],
		},
		{
			mv[0][2],
			mv[1][2],
			mv[2][2],
			mv[3][2],
		},
		{
			mv[0][3],
			mv[1][3],
			mv[2][3],
			mv[3][3],
		},
	}
}

// Column returns a reference to the given column
func (m *Mat4d) Column(idx int) Vec4d {
	return *(*Vec4d)(&m[idx])
}

func TranslationMat4d(x, y, z float64) Mat4d {
	return Mat4d{
		{1, 0, 0, 0},
		{0, 1, 0, 0},
		{0, 0, 1, 0},
		{x, y, z, 1},
	}
}

func ScaleMat4d(x, y, z float64) Mat4d {
	var res Mat4d
	res[0][0] = x
	res[1][1] = y
	res[2][2] = z
	res[3][3] = 1
	return res
}

func (m Mat4d) Translate(x, y, z float64) Mat4d {
	return m.Mul(TranslationMat4d(x, y, z))
}

func (m Mat4d) Scale(x, y, z float64) Mat4d {
	return m.Mul(ScaleMat4d(x, y, z))
}

func RotationZMat4d(angle Rad) Mat4d {
	fs, fc := fastSincos(angle)
	s := float64(fs)
	c := float64(fc)

	return Mat4d{
		{c, s, 0, 0},
		{-s, c, 0, 0},
		{0, 0, 1, 0},
		{0, 0, 0, 1},
	}
}

func RotationXMat4d(angle Rad) Mat4d {
	fs, fc := fastSincos(angle)
	s := float64(fs)
	c := float64(fc)

	return Mat4d{
		{1, 0, 0, 0},
		{0, c, s, 0},
		{0, -s, c, 0},
		{0, 0, 0, 1},
	}
}

func RotationYMat4d(angle Rad) Mat4d {
	fs, fc := fastSincos(angle)
	s := float64(fs)
	c := float64(fc)

	return Mat4d{
		{c, 0, s, 0},
		{0, 1, 0, 0},
		{-s, 0, c, 0},
		{0, 0, 0, 1},
	}
}

func (m Mat4d) RotateX(angle Rad) Mat4d {
	return m.Mul(RotationXMat4d(angle))
}

func (m Mat4d) RotateY(angle Rad) Mat4d {
	return m.Mul(RotationYMat4d(angle))
}

func (m Mat4d) RotateZ(angle Rad) Mat4d {
	return m.Mul(RotationZMat4d(angle))
}

func (m Mat4d) Transform(vec Vec4d) Vec4d {
	return Vec4d{
		(m[0][0])*vec[0] + (m[1][0])*vec[1] + (m[2][0])*vec[2] + (m[3][0])*vec[3],
		(m[0][1])*vec[0] + (m[1][1])*vec[1] + (m[2][1])*vec[2] + (m[3][1])*vec[3],
		(m[0][2])*vec[0] + (m[1][2])*vec[1] + (m[2][2])*vec[2] + (m[3][2])*vec[3],
		(m[0][3])*vec[0] + (m[1][3])*vec[1] + (m[2][3])*vec[2] + (m[3][3])*vec[3],
	}
}

func (m Mat4d) Transform3(vec Vec3d) Vec3d {
	return Vec3d{
		(m[0][0])*vec[0] + (m[1][0])*vec[1] + (m[2][0] * vec[2]) + m[3][0],
		(m[0][1])*vec[0] + (m[1][1])*vec[1] + (m[2][1] * vec[2]) + m[3][1],
		(m[0][2])*vec[0] + (m[1][2])*vec[1] + (m[2][2] * vec[2]) + m[3][2],
	}
}

func (m Mat4d) Transform2(vec Vec2d) Vec2d {
	return Vec2d{
		(m[0][0])*vec[0] + (m[1][0])*vec[1] + m[3][0],
		(m[0][1])*vec[0] + (m[1][1])*vec[1] + m[3][1],
	}
}

func (m Mat4d) TranslateZ() float64 {
	return m[3][2]
}
