// Code generated by generate.go: DO NOT EDIT.

package glm

import "fmt"
import "math"

// Vec2uh is a vector of dimension 2.
type Vec2uh [2]uint16

func (lhs Vec2uh) Dot(rhs Vec2uh) uint16 {
	return lhs[0]*rhs[0] + lhs[1]*rhs[1]
}

func (lhs Vec2uh) LengthSqr() uint16 {
	return lhs.Dot(lhs)
}

func (lhs Vec2uh) Length() uint16 {
	return uint16(math.Sqrt(float64(lhs.Dot(lhs))))
}

func (lhs Vec2uh) Normalize() Vec2uh {
	return lhs.Scale(1.0 / lhs.Length())
}

func (lhs Vec2uh) Scale(s uint16) Vec2uh {
	return Vec2uh{
		lhs[0] * s,
		lhs[1] * s,
	}
}

func (lhs Vec2uh) Reciprocal() Vec2uh {
	return Vec2uh{
		1.0 / lhs[0],
		1.0 / lhs[1],
	}
}

func (lhs Vec2uh) Add(rhs Vec2uh) Vec2uh {
	return Vec2uh{
		lhs[0] + rhs[0],
		lhs[1] + rhs[1],
	}
}

func (lhs Vec2uh) Sub(rhs Vec2uh) Vec2uh {
	return Vec2uh{
		lhs[0] - rhs[0],
		lhs[1] - rhs[1],
	}
}

func (lhs Vec2uh) Mul(rhs Vec2uh) Vec2uh {
	return Vec2uh{
		lhs[0] * rhs[0],
		lhs[1] * rhs[1],
	}
}

func (lhs Vec2uh) Div(rhs Vec2uh) Vec2uh {
	return Vec2uh{
		lhs[0] / rhs[0],
		lhs[1] / rhs[1],
	}
}

func (lhs Vec2uh) Min(rhs Vec2uh) Vec2uh {
	return Vec2uh{
		min(lhs[0], rhs[0]),
		min(lhs[1], rhs[1]),
	}
}

func (lhs Vec2uh) Max(rhs Vec2uh) Vec2uh {
	return Vec2uh{
		max(lhs[0], rhs[0]),
		max(lhs[1], rhs[1]),
	}
}

func (lhs Vec2uh) Extend(z uint16) Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[1],
		z,
	}
}

// SwizzleXX returns a new vector with the components of this
// vector in the order of XX.
func (lhs Vec2uh) SwizzleXX() Vec2uh {
	return Vec2uh{
		lhs[0],
		lhs[0],
	}
}

// SwizzleXY returns a new vector with the components of this
// vector in the order of XY.
func (lhs Vec2uh) SwizzleXY() Vec2uh {
	return Vec2uh{
		lhs[0],
		lhs[1],
	}
}

// SwizzleYX returns a new vector with the components of this
// vector in the order of YX.
func (lhs Vec2uh) SwizzleYX() Vec2uh {
	return Vec2uh{
		lhs[1],
		lhs[0],
	}
}

// SwizzleYY returns a new vector with the components of this
// vector in the order of YY.
func (lhs Vec2uh) SwizzleYY() Vec2uh {
	return Vec2uh{
		lhs[1],
		lhs[1],
	}
}

func (lhs Vec2uh) XY() (x, y uint16) {
	x = lhs[0]
	y = lhs[1]
	return
}

func (lhs Vec2uh) ToVec2f() Vec2f {
	return Vec2f{
		float32(lhs[0]),
		float32(lhs[1]),
	}
}

func (lhs Vec2uh) ToWGPU() [2]float32 {
	return [2]float32{
		float32(lhs[0]),
		float32(lhs[1]),
	}
}

func (lhs Vec2uh) String() string {
	return fmt.Sprintf(
		"vec2(%v, %v)",
		lhs[0],
		lhs[1],
	)
}
