// Code generated by generate.go: DO NOT EDIT.

package glm

import "fmt"
import "math"

// Vec3d is a vector of dimension 3.
type Vec3d [3]float64

func (lhs Vec3d) Dot(rhs Vec3d) float64 {
	return lhs[0]*rhs[0] + lhs[1]*rhs[1] + lhs[2]*rhs[2]
}

func (lhs Vec3d) LengthSqr() float64 {
	return lhs.Dot(lhs)
}

func (lhs Vec3d) Length() float64 {
	return float64(math.Sqrt(float64(lhs.Dot(lhs))))
}

func (lhs Vec3d) Normalize() Vec3d {
	return lhs.Scale(1.0 / lhs.Length())
}

func (lhs Vec3d) Scale(s float64) Vec3d {
	return Vec3d{
		lhs[0] * s,
		lhs[1] * s,
		lhs[2] * s,
	}
}

func (lhs Vec3d) Reciprocal() Vec3d {
	return Vec3d{
		1.0 / lhs[0],
		1.0 / lhs[1],
		1.0 / lhs[2],
	}
}

func (lhs Vec3d) Add(rhs Vec3d) Vec3d {
	return Vec3d{
		lhs[0] + rhs[0],
		lhs[1] + rhs[1],
		lhs[2] + rhs[2],
	}
}

func (lhs Vec3d) Sub(rhs Vec3d) Vec3d {
	return Vec3d{
		lhs[0] - rhs[0],
		lhs[1] - rhs[1],
		lhs[2] - rhs[2],
	}
}

func (lhs Vec3d) Mul(rhs Vec3d) Vec3d {
	return Vec3d{
		lhs[0] * rhs[0],
		lhs[1] * rhs[1],
		lhs[2] * rhs[2],
	}
}

func (lhs Vec3d) Div(rhs Vec3d) Vec3d {
	return Vec3d{
		lhs[0] / rhs[0],
		lhs[1] / rhs[1],
		lhs[2] / rhs[2],
	}
}

func (lhs Vec3d) Min(rhs Vec3d) Vec3d {
	return Vec3d{
		min(lhs[0], rhs[0]),
		min(lhs[1], rhs[1]),
		min(lhs[2], rhs[2]),
	}
}

func (lhs Vec3d) Max(rhs Vec3d) Vec3d {
	return Vec3d{
		max(lhs[0], rhs[0]),
		max(lhs[1], rhs[1]),
		max(lhs[2], rhs[2]),
	}
}

func (lhs Vec3d) Extend(w float64) Vec4d {
	return Vec4d{
		lhs[0],
		lhs[1],
		lhs[2],
		w,
	}
}

func (lhs Vec3d) Truncate() Vec2d {
	return Vec2d{
		lhs[0],
		lhs[1],
	}
}

// SwizzleXX returns a new vector with the components of this
// vector in the order of XX.
func (lhs Vec3d) SwizzleXX() Vec2d {
	return Vec2d{
		lhs[0],
		lhs[0],
	}
}

// SwizzleXY returns a new vector with the components of this
// vector in the order of XY.
func (lhs Vec3d) SwizzleXY() Vec2d {
	return Vec2d{
		lhs[0],
		lhs[1],
	}
}

// SwizzleXZ returns a new vector with the components of this
// vector in the order of XZ.
func (lhs Vec3d) SwizzleXZ() Vec2d {
	return Vec2d{
		lhs[0],
		lhs[2],
	}
}

// SwizzleYX returns a new vector with the components of this
// vector in the order of YX.
func (lhs Vec3d) SwizzleYX() Vec2d {
	return Vec2d{
		lhs[1],
		lhs[0],
	}
}

// SwizzleYY returns a new vector with the components of this
// vector in the order of YY.
func (lhs Vec3d) SwizzleYY() Vec2d {
	return Vec2d{
		lhs[1],
		lhs[1],
	}
}

// SwizzleYZ returns a new vector with the components of this
// vector in the order of YZ.
func (lhs Vec3d) SwizzleYZ() Vec2d {
	return Vec2d{
		lhs[1],
		lhs[2],
	}
}

// SwizzleZX returns a new vector with the components of this
// vector in the order of ZX.
func (lhs Vec3d) SwizzleZX() Vec2d {
	return Vec2d{
		lhs[2],
		lhs[0],
	}
}

// SwizzleZY returns a new vector with the components of this
// vector in the order of ZY.
func (lhs Vec3d) SwizzleZY() Vec2d {
	return Vec2d{
		lhs[2],
		lhs[1],
	}
}

// SwizzleZZ returns a new vector with the components of this
// vector in the order of ZZ.
func (lhs Vec3d) SwizzleZZ() Vec2d {
	return Vec2d{
		lhs[2],
		lhs[2],
	}
}

// SwizzleXXX returns a new vector with the components of this
// vector in the order of XXX.
func (lhs Vec3d) SwizzleXXX() Vec3d {
	return Vec3d{
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXXY returns a new vector with the components of this
// vector in the order of XXY.
func (lhs Vec3d) SwizzleXXY() Vec3d {
	return Vec3d{
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXXZ returns a new vector with the components of this
// vector in the order of XXZ.
func (lhs Vec3d) SwizzleXXZ() Vec3d {
	return Vec3d{
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXYX returns a new vector with the components of this
// vector in the order of XYX.
func (lhs Vec3d) SwizzleXYX() Vec3d {
	return Vec3d{
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXYY returns a new vector with the components of this
// vector in the order of XYY.
func (lhs Vec3d) SwizzleXYY() Vec3d {
	return Vec3d{
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXYZ returns a new vector with the components of this
// vector in the order of XYZ.
func (lhs Vec3d) SwizzleXYZ() Vec3d {
	return Vec3d{
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXZX returns a new vector with the components of this
// vector in the order of XZX.
func (lhs Vec3d) SwizzleXZX() Vec3d {
	return Vec3d{
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXZY returns a new vector with the components of this
// vector in the order of XZY.
func (lhs Vec3d) SwizzleXZY() Vec3d {
	return Vec3d{
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXZZ returns a new vector with the components of this
// vector in the order of XZZ.
func (lhs Vec3d) SwizzleXZZ() Vec3d {
	return Vec3d{
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYXX returns a new vector with the components of this
// vector in the order of YXX.
func (lhs Vec3d) SwizzleYXX() Vec3d {
	return Vec3d{
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYXY returns a new vector with the components of this
// vector in the order of YXY.
func (lhs Vec3d) SwizzleYXY() Vec3d {
	return Vec3d{
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYXZ returns a new vector with the components of this
// vector in the order of YXZ.
func (lhs Vec3d) SwizzleYXZ() Vec3d {
	return Vec3d{
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYYX returns a new vector with the components of this
// vector in the order of YYX.
func (lhs Vec3d) SwizzleYYX() Vec3d {
	return Vec3d{
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYYY returns a new vector with the components of this
// vector in the order of YYY.
func (lhs Vec3d) SwizzleYYY() Vec3d {
	return Vec3d{
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYYZ returns a new vector with the components of this
// vector in the order of YYZ.
func (lhs Vec3d) SwizzleYYZ() Vec3d {
	return Vec3d{
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYZX returns a new vector with the components of this
// vector in the order of YZX.
func (lhs Vec3d) SwizzleYZX() Vec3d {
	return Vec3d{
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYZY returns a new vector with the components of this
// vector in the order of YZY.
func (lhs Vec3d) SwizzleYZY() Vec3d {
	return Vec3d{
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYZZ returns a new vector with the components of this
// vector in the order of YZZ.
func (lhs Vec3d) SwizzleYZZ() Vec3d {
	return Vec3d{
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZXX returns a new vector with the components of this
// vector in the order of ZXX.
func (lhs Vec3d) SwizzleZXX() Vec3d {
	return Vec3d{
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZXY returns a new vector with the components of this
// vector in the order of ZXY.
func (lhs Vec3d) SwizzleZXY() Vec3d {
	return Vec3d{
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZXZ returns a new vector with the components of this
// vector in the order of ZXZ.
func (lhs Vec3d) SwizzleZXZ() Vec3d {
	return Vec3d{
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZYX returns a new vector with the components of this
// vector in the order of ZYX.
func (lhs Vec3d) SwizzleZYX() Vec3d {
	return Vec3d{
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZYY returns a new vector with the components of this
// vector in the order of ZYY.
func (lhs Vec3d) SwizzleZYY() Vec3d {
	return Vec3d{
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZYZ returns a new vector with the components of this
// vector in the order of ZYZ.
func (lhs Vec3d) SwizzleZYZ() Vec3d {
	return Vec3d{
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZZX returns a new vector with the components of this
// vector in the order of ZZX.
func (lhs Vec3d) SwizzleZZX() Vec3d {
	return Vec3d{
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZZY returns a new vector with the components of this
// vector in the order of ZZY.
func (lhs Vec3d) SwizzleZZY() Vec3d {
	return Vec3d{
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZZZ returns a new vector with the components of this
// vector in the order of ZZZ.
func (lhs Vec3d) SwizzleZZZ() Vec3d {
	return Vec3d{
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

func (lhs Vec3d) XY() (x, y float64) {
	x = lhs[0]
	y = lhs[1]
	return
}

func (lhs Vec3d) XYZ() (x, y, z float64) {
	x = lhs[0]
	y = lhs[1]
	z = lhs[2]
	return
}

func (lhs Vec3d) ToVec3f() Vec3f {
	return Vec3f{
		float32(lhs[0]),
		float32(lhs[1]),
		float32(lhs[2]),
	}
}

func (lhs Vec3d) ToWGPU() [4]float32 {
	return [4]float32{
		float32(lhs[0]),
		float32(lhs[1]),
		float32(lhs[2]),
	}
}

func (lhs Vec3d) String() string {
	return fmt.Sprintf(
		"vec3(%v, %v, %v)",
		lhs[0],
		lhs[1],
		lhs[2],
	)
}
