// Code generated by generate.go: DO NOT EDIT.

package glm

import (
	"fmt"
)

type Rectd struct {
	Min Vec2d
	Max Vec2d
}

func RectdFromSize(pos Vec2d, size Vec2d) Rectd {
	return RectdFromPoints(pos, pos.Add(size))
}

func RectdFromXYWH(x, y, w, h float64) Rectd {
	pos := Vec2d{x, y}
	size := Vec2d{w, h}
	return RectdFromSize(pos, size)
}

func RectdFromPoints(a, b Vec2d) Rectd {
	return Rectd{
		Min: Vec2d{
			min(a[0], b[0]),
			min(a[1], b[1]),
		},
		Max: Vec2d{
			max(a[0], b[0]),
			max(a[1], b[1]),
		},
	}
}

func (r Rectd) Extend(point Vec2d) Rectd {
	minX := min(r.Min[0], point[0])
	minY := min(r.Min[1], point[1])

	maxX := max(r.Max[0], point[0])
	maxY := max(r.Max[1], point[1])

	return Rectd{
		Min: Vec2d{minX, minY},
		Max: Vec2d{maxX, maxY},
	}
}

func (r Rectd) Union(other Rectd) Rectd {
	return r.Extend(other.Min).Extend(other.Max)
}

func (r Rectd) Contains(other Rectd) bool {
	return r.Min[0] <= other.Min[0] && r.Min[1] <= other.Min[1] &&
		r.Max[0] >= other.Max[0] && r.Max[1] >= other.Max[1]
}

func (r Rectd) Center() Vec2d {
	return r.Min.Add(r.Max).Div(Vec2d{2, 2})
}

func (r Rectd) Offset() Vec2d {
	return r.Min
}

func (r Rectd) Size() Vec2d {
	return r.Max.Sub(r.Min)
}

func (r Rectd) Width() float64 {
	return r.Max[0] - r.Min[0]
}

func (r Rectd) Height() float64 {
	return r.Max[1] - r.Min[1]
}

func (r Rectd) XYWH() (float64, float64, float64, float64) {
	x, y := r.Min.XY()
	w, h := r.Size().XY()
	return x, y, w, h
}

func (r Rectd) String() string {
	x, y, w, h := r.XYWH()
	return fmt.Sprintf("Rect(x=%v, y=%v, w=%v, h=%v)", x, y, w, h)
}
