// Code generated by generate.go: DO NOT EDIT.

package glm

import "fmt"
import "math"

// Vec4u is a vector of dimension 4.
type Vec4u [4]uint32

func (lhs Vec4u) Dot(rhs Vec4u) uint32 {
	return lhs[0]*rhs[0] + lhs[1]*rhs[1] + lhs[2]*rhs[2] + lhs[3]*rhs[3]
}

func (lhs Vec4u) LengthSqr() uint32 {
	return lhs.Dot(lhs)
}

func (lhs Vec4u) Length() uint32 {
	return uint32(math.Sqrt(float64(lhs.Dot(lhs))))
}

func (lhs Vec4u) Normalize() Vec4u {
	return lhs.Scale(1.0 / lhs.Length())
}

func (lhs Vec4u) Scale(s uint32) Vec4u {
	return Vec4u{
		lhs[0] * s,
		lhs[1] * s,
		lhs[2] * s,
		lhs[3] * s,
	}
}

func (lhs Vec4u) Reciprocal() Vec4u {
	return Vec4u{
		1.0 / lhs[0],
		1.0 / lhs[1],
		1.0 / lhs[2],
		1.0 / lhs[3],
	}
}

func (lhs Vec4u) Add(rhs Vec4u) Vec4u {
	return Vec4u{
		lhs[0] + rhs[0],
		lhs[1] + rhs[1],
		lhs[2] + rhs[2],
		lhs[3] + rhs[3],
	}
}

func (lhs Vec4u) Sub(rhs Vec4u) Vec4u {
	return Vec4u{
		lhs[0] - rhs[0],
		lhs[1] - rhs[1],
		lhs[2] - rhs[2],
		lhs[3] - rhs[3],
	}
}

func (lhs Vec4u) Mul(rhs Vec4u) Vec4u {
	return Vec4u{
		lhs[0] * rhs[0],
		lhs[1] * rhs[1],
		lhs[2] * rhs[2],
		lhs[3] * rhs[3],
	}
}

func (lhs Vec4u) Div(rhs Vec4u) Vec4u {
	return Vec4u{
		lhs[0] / rhs[0],
		lhs[1] / rhs[1],
		lhs[2] / rhs[2],
		lhs[3] / rhs[3],
	}
}

func (lhs Vec4u) Min(rhs Vec4u) Vec4u {
	return Vec4u{
		min(lhs[0], rhs[0]),
		min(lhs[1], rhs[1]),
		min(lhs[2], rhs[2]),
		min(lhs[3], rhs[3]),
	}
}

func (lhs Vec4u) Max(rhs Vec4u) Vec4u {
	return Vec4u{
		max(lhs[0], rhs[0]),
		max(lhs[1], rhs[1]),
		max(lhs[2], rhs[2]),
		max(lhs[3], rhs[3]),
	}
}

func (lhs Vec4u) Truncate() Vec3u {
	return Vec3u{
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXX returns a new vector with the components of this
// vector in the order of XX.
func (lhs Vec4u) SwizzleXX() Vec2u {
	return Vec2u{
		lhs[0],
		lhs[0],
	}
}

// SwizzleXY returns a new vector with the components of this
// vector in the order of XY.
func (lhs Vec4u) SwizzleXY() Vec2u {
	return Vec2u{
		lhs[0],
		lhs[1],
	}
}

// SwizzleXZ returns a new vector with the components of this
// vector in the order of XZ.
func (lhs Vec4u) SwizzleXZ() Vec2u {
	return Vec2u{
		lhs[0],
		lhs[2],
	}
}

// SwizzleXW returns a new vector with the components of this
// vector in the order of XW.
func (lhs Vec4u) SwizzleXW() Vec2u {
	return Vec2u{
		lhs[0],
		lhs[3],
	}
}

// SwizzleYX returns a new vector with the components of this
// vector in the order of YX.
func (lhs Vec4u) SwizzleYX() Vec2u {
	return Vec2u{
		lhs[1],
		lhs[0],
	}
}

// SwizzleYY returns a new vector with the components of this
// vector in the order of YY.
func (lhs Vec4u) SwizzleYY() Vec2u {
	return Vec2u{
		lhs[1],
		lhs[1],
	}
}

// SwizzleYZ returns a new vector with the components of this
// vector in the order of YZ.
func (lhs Vec4u) SwizzleYZ() Vec2u {
	return Vec2u{
		lhs[1],
		lhs[2],
	}
}

// SwizzleYW returns a new vector with the components of this
// vector in the order of YW.
func (lhs Vec4u) SwizzleYW() Vec2u {
	return Vec2u{
		lhs[1],
		lhs[3],
	}
}

// SwizzleZX returns a new vector with the components of this
// vector in the order of ZX.
func (lhs Vec4u) SwizzleZX() Vec2u {
	return Vec2u{
		lhs[2],
		lhs[0],
	}
}

// SwizzleZY returns a new vector with the components of this
// vector in the order of ZY.
func (lhs Vec4u) SwizzleZY() Vec2u {
	return Vec2u{
		lhs[2],
		lhs[1],
	}
}

// SwizzleZZ returns a new vector with the components of this
// vector in the order of ZZ.
func (lhs Vec4u) SwizzleZZ() Vec2u {
	return Vec2u{
		lhs[2],
		lhs[2],
	}
}

// SwizzleZW returns a new vector with the components of this
// vector in the order of ZW.
func (lhs Vec4u) SwizzleZW() Vec2u {
	return Vec2u{
		lhs[2],
		lhs[3],
	}
}

// SwizzleWX returns a new vector with the components of this
// vector in the order of WX.
func (lhs Vec4u) SwizzleWX() Vec2u {
	return Vec2u{
		lhs[3],
		lhs[0],
	}
}

// SwizzleWY returns a new vector with the components of this
// vector in the order of WY.
func (lhs Vec4u) SwizzleWY() Vec2u {
	return Vec2u{
		lhs[3],
		lhs[1],
	}
}

// SwizzleWZ returns a new vector with the components of this
// vector in the order of WZ.
func (lhs Vec4u) SwizzleWZ() Vec2u {
	return Vec2u{
		lhs[3],
		lhs[2],
	}
}

// SwizzleWW returns a new vector with the components of this
// vector in the order of WW.
func (lhs Vec4u) SwizzleWW() Vec2u {
	return Vec2u{
		lhs[3],
		lhs[3],
	}
}

// SwizzleXXX returns a new vector with the components of this
// vector in the order of XXX.
func (lhs Vec4u) SwizzleXXX() Vec3u {
	return Vec3u{
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXXY returns a new vector with the components of this
// vector in the order of XXY.
func (lhs Vec4u) SwizzleXXY() Vec3u {
	return Vec3u{
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXXZ returns a new vector with the components of this
// vector in the order of XXZ.
func (lhs Vec4u) SwizzleXXZ() Vec3u {
	return Vec3u{
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXXW returns a new vector with the components of this
// vector in the order of XXW.
func (lhs Vec4u) SwizzleXXW() Vec3u {
	return Vec3u{
		lhs[0],
		lhs[0],
		lhs[3],
	}
}

// SwizzleXYX returns a new vector with the components of this
// vector in the order of XYX.
func (lhs Vec4u) SwizzleXYX() Vec3u {
	return Vec3u{
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXYY returns a new vector with the components of this
// vector in the order of XYY.
func (lhs Vec4u) SwizzleXYY() Vec3u {
	return Vec3u{
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXYZ returns a new vector with the components of this
// vector in the order of XYZ.
func (lhs Vec4u) SwizzleXYZ() Vec3u {
	return Vec3u{
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXYW returns a new vector with the components of this
// vector in the order of XYW.
func (lhs Vec4u) SwizzleXYW() Vec3u {
	return Vec3u{
		lhs[0],
		lhs[1],
		lhs[3],
	}
}

// SwizzleXZX returns a new vector with the components of this
// vector in the order of XZX.
func (lhs Vec4u) SwizzleXZX() Vec3u {
	return Vec3u{
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXZY returns a new vector with the components of this
// vector in the order of XZY.
func (lhs Vec4u) SwizzleXZY() Vec3u {
	return Vec3u{
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXZZ returns a new vector with the components of this
// vector in the order of XZZ.
func (lhs Vec4u) SwizzleXZZ() Vec3u {
	return Vec3u{
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleXZW returns a new vector with the components of this
// vector in the order of XZW.
func (lhs Vec4u) SwizzleXZW() Vec3u {
	return Vec3u{
		lhs[0],
		lhs[2],
		lhs[3],
	}
}

// SwizzleXWX returns a new vector with the components of this
// vector in the order of XWX.
func (lhs Vec4u) SwizzleXWX() Vec3u {
	return Vec3u{
		lhs[0],
		lhs[3],
		lhs[0],
	}
}

// SwizzleXWY returns a new vector with the components of this
// vector in the order of XWY.
func (lhs Vec4u) SwizzleXWY() Vec3u {
	return Vec3u{
		lhs[0],
		lhs[3],
		lhs[1],
	}
}

// SwizzleXWZ returns a new vector with the components of this
// vector in the order of XWZ.
func (lhs Vec4u) SwizzleXWZ() Vec3u {
	return Vec3u{
		lhs[0],
		lhs[3],
		lhs[2],
	}
}

// SwizzleXWW returns a new vector with the components of this
// vector in the order of XWW.
func (lhs Vec4u) SwizzleXWW() Vec3u {
	return Vec3u{
		lhs[0],
		lhs[3],
		lhs[3],
	}
}

// SwizzleYXX returns a new vector with the components of this
// vector in the order of YXX.
func (lhs Vec4u) SwizzleYXX() Vec3u {
	return Vec3u{
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYXY returns a new vector with the components of this
// vector in the order of YXY.
func (lhs Vec4u) SwizzleYXY() Vec3u {
	return Vec3u{
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYXZ returns a new vector with the components of this
// vector in the order of YXZ.
func (lhs Vec4u) SwizzleYXZ() Vec3u {
	return Vec3u{
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYXW returns a new vector with the components of this
// vector in the order of YXW.
func (lhs Vec4u) SwizzleYXW() Vec3u {
	return Vec3u{
		lhs[1],
		lhs[0],
		lhs[3],
	}
}

// SwizzleYYX returns a new vector with the components of this
// vector in the order of YYX.
func (lhs Vec4u) SwizzleYYX() Vec3u {
	return Vec3u{
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYYY returns a new vector with the components of this
// vector in the order of YYY.
func (lhs Vec4u) SwizzleYYY() Vec3u {
	return Vec3u{
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYYZ returns a new vector with the components of this
// vector in the order of YYZ.
func (lhs Vec4u) SwizzleYYZ() Vec3u {
	return Vec3u{
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYYW returns a new vector with the components of this
// vector in the order of YYW.
func (lhs Vec4u) SwizzleYYW() Vec3u {
	return Vec3u{
		lhs[1],
		lhs[1],
		lhs[3],
	}
}

// SwizzleYZX returns a new vector with the components of this
// vector in the order of YZX.
func (lhs Vec4u) SwizzleYZX() Vec3u {
	return Vec3u{
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYZY returns a new vector with the components of this
// vector in the order of YZY.
func (lhs Vec4u) SwizzleYZY() Vec3u {
	return Vec3u{
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYZZ returns a new vector with the components of this
// vector in the order of YZZ.
func (lhs Vec4u) SwizzleYZZ() Vec3u {
	return Vec3u{
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYZW returns a new vector with the components of this
// vector in the order of YZW.
func (lhs Vec4u) SwizzleYZW() Vec3u {
	return Vec3u{
		lhs[1],
		lhs[2],
		lhs[3],
	}
}

// SwizzleYWX returns a new vector with the components of this
// vector in the order of YWX.
func (lhs Vec4u) SwizzleYWX() Vec3u {
	return Vec3u{
		lhs[1],
		lhs[3],
		lhs[0],
	}
}

// SwizzleYWY returns a new vector with the components of this
// vector in the order of YWY.
func (lhs Vec4u) SwizzleYWY() Vec3u {
	return Vec3u{
		lhs[1],
		lhs[3],
		lhs[1],
	}
}

// SwizzleYWZ returns a new vector with the components of this
// vector in the order of YWZ.
func (lhs Vec4u) SwizzleYWZ() Vec3u {
	return Vec3u{
		lhs[1],
		lhs[3],
		lhs[2],
	}
}

// SwizzleYWW returns a new vector with the components of this
// vector in the order of YWW.
func (lhs Vec4u) SwizzleYWW() Vec3u {
	return Vec3u{
		lhs[1],
		lhs[3],
		lhs[3],
	}
}

// SwizzleZXX returns a new vector with the components of this
// vector in the order of ZXX.
func (lhs Vec4u) SwizzleZXX() Vec3u {
	return Vec3u{
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZXY returns a new vector with the components of this
// vector in the order of ZXY.
func (lhs Vec4u) SwizzleZXY() Vec3u {
	return Vec3u{
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZXZ returns a new vector with the components of this
// vector in the order of ZXZ.
func (lhs Vec4u) SwizzleZXZ() Vec3u {
	return Vec3u{
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZXW returns a new vector with the components of this
// vector in the order of ZXW.
func (lhs Vec4u) SwizzleZXW() Vec3u {
	return Vec3u{
		lhs[2],
		lhs[0],
		lhs[3],
	}
}

// SwizzleZYX returns a new vector with the components of this
// vector in the order of ZYX.
func (lhs Vec4u) SwizzleZYX() Vec3u {
	return Vec3u{
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZYY returns a new vector with the components of this
// vector in the order of ZYY.
func (lhs Vec4u) SwizzleZYY() Vec3u {
	return Vec3u{
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZYZ returns a new vector with the components of this
// vector in the order of ZYZ.
func (lhs Vec4u) SwizzleZYZ() Vec3u {
	return Vec3u{
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZYW returns a new vector with the components of this
// vector in the order of ZYW.
func (lhs Vec4u) SwizzleZYW() Vec3u {
	return Vec3u{
		lhs[2],
		lhs[1],
		lhs[3],
	}
}

// SwizzleZZX returns a new vector with the components of this
// vector in the order of ZZX.
func (lhs Vec4u) SwizzleZZX() Vec3u {
	return Vec3u{
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZZY returns a new vector with the components of this
// vector in the order of ZZY.
func (lhs Vec4u) SwizzleZZY() Vec3u {
	return Vec3u{
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZZZ returns a new vector with the components of this
// vector in the order of ZZZ.
func (lhs Vec4u) SwizzleZZZ() Vec3u {
	return Vec3u{
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZZW returns a new vector with the components of this
// vector in the order of ZZW.
func (lhs Vec4u) SwizzleZZW() Vec3u {
	return Vec3u{
		lhs[2],
		lhs[2],
		lhs[3],
	}
}

// SwizzleZWX returns a new vector with the components of this
// vector in the order of ZWX.
func (lhs Vec4u) SwizzleZWX() Vec3u {
	return Vec3u{
		lhs[2],
		lhs[3],
		lhs[0],
	}
}

// SwizzleZWY returns a new vector with the components of this
// vector in the order of ZWY.
func (lhs Vec4u) SwizzleZWY() Vec3u {
	return Vec3u{
		lhs[2],
		lhs[3],
		lhs[1],
	}
}

// SwizzleZWZ returns a new vector with the components of this
// vector in the order of ZWZ.
func (lhs Vec4u) SwizzleZWZ() Vec3u {
	return Vec3u{
		lhs[2],
		lhs[3],
		lhs[2],
	}
}

// SwizzleZWW returns a new vector with the components of this
// vector in the order of ZWW.
func (lhs Vec4u) SwizzleZWW() Vec3u {
	return Vec3u{
		lhs[2],
		lhs[3],
		lhs[3],
	}
}

// SwizzleWXX returns a new vector with the components of this
// vector in the order of WXX.
func (lhs Vec4u) SwizzleWXX() Vec3u {
	return Vec3u{
		lhs[3],
		lhs[0],
		lhs[0],
	}
}

// SwizzleWXY returns a new vector with the components of this
// vector in the order of WXY.
func (lhs Vec4u) SwizzleWXY() Vec3u {
	return Vec3u{
		lhs[3],
		lhs[0],
		lhs[1],
	}
}

// SwizzleWXZ returns a new vector with the components of this
// vector in the order of WXZ.
func (lhs Vec4u) SwizzleWXZ() Vec3u {
	return Vec3u{
		lhs[3],
		lhs[0],
		lhs[2],
	}
}

// SwizzleWXW returns a new vector with the components of this
// vector in the order of WXW.
func (lhs Vec4u) SwizzleWXW() Vec3u {
	return Vec3u{
		lhs[3],
		lhs[0],
		lhs[3],
	}
}

// SwizzleWYX returns a new vector with the components of this
// vector in the order of WYX.
func (lhs Vec4u) SwizzleWYX() Vec3u {
	return Vec3u{
		lhs[3],
		lhs[1],
		lhs[0],
	}
}

// SwizzleWYY returns a new vector with the components of this
// vector in the order of WYY.
func (lhs Vec4u) SwizzleWYY() Vec3u {
	return Vec3u{
		lhs[3],
		lhs[1],
		lhs[1],
	}
}

// SwizzleWYZ returns a new vector with the components of this
// vector in the order of WYZ.
func (lhs Vec4u) SwizzleWYZ() Vec3u {
	return Vec3u{
		lhs[3],
		lhs[1],
		lhs[2],
	}
}

// SwizzleWYW returns a new vector with the components of this
// vector in the order of WYW.
func (lhs Vec4u) SwizzleWYW() Vec3u {
	return Vec3u{
		lhs[3],
		lhs[1],
		lhs[3],
	}
}

// SwizzleWZX returns a new vector with the components of this
// vector in the order of WZX.
func (lhs Vec4u) SwizzleWZX() Vec3u {
	return Vec3u{
		lhs[3],
		lhs[2],
		lhs[0],
	}
}

// SwizzleWZY returns a new vector with the components of this
// vector in the order of WZY.
func (lhs Vec4u) SwizzleWZY() Vec3u {
	return Vec3u{
		lhs[3],
		lhs[2],
		lhs[1],
	}
}

// SwizzleWZZ returns a new vector with the components of this
// vector in the order of WZZ.
func (lhs Vec4u) SwizzleWZZ() Vec3u {
	return Vec3u{
		lhs[3],
		lhs[2],
		lhs[2],
	}
}

// SwizzleWZW returns a new vector with the components of this
// vector in the order of WZW.
func (lhs Vec4u) SwizzleWZW() Vec3u {
	return Vec3u{
		lhs[3],
		lhs[2],
		lhs[3],
	}
}

// SwizzleWWX returns a new vector with the components of this
// vector in the order of WWX.
func (lhs Vec4u) SwizzleWWX() Vec3u {
	return Vec3u{
		lhs[3],
		lhs[3],
		lhs[0],
	}
}

// SwizzleWWY returns a new vector with the components of this
// vector in the order of WWY.
func (lhs Vec4u) SwizzleWWY() Vec3u {
	return Vec3u{
		lhs[3],
		lhs[3],
		lhs[1],
	}
}

// SwizzleWWZ returns a new vector with the components of this
// vector in the order of WWZ.
func (lhs Vec4u) SwizzleWWZ() Vec3u {
	return Vec3u{
		lhs[3],
		lhs[3],
		lhs[2],
	}
}

// SwizzleWWW returns a new vector with the components of this
// vector in the order of WWW.
func (lhs Vec4u) SwizzleWWW() Vec3u {
	return Vec3u{
		lhs[3],
		lhs[3],
		lhs[3],
	}
}

// SwizzleXXXX returns a new vector with the components of this
// vector in the order of XXXX.
func (lhs Vec4u) SwizzleXXXX() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXXXY returns a new vector with the components of this
// vector in the order of XXXY.
func (lhs Vec4u) SwizzleXXXY() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXXXZ returns a new vector with the components of this
// vector in the order of XXXZ.
func (lhs Vec4u) SwizzleXXXZ() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXXXW returns a new vector with the components of this
// vector in the order of XXXW.
func (lhs Vec4u) SwizzleXXXW() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[0],
		lhs[0],
		lhs[3],
	}
}

// SwizzleXXYX returns a new vector with the components of this
// vector in the order of XXYX.
func (lhs Vec4u) SwizzleXXYX() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXXYY returns a new vector with the components of this
// vector in the order of XXYY.
func (lhs Vec4u) SwizzleXXYY() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXXYZ returns a new vector with the components of this
// vector in the order of XXYZ.
func (lhs Vec4u) SwizzleXXYZ() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXXYW returns a new vector with the components of this
// vector in the order of XXYW.
func (lhs Vec4u) SwizzleXXYW() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[0],
		lhs[1],
		lhs[3],
	}
}

// SwizzleXXZX returns a new vector with the components of this
// vector in the order of XXZX.
func (lhs Vec4u) SwizzleXXZX() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXXZY returns a new vector with the components of this
// vector in the order of XXZY.
func (lhs Vec4u) SwizzleXXZY() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXXZZ returns a new vector with the components of this
// vector in the order of XXZZ.
func (lhs Vec4u) SwizzleXXZZ() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleXXZW returns a new vector with the components of this
// vector in the order of XXZW.
func (lhs Vec4u) SwizzleXXZW() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[0],
		lhs[2],
		lhs[3],
	}
}

// SwizzleXXWX returns a new vector with the components of this
// vector in the order of XXWX.
func (lhs Vec4u) SwizzleXXWX() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[0],
		lhs[3],
		lhs[0],
	}
}

// SwizzleXXWY returns a new vector with the components of this
// vector in the order of XXWY.
func (lhs Vec4u) SwizzleXXWY() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[0],
		lhs[3],
		lhs[1],
	}
}

// SwizzleXXWZ returns a new vector with the components of this
// vector in the order of XXWZ.
func (lhs Vec4u) SwizzleXXWZ() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[0],
		lhs[3],
		lhs[2],
	}
}

// SwizzleXXWW returns a new vector with the components of this
// vector in the order of XXWW.
func (lhs Vec4u) SwizzleXXWW() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[0],
		lhs[3],
		lhs[3],
	}
}

// SwizzleXYXX returns a new vector with the components of this
// vector in the order of XYXX.
func (lhs Vec4u) SwizzleXYXX() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXYXY returns a new vector with the components of this
// vector in the order of XYXY.
func (lhs Vec4u) SwizzleXYXY() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXYXZ returns a new vector with the components of this
// vector in the order of XYXZ.
func (lhs Vec4u) SwizzleXYXZ() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXYXW returns a new vector with the components of this
// vector in the order of XYXW.
func (lhs Vec4u) SwizzleXYXW() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[1],
		lhs[0],
		lhs[3],
	}
}

// SwizzleXYYX returns a new vector with the components of this
// vector in the order of XYYX.
func (lhs Vec4u) SwizzleXYYX() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXYYY returns a new vector with the components of this
// vector in the order of XYYY.
func (lhs Vec4u) SwizzleXYYY() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXYYZ returns a new vector with the components of this
// vector in the order of XYYZ.
func (lhs Vec4u) SwizzleXYYZ() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXYYW returns a new vector with the components of this
// vector in the order of XYYW.
func (lhs Vec4u) SwizzleXYYW() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[1],
		lhs[1],
		lhs[3],
	}
}

// SwizzleXYZX returns a new vector with the components of this
// vector in the order of XYZX.
func (lhs Vec4u) SwizzleXYZX() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXYZY returns a new vector with the components of this
// vector in the order of XYZY.
func (lhs Vec4u) SwizzleXYZY() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXYZZ returns a new vector with the components of this
// vector in the order of XYZZ.
func (lhs Vec4u) SwizzleXYZZ() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleXYZW returns a new vector with the components of this
// vector in the order of XYZW.
func (lhs Vec4u) SwizzleXYZW() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[1],
		lhs[2],
		lhs[3],
	}
}

// SwizzleXYWX returns a new vector with the components of this
// vector in the order of XYWX.
func (lhs Vec4u) SwizzleXYWX() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[1],
		lhs[3],
		lhs[0],
	}
}

// SwizzleXYWY returns a new vector with the components of this
// vector in the order of XYWY.
func (lhs Vec4u) SwizzleXYWY() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[1],
		lhs[3],
		lhs[1],
	}
}

// SwizzleXYWZ returns a new vector with the components of this
// vector in the order of XYWZ.
func (lhs Vec4u) SwizzleXYWZ() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[1],
		lhs[3],
		lhs[2],
	}
}

// SwizzleXYWW returns a new vector with the components of this
// vector in the order of XYWW.
func (lhs Vec4u) SwizzleXYWW() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[1],
		lhs[3],
		lhs[3],
	}
}

// SwizzleXZXX returns a new vector with the components of this
// vector in the order of XZXX.
func (lhs Vec4u) SwizzleXZXX() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXZXY returns a new vector with the components of this
// vector in the order of XZXY.
func (lhs Vec4u) SwizzleXZXY() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXZXZ returns a new vector with the components of this
// vector in the order of XZXZ.
func (lhs Vec4u) SwizzleXZXZ() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXZXW returns a new vector with the components of this
// vector in the order of XZXW.
func (lhs Vec4u) SwizzleXZXW() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[2],
		lhs[0],
		lhs[3],
	}
}

// SwizzleXZYX returns a new vector with the components of this
// vector in the order of XZYX.
func (lhs Vec4u) SwizzleXZYX() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXZYY returns a new vector with the components of this
// vector in the order of XZYY.
func (lhs Vec4u) SwizzleXZYY() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXZYZ returns a new vector with the components of this
// vector in the order of XZYZ.
func (lhs Vec4u) SwizzleXZYZ() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXZYW returns a new vector with the components of this
// vector in the order of XZYW.
func (lhs Vec4u) SwizzleXZYW() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[2],
		lhs[1],
		lhs[3],
	}
}

// SwizzleXZZX returns a new vector with the components of this
// vector in the order of XZZX.
func (lhs Vec4u) SwizzleXZZX() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXZZY returns a new vector with the components of this
// vector in the order of XZZY.
func (lhs Vec4u) SwizzleXZZY() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXZZZ returns a new vector with the components of this
// vector in the order of XZZZ.
func (lhs Vec4u) SwizzleXZZZ() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

// SwizzleXZZW returns a new vector with the components of this
// vector in the order of XZZW.
func (lhs Vec4u) SwizzleXZZW() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[2],
		lhs[2],
		lhs[3],
	}
}

// SwizzleXZWX returns a new vector with the components of this
// vector in the order of XZWX.
func (lhs Vec4u) SwizzleXZWX() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[2],
		lhs[3],
		lhs[0],
	}
}

// SwizzleXZWY returns a new vector with the components of this
// vector in the order of XZWY.
func (lhs Vec4u) SwizzleXZWY() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[2],
		lhs[3],
		lhs[1],
	}
}

// SwizzleXZWZ returns a new vector with the components of this
// vector in the order of XZWZ.
func (lhs Vec4u) SwizzleXZWZ() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[2],
		lhs[3],
		lhs[2],
	}
}

// SwizzleXZWW returns a new vector with the components of this
// vector in the order of XZWW.
func (lhs Vec4u) SwizzleXZWW() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[2],
		lhs[3],
		lhs[3],
	}
}

// SwizzleXWXX returns a new vector with the components of this
// vector in the order of XWXX.
func (lhs Vec4u) SwizzleXWXX() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[3],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXWXY returns a new vector with the components of this
// vector in the order of XWXY.
func (lhs Vec4u) SwizzleXWXY() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[3],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXWXZ returns a new vector with the components of this
// vector in the order of XWXZ.
func (lhs Vec4u) SwizzleXWXZ() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[3],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXWXW returns a new vector with the components of this
// vector in the order of XWXW.
func (lhs Vec4u) SwizzleXWXW() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[3],
		lhs[0],
		lhs[3],
	}
}

// SwizzleXWYX returns a new vector with the components of this
// vector in the order of XWYX.
func (lhs Vec4u) SwizzleXWYX() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[3],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXWYY returns a new vector with the components of this
// vector in the order of XWYY.
func (lhs Vec4u) SwizzleXWYY() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[3],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXWYZ returns a new vector with the components of this
// vector in the order of XWYZ.
func (lhs Vec4u) SwizzleXWYZ() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[3],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXWYW returns a new vector with the components of this
// vector in the order of XWYW.
func (lhs Vec4u) SwizzleXWYW() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[3],
		lhs[1],
		lhs[3],
	}
}

// SwizzleXWZX returns a new vector with the components of this
// vector in the order of XWZX.
func (lhs Vec4u) SwizzleXWZX() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[3],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXWZY returns a new vector with the components of this
// vector in the order of XWZY.
func (lhs Vec4u) SwizzleXWZY() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[3],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXWZZ returns a new vector with the components of this
// vector in the order of XWZZ.
func (lhs Vec4u) SwizzleXWZZ() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[3],
		lhs[2],
		lhs[2],
	}
}

// SwizzleXWZW returns a new vector with the components of this
// vector in the order of XWZW.
func (lhs Vec4u) SwizzleXWZW() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[3],
		lhs[2],
		lhs[3],
	}
}

// SwizzleXWWX returns a new vector with the components of this
// vector in the order of XWWX.
func (lhs Vec4u) SwizzleXWWX() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[3],
		lhs[3],
		lhs[0],
	}
}

// SwizzleXWWY returns a new vector with the components of this
// vector in the order of XWWY.
func (lhs Vec4u) SwizzleXWWY() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[3],
		lhs[3],
		lhs[1],
	}
}

// SwizzleXWWZ returns a new vector with the components of this
// vector in the order of XWWZ.
func (lhs Vec4u) SwizzleXWWZ() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[3],
		lhs[3],
		lhs[2],
	}
}

// SwizzleXWWW returns a new vector with the components of this
// vector in the order of XWWW.
func (lhs Vec4u) SwizzleXWWW() Vec4u {
	return Vec4u{
		lhs[0],
		lhs[3],
		lhs[3],
		lhs[3],
	}
}

// SwizzleYXXX returns a new vector with the components of this
// vector in the order of YXXX.
func (lhs Vec4u) SwizzleYXXX() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYXXY returns a new vector with the components of this
// vector in the order of YXXY.
func (lhs Vec4u) SwizzleYXXY() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYXXZ returns a new vector with the components of this
// vector in the order of YXXZ.
func (lhs Vec4u) SwizzleYXXZ() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYXXW returns a new vector with the components of this
// vector in the order of YXXW.
func (lhs Vec4u) SwizzleYXXW() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[0],
		lhs[0],
		lhs[3],
	}
}

// SwizzleYXYX returns a new vector with the components of this
// vector in the order of YXYX.
func (lhs Vec4u) SwizzleYXYX() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYXYY returns a new vector with the components of this
// vector in the order of YXYY.
func (lhs Vec4u) SwizzleYXYY() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYXYZ returns a new vector with the components of this
// vector in the order of YXYZ.
func (lhs Vec4u) SwizzleYXYZ() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYXYW returns a new vector with the components of this
// vector in the order of YXYW.
func (lhs Vec4u) SwizzleYXYW() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[0],
		lhs[1],
		lhs[3],
	}
}

// SwizzleYXZX returns a new vector with the components of this
// vector in the order of YXZX.
func (lhs Vec4u) SwizzleYXZX() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYXZY returns a new vector with the components of this
// vector in the order of YXZY.
func (lhs Vec4u) SwizzleYXZY() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYXZZ returns a new vector with the components of this
// vector in the order of YXZZ.
func (lhs Vec4u) SwizzleYXZZ() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYXZW returns a new vector with the components of this
// vector in the order of YXZW.
func (lhs Vec4u) SwizzleYXZW() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[0],
		lhs[2],
		lhs[3],
	}
}

// SwizzleYXWX returns a new vector with the components of this
// vector in the order of YXWX.
func (lhs Vec4u) SwizzleYXWX() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[0],
		lhs[3],
		lhs[0],
	}
}

// SwizzleYXWY returns a new vector with the components of this
// vector in the order of YXWY.
func (lhs Vec4u) SwizzleYXWY() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[0],
		lhs[3],
		lhs[1],
	}
}

// SwizzleYXWZ returns a new vector with the components of this
// vector in the order of YXWZ.
func (lhs Vec4u) SwizzleYXWZ() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[0],
		lhs[3],
		lhs[2],
	}
}

// SwizzleYXWW returns a new vector with the components of this
// vector in the order of YXWW.
func (lhs Vec4u) SwizzleYXWW() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[0],
		lhs[3],
		lhs[3],
	}
}

// SwizzleYYXX returns a new vector with the components of this
// vector in the order of YYXX.
func (lhs Vec4u) SwizzleYYXX() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYYXY returns a new vector with the components of this
// vector in the order of YYXY.
func (lhs Vec4u) SwizzleYYXY() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYYXZ returns a new vector with the components of this
// vector in the order of YYXZ.
func (lhs Vec4u) SwizzleYYXZ() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYYXW returns a new vector with the components of this
// vector in the order of YYXW.
func (lhs Vec4u) SwizzleYYXW() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[1],
		lhs[0],
		lhs[3],
	}
}

// SwizzleYYYX returns a new vector with the components of this
// vector in the order of YYYX.
func (lhs Vec4u) SwizzleYYYX() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYYYY returns a new vector with the components of this
// vector in the order of YYYY.
func (lhs Vec4u) SwizzleYYYY() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYYYZ returns a new vector with the components of this
// vector in the order of YYYZ.
func (lhs Vec4u) SwizzleYYYZ() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYYYW returns a new vector with the components of this
// vector in the order of YYYW.
func (lhs Vec4u) SwizzleYYYW() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[1],
		lhs[1],
		lhs[3],
	}
}

// SwizzleYYZX returns a new vector with the components of this
// vector in the order of YYZX.
func (lhs Vec4u) SwizzleYYZX() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYYZY returns a new vector with the components of this
// vector in the order of YYZY.
func (lhs Vec4u) SwizzleYYZY() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYYZZ returns a new vector with the components of this
// vector in the order of YYZZ.
func (lhs Vec4u) SwizzleYYZZ() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYYZW returns a new vector with the components of this
// vector in the order of YYZW.
func (lhs Vec4u) SwizzleYYZW() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[1],
		lhs[2],
		lhs[3],
	}
}

// SwizzleYYWX returns a new vector with the components of this
// vector in the order of YYWX.
func (lhs Vec4u) SwizzleYYWX() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[1],
		lhs[3],
		lhs[0],
	}
}

// SwizzleYYWY returns a new vector with the components of this
// vector in the order of YYWY.
func (lhs Vec4u) SwizzleYYWY() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[1],
		lhs[3],
		lhs[1],
	}
}

// SwizzleYYWZ returns a new vector with the components of this
// vector in the order of YYWZ.
func (lhs Vec4u) SwizzleYYWZ() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[1],
		lhs[3],
		lhs[2],
	}
}

// SwizzleYYWW returns a new vector with the components of this
// vector in the order of YYWW.
func (lhs Vec4u) SwizzleYYWW() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[1],
		lhs[3],
		lhs[3],
	}
}

// SwizzleYZXX returns a new vector with the components of this
// vector in the order of YZXX.
func (lhs Vec4u) SwizzleYZXX() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYZXY returns a new vector with the components of this
// vector in the order of YZXY.
func (lhs Vec4u) SwizzleYZXY() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYZXZ returns a new vector with the components of this
// vector in the order of YZXZ.
func (lhs Vec4u) SwizzleYZXZ() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYZXW returns a new vector with the components of this
// vector in the order of YZXW.
func (lhs Vec4u) SwizzleYZXW() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[2],
		lhs[0],
		lhs[3],
	}
}

// SwizzleYZYX returns a new vector with the components of this
// vector in the order of YZYX.
func (lhs Vec4u) SwizzleYZYX() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYZYY returns a new vector with the components of this
// vector in the order of YZYY.
func (lhs Vec4u) SwizzleYZYY() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYZYZ returns a new vector with the components of this
// vector in the order of YZYZ.
func (lhs Vec4u) SwizzleYZYZ() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYZYW returns a new vector with the components of this
// vector in the order of YZYW.
func (lhs Vec4u) SwizzleYZYW() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[2],
		lhs[1],
		lhs[3],
	}
}

// SwizzleYZZX returns a new vector with the components of this
// vector in the order of YZZX.
func (lhs Vec4u) SwizzleYZZX() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYZZY returns a new vector with the components of this
// vector in the order of YZZY.
func (lhs Vec4u) SwizzleYZZY() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYZZZ returns a new vector with the components of this
// vector in the order of YZZZ.
func (lhs Vec4u) SwizzleYZZZ() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYZZW returns a new vector with the components of this
// vector in the order of YZZW.
func (lhs Vec4u) SwizzleYZZW() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[2],
		lhs[2],
		lhs[3],
	}
}

// SwizzleYZWX returns a new vector with the components of this
// vector in the order of YZWX.
func (lhs Vec4u) SwizzleYZWX() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[2],
		lhs[3],
		lhs[0],
	}
}

// SwizzleYZWY returns a new vector with the components of this
// vector in the order of YZWY.
func (lhs Vec4u) SwizzleYZWY() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[2],
		lhs[3],
		lhs[1],
	}
}

// SwizzleYZWZ returns a new vector with the components of this
// vector in the order of YZWZ.
func (lhs Vec4u) SwizzleYZWZ() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[2],
		lhs[3],
		lhs[2],
	}
}

// SwizzleYZWW returns a new vector with the components of this
// vector in the order of YZWW.
func (lhs Vec4u) SwizzleYZWW() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[2],
		lhs[3],
		lhs[3],
	}
}

// SwizzleYWXX returns a new vector with the components of this
// vector in the order of YWXX.
func (lhs Vec4u) SwizzleYWXX() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[3],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYWXY returns a new vector with the components of this
// vector in the order of YWXY.
func (lhs Vec4u) SwizzleYWXY() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[3],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYWXZ returns a new vector with the components of this
// vector in the order of YWXZ.
func (lhs Vec4u) SwizzleYWXZ() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[3],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYWXW returns a new vector with the components of this
// vector in the order of YWXW.
func (lhs Vec4u) SwizzleYWXW() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[3],
		lhs[0],
		lhs[3],
	}
}

// SwizzleYWYX returns a new vector with the components of this
// vector in the order of YWYX.
func (lhs Vec4u) SwizzleYWYX() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[3],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYWYY returns a new vector with the components of this
// vector in the order of YWYY.
func (lhs Vec4u) SwizzleYWYY() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[3],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYWYZ returns a new vector with the components of this
// vector in the order of YWYZ.
func (lhs Vec4u) SwizzleYWYZ() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[3],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYWYW returns a new vector with the components of this
// vector in the order of YWYW.
func (lhs Vec4u) SwizzleYWYW() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[3],
		lhs[1],
		lhs[3],
	}
}

// SwizzleYWZX returns a new vector with the components of this
// vector in the order of YWZX.
func (lhs Vec4u) SwizzleYWZX() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[3],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYWZY returns a new vector with the components of this
// vector in the order of YWZY.
func (lhs Vec4u) SwizzleYWZY() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[3],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYWZZ returns a new vector with the components of this
// vector in the order of YWZZ.
func (lhs Vec4u) SwizzleYWZZ() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[3],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYWZW returns a new vector with the components of this
// vector in the order of YWZW.
func (lhs Vec4u) SwizzleYWZW() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[3],
		lhs[2],
		lhs[3],
	}
}

// SwizzleYWWX returns a new vector with the components of this
// vector in the order of YWWX.
func (lhs Vec4u) SwizzleYWWX() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[3],
		lhs[3],
		lhs[0],
	}
}

// SwizzleYWWY returns a new vector with the components of this
// vector in the order of YWWY.
func (lhs Vec4u) SwizzleYWWY() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[3],
		lhs[3],
		lhs[1],
	}
}

// SwizzleYWWZ returns a new vector with the components of this
// vector in the order of YWWZ.
func (lhs Vec4u) SwizzleYWWZ() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[3],
		lhs[3],
		lhs[2],
	}
}

// SwizzleYWWW returns a new vector with the components of this
// vector in the order of YWWW.
func (lhs Vec4u) SwizzleYWWW() Vec4u {
	return Vec4u{
		lhs[1],
		lhs[3],
		lhs[3],
		lhs[3],
	}
}

// SwizzleZXXX returns a new vector with the components of this
// vector in the order of ZXXX.
func (lhs Vec4u) SwizzleZXXX() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZXXY returns a new vector with the components of this
// vector in the order of ZXXY.
func (lhs Vec4u) SwizzleZXXY() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZXXZ returns a new vector with the components of this
// vector in the order of ZXXZ.
func (lhs Vec4u) SwizzleZXXZ() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZXXW returns a new vector with the components of this
// vector in the order of ZXXW.
func (lhs Vec4u) SwizzleZXXW() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[0],
		lhs[0],
		lhs[3],
	}
}

// SwizzleZXYX returns a new vector with the components of this
// vector in the order of ZXYX.
func (lhs Vec4u) SwizzleZXYX() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZXYY returns a new vector with the components of this
// vector in the order of ZXYY.
func (lhs Vec4u) SwizzleZXYY() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZXYZ returns a new vector with the components of this
// vector in the order of ZXYZ.
func (lhs Vec4u) SwizzleZXYZ() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZXYW returns a new vector with the components of this
// vector in the order of ZXYW.
func (lhs Vec4u) SwizzleZXYW() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[0],
		lhs[1],
		lhs[3],
	}
}

// SwizzleZXZX returns a new vector with the components of this
// vector in the order of ZXZX.
func (lhs Vec4u) SwizzleZXZX() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZXZY returns a new vector with the components of this
// vector in the order of ZXZY.
func (lhs Vec4u) SwizzleZXZY() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZXZZ returns a new vector with the components of this
// vector in the order of ZXZZ.
func (lhs Vec4u) SwizzleZXZZ() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZXZW returns a new vector with the components of this
// vector in the order of ZXZW.
func (lhs Vec4u) SwizzleZXZW() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[0],
		lhs[2],
		lhs[3],
	}
}

// SwizzleZXWX returns a new vector with the components of this
// vector in the order of ZXWX.
func (lhs Vec4u) SwizzleZXWX() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[0],
		lhs[3],
		lhs[0],
	}
}

// SwizzleZXWY returns a new vector with the components of this
// vector in the order of ZXWY.
func (lhs Vec4u) SwizzleZXWY() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[0],
		lhs[3],
		lhs[1],
	}
}

// SwizzleZXWZ returns a new vector with the components of this
// vector in the order of ZXWZ.
func (lhs Vec4u) SwizzleZXWZ() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[0],
		lhs[3],
		lhs[2],
	}
}

// SwizzleZXWW returns a new vector with the components of this
// vector in the order of ZXWW.
func (lhs Vec4u) SwizzleZXWW() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[0],
		lhs[3],
		lhs[3],
	}
}

// SwizzleZYXX returns a new vector with the components of this
// vector in the order of ZYXX.
func (lhs Vec4u) SwizzleZYXX() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZYXY returns a new vector with the components of this
// vector in the order of ZYXY.
func (lhs Vec4u) SwizzleZYXY() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZYXZ returns a new vector with the components of this
// vector in the order of ZYXZ.
func (lhs Vec4u) SwizzleZYXZ() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZYXW returns a new vector with the components of this
// vector in the order of ZYXW.
func (lhs Vec4u) SwizzleZYXW() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[1],
		lhs[0],
		lhs[3],
	}
}

// SwizzleZYYX returns a new vector with the components of this
// vector in the order of ZYYX.
func (lhs Vec4u) SwizzleZYYX() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZYYY returns a new vector with the components of this
// vector in the order of ZYYY.
func (lhs Vec4u) SwizzleZYYY() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZYYZ returns a new vector with the components of this
// vector in the order of ZYYZ.
func (lhs Vec4u) SwizzleZYYZ() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZYYW returns a new vector with the components of this
// vector in the order of ZYYW.
func (lhs Vec4u) SwizzleZYYW() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[1],
		lhs[1],
		lhs[3],
	}
}

// SwizzleZYZX returns a new vector with the components of this
// vector in the order of ZYZX.
func (lhs Vec4u) SwizzleZYZX() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZYZY returns a new vector with the components of this
// vector in the order of ZYZY.
func (lhs Vec4u) SwizzleZYZY() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZYZZ returns a new vector with the components of this
// vector in the order of ZYZZ.
func (lhs Vec4u) SwizzleZYZZ() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZYZW returns a new vector with the components of this
// vector in the order of ZYZW.
func (lhs Vec4u) SwizzleZYZW() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[1],
		lhs[2],
		lhs[3],
	}
}

// SwizzleZYWX returns a new vector with the components of this
// vector in the order of ZYWX.
func (lhs Vec4u) SwizzleZYWX() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[1],
		lhs[3],
		lhs[0],
	}
}

// SwizzleZYWY returns a new vector with the components of this
// vector in the order of ZYWY.
func (lhs Vec4u) SwizzleZYWY() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[1],
		lhs[3],
		lhs[1],
	}
}

// SwizzleZYWZ returns a new vector with the components of this
// vector in the order of ZYWZ.
func (lhs Vec4u) SwizzleZYWZ() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[1],
		lhs[3],
		lhs[2],
	}
}

// SwizzleZYWW returns a new vector with the components of this
// vector in the order of ZYWW.
func (lhs Vec4u) SwizzleZYWW() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[1],
		lhs[3],
		lhs[3],
	}
}

// SwizzleZZXX returns a new vector with the components of this
// vector in the order of ZZXX.
func (lhs Vec4u) SwizzleZZXX() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZZXY returns a new vector with the components of this
// vector in the order of ZZXY.
func (lhs Vec4u) SwizzleZZXY() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZZXZ returns a new vector with the components of this
// vector in the order of ZZXZ.
func (lhs Vec4u) SwizzleZZXZ() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZZXW returns a new vector with the components of this
// vector in the order of ZZXW.
func (lhs Vec4u) SwizzleZZXW() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[2],
		lhs[0],
		lhs[3],
	}
}

// SwizzleZZYX returns a new vector with the components of this
// vector in the order of ZZYX.
func (lhs Vec4u) SwizzleZZYX() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZZYY returns a new vector with the components of this
// vector in the order of ZZYY.
func (lhs Vec4u) SwizzleZZYY() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZZYZ returns a new vector with the components of this
// vector in the order of ZZYZ.
func (lhs Vec4u) SwizzleZZYZ() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZZYW returns a new vector with the components of this
// vector in the order of ZZYW.
func (lhs Vec4u) SwizzleZZYW() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[2],
		lhs[1],
		lhs[3],
	}
}

// SwizzleZZZX returns a new vector with the components of this
// vector in the order of ZZZX.
func (lhs Vec4u) SwizzleZZZX() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZZZY returns a new vector with the components of this
// vector in the order of ZZZY.
func (lhs Vec4u) SwizzleZZZY() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZZZZ returns a new vector with the components of this
// vector in the order of ZZZZ.
func (lhs Vec4u) SwizzleZZZZ() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZZZW returns a new vector with the components of this
// vector in the order of ZZZW.
func (lhs Vec4u) SwizzleZZZW() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[2],
		lhs[2],
		lhs[3],
	}
}

// SwizzleZZWX returns a new vector with the components of this
// vector in the order of ZZWX.
func (lhs Vec4u) SwizzleZZWX() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[2],
		lhs[3],
		lhs[0],
	}
}

// SwizzleZZWY returns a new vector with the components of this
// vector in the order of ZZWY.
func (lhs Vec4u) SwizzleZZWY() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[2],
		lhs[3],
		lhs[1],
	}
}

// SwizzleZZWZ returns a new vector with the components of this
// vector in the order of ZZWZ.
func (lhs Vec4u) SwizzleZZWZ() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[2],
		lhs[3],
		lhs[2],
	}
}

// SwizzleZZWW returns a new vector with the components of this
// vector in the order of ZZWW.
func (lhs Vec4u) SwizzleZZWW() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[2],
		lhs[3],
		lhs[3],
	}
}

// SwizzleZWXX returns a new vector with the components of this
// vector in the order of ZWXX.
func (lhs Vec4u) SwizzleZWXX() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[3],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZWXY returns a new vector with the components of this
// vector in the order of ZWXY.
func (lhs Vec4u) SwizzleZWXY() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[3],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZWXZ returns a new vector with the components of this
// vector in the order of ZWXZ.
func (lhs Vec4u) SwizzleZWXZ() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[3],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZWXW returns a new vector with the components of this
// vector in the order of ZWXW.
func (lhs Vec4u) SwizzleZWXW() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[3],
		lhs[0],
		lhs[3],
	}
}

// SwizzleZWYX returns a new vector with the components of this
// vector in the order of ZWYX.
func (lhs Vec4u) SwizzleZWYX() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[3],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZWYY returns a new vector with the components of this
// vector in the order of ZWYY.
func (lhs Vec4u) SwizzleZWYY() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[3],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZWYZ returns a new vector with the components of this
// vector in the order of ZWYZ.
func (lhs Vec4u) SwizzleZWYZ() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[3],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZWYW returns a new vector with the components of this
// vector in the order of ZWYW.
func (lhs Vec4u) SwizzleZWYW() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[3],
		lhs[1],
		lhs[3],
	}
}

// SwizzleZWZX returns a new vector with the components of this
// vector in the order of ZWZX.
func (lhs Vec4u) SwizzleZWZX() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[3],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZWZY returns a new vector with the components of this
// vector in the order of ZWZY.
func (lhs Vec4u) SwizzleZWZY() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[3],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZWZZ returns a new vector with the components of this
// vector in the order of ZWZZ.
func (lhs Vec4u) SwizzleZWZZ() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[3],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZWZW returns a new vector with the components of this
// vector in the order of ZWZW.
func (lhs Vec4u) SwizzleZWZW() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[3],
		lhs[2],
		lhs[3],
	}
}

// SwizzleZWWX returns a new vector with the components of this
// vector in the order of ZWWX.
func (lhs Vec4u) SwizzleZWWX() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[3],
		lhs[3],
		lhs[0],
	}
}

// SwizzleZWWY returns a new vector with the components of this
// vector in the order of ZWWY.
func (lhs Vec4u) SwizzleZWWY() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[3],
		lhs[3],
		lhs[1],
	}
}

// SwizzleZWWZ returns a new vector with the components of this
// vector in the order of ZWWZ.
func (lhs Vec4u) SwizzleZWWZ() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[3],
		lhs[3],
		lhs[2],
	}
}

// SwizzleZWWW returns a new vector with the components of this
// vector in the order of ZWWW.
func (lhs Vec4u) SwizzleZWWW() Vec4u {
	return Vec4u{
		lhs[2],
		lhs[3],
		lhs[3],
		lhs[3],
	}
}

// SwizzleWXXX returns a new vector with the components of this
// vector in the order of WXXX.
func (lhs Vec4u) SwizzleWXXX() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleWXXY returns a new vector with the components of this
// vector in the order of WXXY.
func (lhs Vec4u) SwizzleWXXY() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleWXXZ returns a new vector with the components of this
// vector in the order of WXXZ.
func (lhs Vec4u) SwizzleWXXZ() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleWXXW returns a new vector with the components of this
// vector in the order of WXXW.
func (lhs Vec4u) SwizzleWXXW() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[0],
		lhs[0],
		lhs[3],
	}
}

// SwizzleWXYX returns a new vector with the components of this
// vector in the order of WXYX.
func (lhs Vec4u) SwizzleWXYX() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleWXYY returns a new vector with the components of this
// vector in the order of WXYY.
func (lhs Vec4u) SwizzleWXYY() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleWXYZ returns a new vector with the components of this
// vector in the order of WXYZ.
func (lhs Vec4u) SwizzleWXYZ() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleWXYW returns a new vector with the components of this
// vector in the order of WXYW.
func (lhs Vec4u) SwizzleWXYW() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[0],
		lhs[1],
		lhs[3],
	}
}

// SwizzleWXZX returns a new vector with the components of this
// vector in the order of WXZX.
func (lhs Vec4u) SwizzleWXZX() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleWXZY returns a new vector with the components of this
// vector in the order of WXZY.
func (lhs Vec4u) SwizzleWXZY() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleWXZZ returns a new vector with the components of this
// vector in the order of WXZZ.
func (lhs Vec4u) SwizzleWXZZ() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleWXZW returns a new vector with the components of this
// vector in the order of WXZW.
func (lhs Vec4u) SwizzleWXZW() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[0],
		lhs[2],
		lhs[3],
	}
}

// SwizzleWXWX returns a new vector with the components of this
// vector in the order of WXWX.
func (lhs Vec4u) SwizzleWXWX() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[0],
		lhs[3],
		lhs[0],
	}
}

// SwizzleWXWY returns a new vector with the components of this
// vector in the order of WXWY.
func (lhs Vec4u) SwizzleWXWY() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[0],
		lhs[3],
		lhs[1],
	}
}

// SwizzleWXWZ returns a new vector with the components of this
// vector in the order of WXWZ.
func (lhs Vec4u) SwizzleWXWZ() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[0],
		lhs[3],
		lhs[2],
	}
}

// SwizzleWXWW returns a new vector with the components of this
// vector in the order of WXWW.
func (lhs Vec4u) SwizzleWXWW() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[0],
		lhs[3],
		lhs[3],
	}
}

// SwizzleWYXX returns a new vector with the components of this
// vector in the order of WYXX.
func (lhs Vec4u) SwizzleWYXX() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleWYXY returns a new vector with the components of this
// vector in the order of WYXY.
func (lhs Vec4u) SwizzleWYXY() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleWYXZ returns a new vector with the components of this
// vector in the order of WYXZ.
func (lhs Vec4u) SwizzleWYXZ() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleWYXW returns a new vector with the components of this
// vector in the order of WYXW.
func (lhs Vec4u) SwizzleWYXW() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[1],
		lhs[0],
		lhs[3],
	}
}

// SwizzleWYYX returns a new vector with the components of this
// vector in the order of WYYX.
func (lhs Vec4u) SwizzleWYYX() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleWYYY returns a new vector with the components of this
// vector in the order of WYYY.
func (lhs Vec4u) SwizzleWYYY() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleWYYZ returns a new vector with the components of this
// vector in the order of WYYZ.
func (lhs Vec4u) SwizzleWYYZ() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleWYYW returns a new vector with the components of this
// vector in the order of WYYW.
func (lhs Vec4u) SwizzleWYYW() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[1],
		lhs[1],
		lhs[3],
	}
}

// SwizzleWYZX returns a new vector with the components of this
// vector in the order of WYZX.
func (lhs Vec4u) SwizzleWYZX() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleWYZY returns a new vector with the components of this
// vector in the order of WYZY.
func (lhs Vec4u) SwizzleWYZY() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleWYZZ returns a new vector with the components of this
// vector in the order of WYZZ.
func (lhs Vec4u) SwizzleWYZZ() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleWYZW returns a new vector with the components of this
// vector in the order of WYZW.
func (lhs Vec4u) SwizzleWYZW() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[1],
		lhs[2],
		lhs[3],
	}
}

// SwizzleWYWX returns a new vector with the components of this
// vector in the order of WYWX.
func (lhs Vec4u) SwizzleWYWX() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[1],
		lhs[3],
		lhs[0],
	}
}

// SwizzleWYWY returns a new vector with the components of this
// vector in the order of WYWY.
func (lhs Vec4u) SwizzleWYWY() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[1],
		lhs[3],
		lhs[1],
	}
}

// SwizzleWYWZ returns a new vector with the components of this
// vector in the order of WYWZ.
func (lhs Vec4u) SwizzleWYWZ() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[1],
		lhs[3],
		lhs[2],
	}
}

// SwizzleWYWW returns a new vector with the components of this
// vector in the order of WYWW.
func (lhs Vec4u) SwizzleWYWW() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[1],
		lhs[3],
		lhs[3],
	}
}

// SwizzleWZXX returns a new vector with the components of this
// vector in the order of WZXX.
func (lhs Vec4u) SwizzleWZXX() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleWZXY returns a new vector with the components of this
// vector in the order of WZXY.
func (lhs Vec4u) SwizzleWZXY() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleWZXZ returns a new vector with the components of this
// vector in the order of WZXZ.
func (lhs Vec4u) SwizzleWZXZ() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleWZXW returns a new vector with the components of this
// vector in the order of WZXW.
func (lhs Vec4u) SwizzleWZXW() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[2],
		lhs[0],
		lhs[3],
	}
}

// SwizzleWZYX returns a new vector with the components of this
// vector in the order of WZYX.
func (lhs Vec4u) SwizzleWZYX() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleWZYY returns a new vector with the components of this
// vector in the order of WZYY.
func (lhs Vec4u) SwizzleWZYY() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleWZYZ returns a new vector with the components of this
// vector in the order of WZYZ.
func (lhs Vec4u) SwizzleWZYZ() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleWZYW returns a new vector with the components of this
// vector in the order of WZYW.
func (lhs Vec4u) SwizzleWZYW() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[2],
		lhs[1],
		lhs[3],
	}
}

// SwizzleWZZX returns a new vector with the components of this
// vector in the order of WZZX.
func (lhs Vec4u) SwizzleWZZX() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleWZZY returns a new vector with the components of this
// vector in the order of WZZY.
func (lhs Vec4u) SwizzleWZZY() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleWZZZ returns a new vector with the components of this
// vector in the order of WZZZ.
func (lhs Vec4u) SwizzleWZZZ() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

// SwizzleWZZW returns a new vector with the components of this
// vector in the order of WZZW.
func (lhs Vec4u) SwizzleWZZW() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[2],
		lhs[2],
		lhs[3],
	}
}

// SwizzleWZWX returns a new vector with the components of this
// vector in the order of WZWX.
func (lhs Vec4u) SwizzleWZWX() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[2],
		lhs[3],
		lhs[0],
	}
}

// SwizzleWZWY returns a new vector with the components of this
// vector in the order of WZWY.
func (lhs Vec4u) SwizzleWZWY() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[2],
		lhs[3],
		lhs[1],
	}
}

// SwizzleWZWZ returns a new vector with the components of this
// vector in the order of WZWZ.
func (lhs Vec4u) SwizzleWZWZ() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[2],
		lhs[3],
		lhs[2],
	}
}

// SwizzleWZWW returns a new vector with the components of this
// vector in the order of WZWW.
func (lhs Vec4u) SwizzleWZWW() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[2],
		lhs[3],
		lhs[3],
	}
}

// SwizzleWWXX returns a new vector with the components of this
// vector in the order of WWXX.
func (lhs Vec4u) SwizzleWWXX() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[3],
		lhs[0],
		lhs[0],
	}
}

// SwizzleWWXY returns a new vector with the components of this
// vector in the order of WWXY.
func (lhs Vec4u) SwizzleWWXY() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[3],
		lhs[0],
		lhs[1],
	}
}

// SwizzleWWXZ returns a new vector with the components of this
// vector in the order of WWXZ.
func (lhs Vec4u) SwizzleWWXZ() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[3],
		lhs[0],
		lhs[2],
	}
}

// SwizzleWWXW returns a new vector with the components of this
// vector in the order of WWXW.
func (lhs Vec4u) SwizzleWWXW() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[3],
		lhs[0],
		lhs[3],
	}
}

// SwizzleWWYX returns a new vector with the components of this
// vector in the order of WWYX.
func (lhs Vec4u) SwizzleWWYX() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[3],
		lhs[1],
		lhs[0],
	}
}

// SwizzleWWYY returns a new vector with the components of this
// vector in the order of WWYY.
func (lhs Vec4u) SwizzleWWYY() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[3],
		lhs[1],
		lhs[1],
	}
}

// SwizzleWWYZ returns a new vector with the components of this
// vector in the order of WWYZ.
func (lhs Vec4u) SwizzleWWYZ() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[3],
		lhs[1],
		lhs[2],
	}
}

// SwizzleWWYW returns a new vector with the components of this
// vector in the order of WWYW.
func (lhs Vec4u) SwizzleWWYW() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[3],
		lhs[1],
		lhs[3],
	}
}

// SwizzleWWZX returns a new vector with the components of this
// vector in the order of WWZX.
func (lhs Vec4u) SwizzleWWZX() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[3],
		lhs[2],
		lhs[0],
	}
}

// SwizzleWWZY returns a new vector with the components of this
// vector in the order of WWZY.
func (lhs Vec4u) SwizzleWWZY() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[3],
		lhs[2],
		lhs[1],
	}
}

// SwizzleWWZZ returns a new vector with the components of this
// vector in the order of WWZZ.
func (lhs Vec4u) SwizzleWWZZ() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[3],
		lhs[2],
		lhs[2],
	}
}

// SwizzleWWZW returns a new vector with the components of this
// vector in the order of WWZW.
func (lhs Vec4u) SwizzleWWZW() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[3],
		lhs[2],
		lhs[3],
	}
}

// SwizzleWWWX returns a new vector with the components of this
// vector in the order of WWWX.
func (lhs Vec4u) SwizzleWWWX() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[3],
		lhs[3],
		lhs[0],
	}
}

// SwizzleWWWY returns a new vector with the components of this
// vector in the order of WWWY.
func (lhs Vec4u) SwizzleWWWY() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[3],
		lhs[3],
		lhs[1],
	}
}

// SwizzleWWWZ returns a new vector with the components of this
// vector in the order of WWWZ.
func (lhs Vec4u) SwizzleWWWZ() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[3],
		lhs[3],
		lhs[2],
	}
}

// SwizzleWWWW returns a new vector with the components of this
// vector in the order of WWWW.
func (lhs Vec4u) SwizzleWWWW() Vec4u {
	return Vec4u{
		lhs[3],
		lhs[3],
		lhs[3],
		lhs[3],
	}
}

func (lhs Vec4u) XY() (x, y uint32) {
	x = lhs[0]
	y = lhs[1]
	return
}

func (lhs Vec4u) XYZ() (x, y, z uint32) {
	x = lhs[0]
	y = lhs[1]
	z = lhs[2]
	return
}

func (lhs Vec4u) XYZW() (x, y, z, w uint32) {
	x = lhs[0]
	y = lhs[1]
	z = lhs[2]
	w = lhs[3]
	return
}

func (lhs Vec4u) ToVec4f() Vec4f {
	return Vec4f{
		float32(lhs[0]),
		float32(lhs[1]),
		float32(lhs[2]),
		float32(lhs[3]),
	}
}

func (lhs Vec4u) ToWGPU() [4]float32 {
	return [4]float32{
		float32(lhs[0]),
		float32(lhs[1]),
		float32(lhs[2]),
		float32(lhs[3]),
	}
}

func (lhs Vec4u) String() string {
	return fmt.Sprintf(
		"vec4(%v, %v, %v, %v)",
		lhs[0],
		lhs[1],
		lhs[2],
		lhs[3],
	)
}
