// Code generated by generate.go: DO NOT EDIT.

package glm

import "unsafe"

type _ = unsafe.Pointer

// Mat3uh is a 3x3 matrix.
// The default value is filled with all zero values.
type Mat3uh [3][3]uint16

func IdentityMat3uh() Mat3uh {
	var m Mat3uh
	m[0][0] = 1
	m[1][1] = 1
	m[2][2] = 1
	return m
}

func (m Mat3uh) Mul(o Mat3uh) Mat3uh {
	mv := &m
	ov := &o

	return Mat3uh{
		{
			mv[0][0]*ov[0][0] + mv[1][0]*ov[0][1] + mv[2][0]*ov[0][2],
			mv[0][1]*ov[0][0] + mv[1][1]*ov[0][1] + mv[2][1]*ov[0][2],
			mv[0][2]*ov[0][0] + mv[1][2]*ov[0][1] + mv[2][2]*ov[0][2],
		},
		{
			mv[0][0]*ov[1][0] + mv[1][0]*ov[1][1] + mv[2][0]*ov[1][2],
			mv[0][1]*ov[1][0] + mv[1][1]*ov[1][1] + mv[2][1]*ov[1][2],
			mv[0][2]*ov[1][0] + mv[1][2]*ov[1][1] + mv[2][2]*ov[1][2],
		},
		{
			mv[0][0]*ov[2][0] + mv[1][0]*ov[2][1] + mv[2][0]*ov[2][2],
			mv[0][1]*ov[2][0] + mv[1][1]*ov[2][1] + mv[2][1]*ov[2][2],
			mv[0][2]*ov[2][0] + mv[1][2]*ov[2][1] + mv[2][2]*ov[2][2],
		},
	}
}

func (m Mat3uh) Transpose() Mat3uh {
	mv := &m

	return Mat3uh{
		{
			mv[0][0],
			mv[1][0],
			mv[2][0],
		},
		{
			mv[0][1],
			mv[1][1],
			mv[2][1],
		},
		{
			mv[0][2],
			mv[1][2],
			mv[2][2],
		},
	}
}

// Column returns a reference to the given column
func (m *Mat3uh) Column(idx int) Vec3uh {
	return *(*Vec3uh)(&m[idx])
}

func TranslationMat3uh(x, y uint16) Mat3uh {
	return Mat3uh{
		{1, 0, 0},
		{0, 1, 0},
		{x, y, 1},
	}
}

func ScaleMat3uh(x, y uint16) Mat3uh {
	var res Mat3uh
	res[0][0] = x
	res[1][1] = y
	res[2][2] = 1
	return res
}

func (m Mat3uh) Translate(x, y uint16) Mat3uh {
	return m.Mul(TranslationMat3uh(x, y))
}

func (m Mat3uh) Scale(x, y uint16) Mat3uh {
	return m.Mul(ScaleMat3uh(x, y))
}

func (m Mat3uh) Row(i int) Vec3uh {
	if i == 0 {
		return Vec3uh{
			m[0][0],
			m[1][0],
			m[2][0],
		}
	}
	if i == 1 {
		return Vec3uh{m[0][1], m[1][1], m[2][1]}
	}
	if i == 2 {
		return Vec3uh{
			m[0][2],
			m[1][2],
			m[2][2],
		}
	}

	panic(i)
}

func (m Mat3uh) Transform(vec Vec3uh) Vec3uh {
	return Vec3uh{
		(m[0][0])*vec[0] + (m[1][0])*vec[1] + (m[2][0])*vec[2],
		(m[0][1])*vec[0] + (m[1][1])*vec[1] + (m[2][1])*vec[2],
		(m[0][2])*vec[0] + (m[1][2])*vec[1] + (m[2][2])*vec[2],
	}
}

func (m Mat3uh) Transform2(vec Vec2uh) Vec2uh {
	return Vec2uh{
		(m[0][0])*vec[0] + (m[1][0])*vec[1] + (m[2][0]),
		(m[0][1])*vec[0] + (m[1][1])*vec[1] + (m[2][1]),
	}
}
