// Code generated by generate.go: DO NOT EDIT.

package glm

import "unsafe"

type _ = unsafe.Pointer

// Mat4u is a 4x4 matrix.
// The default value is filled with all zero values.
type Mat4u [4][4]uint32

func IdentityMat4u() Mat4u {
	var m Mat4u
	m[0][0] = 1
	m[1][1] = 1
	m[2][2] = 1
	m[3][3] = 1
	return m
}

func (m Mat4u) Mul(o Mat4u) Mat4u {
	mv := &m
	ov := &o

	return Mat4u{
		{
			mv[0][0]*ov[0][0] + mv[1][0]*ov[0][1] + mv[2][0]*ov[0][2] + mv[3][0]*ov[0][3],
			mv[0][1]*ov[0][0] + mv[1][1]*ov[0][1] + mv[2][1]*ov[0][2] + mv[3][1]*ov[0][3],
			mv[0][2]*ov[0][0] + mv[1][2]*ov[0][1] + mv[2][2]*ov[0][2] + mv[3][2]*ov[0][3],
			mv[0][3]*ov[0][0] + mv[1][3]*ov[0][1] + mv[2][3]*ov[0][2] + mv[3][3]*ov[0][3],
		},
		{
			mv[0][0]*ov[1][0] + mv[1][0]*ov[1][1] + mv[2][0]*ov[1][2] + mv[3][0]*ov[1][3],
			mv[0][1]*ov[1][0] + mv[1][1]*ov[1][1] + mv[2][1]*ov[1][2] + mv[3][1]*ov[1][3],
			mv[0][2]*ov[1][0] + mv[1][2]*ov[1][1] + mv[2][2]*ov[1][2] + mv[3][2]*ov[1][3],
			mv[0][3]*ov[1][0] + mv[1][3]*ov[1][1] + mv[2][3]*ov[1][2] + mv[3][3]*ov[1][3],
		},
		{
			mv[0][0]*ov[2][0] + mv[1][0]*ov[2][1] + mv[2][0]*ov[2][2] + mv[3][0]*ov[2][3],
			mv[0][1]*ov[2][0] + mv[1][1]*ov[2][1] + mv[2][1]*ov[2][2] + mv[3][1]*ov[2][3],
			mv[0][2]*ov[2][0] + mv[1][2]*ov[2][1] + mv[2][2]*ov[2][2] + mv[3][2]*ov[2][3],
			mv[0][3]*ov[2][0] + mv[1][3]*ov[2][1] + mv[2][3]*ov[2][2] + mv[3][3]*ov[2][3],
		},
		{
			mv[0][0]*ov[3][0] + mv[1][0]*ov[3][1] + mv[2][0]*ov[3][2] + mv[3][0]*ov[3][3],
			mv[0][1]*ov[3][0] + mv[1][1]*ov[3][1] + mv[2][1]*ov[3][2] + mv[3][1]*ov[3][3],
			mv[0][2]*ov[3][0] + mv[1][2]*ov[3][1] + mv[2][2]*ov[3][2] + mv[3][2]*ov[3][3],
			mv[0][3]*ov[3][0] + mv[1][3]*ov[3][1] + mv[2][3]*ov[3][2] + mv[3][3]*ov[3][3],
		},
	}
}

func (m Mat4u) Transpose() Mat4u {
	mv := &m

	return Mat4u{
		{
			mv[0][0],
			mv[1][0],
			mv[2][0],
			mv[3][0],
		},
		{
			mv[0][1],
			mv[1][1],
			mv[2][1],
			mv[3][1],
		},
		{
			mv[0][2],
			mv[1][2],
			mv[2][2],
			mv[3][2],
		},
		{
			mv[0][3],
			mv[1][3],
			mv[2][3],
			mv[3][3],
		},
	}
}

// Column returns a reference to the given column
func (m *Mat4u) Column(idx int) Vec4u {
	return *(*Vec4u)(&m[idx])
}

func TranslationMat4u(x, y, z uint32) Mat4u {
	return Mat4u{
		{1, 0, 0, 0},
		{0, 1, 0, 0},
		{0, 0, 1, 0},
		{x, y, z, 1},
	}
}

func ScaleMat4u(x, y, z uint32) Mat4u {
	var res Mat4u
	res[0][0] = x
	res[1][1] = y
	res[2][2] = z
	res[3][3] = 1
	return res
}

func (m Mat4u) Translate(x, y, z uint32) Mat4u {
	return m.Mul(TranslationMat4u(x, y, z))
}

func (m Mat4u) Scale(x, y, z uint32) Mat4u {
	return m.Mul(ScaleMat4u(x, y, z))
}

func (m Mat4u) Transform(vec Vec4u) Vec4u {
	return Vec4u{
		(m[0][0])*vec[0] + (m[1][0])*vec[1] + (m[2][0])*vec[2] + (m[3][0])*vec[3],
		(m[0][1])*vec[0] + (m[1][1])*vec[1] + (m[2][1])*vec[2] + (m[3][1])*vec[3],
		(m[0][2])*vec[0] + (m[1][2])*vec[1] + (m[2][2])*vec[2] + (m[3][2])*vec[3],
		(m[0][3])*vec[0] + (m[1][3])*vec[1] + (m[2][3])*vec[2] + (m[3][3])*vec[3],
	}
}

func (m Mat4u) Transform3(vec Vec3u) Vec3u {
	return Vec3u{
		(m[0][0])*vec[0] + (m[1][0])*vec[1] + (m[2][0] * vec[2]) + m[3][0],
		(m[0][1])*vec[0] + (m[1][1])*vec[1] + (m[2][1] * vec[2]) + m[3][1],
		(m[0][2])*vec[0] + (m[1][2])*vec[1] + (m[2][2] * vec[2]) + m[3][2],
	}
}

func (m Mat4u) Transform2(vec Vec2u) Vec2u {
	return Vec2u{
		(m[0][0])*vec[0] + (m[1][0])*vec[1] + m[3][0],
		(m[0][1])*vec[0] + (m[1][1])*vec[1] + m[3][1],
	}
}

func (m Mat4u) TranslateZ() uint32 {
	return m[3][2]
}
