// Code generated by generate.go: DO NOT EDIT.

package glm

import "fmt"
import "math"

// Vec2u is a vector of dimension 2.
type Vec2u [2]uint32

func (lhs Vec2u) Dot(rhs Vec2u) uint32 {
	return lhs[0]*rhs[0] + lhs[1]*rhs[1]
}

func (lhs Vec2u) LengthSqr() uint32 {
	return lhs.Dot(lhs)
}

func (lhs Vec2u) Length() uint32 {
	return uint32(math.Sqrt(float64(lhs.Dot(lhs))))
}

func (lhs Vec2u) Normalize() Vec2u {
	return lhs.Scale(1.0 / lhs.Length())
}

func (lhs Vec2u) Scale(s uint32) Vec2u {
	return Vec2u{
		lhs[0] * s,
		lhs[1] * s,
	}
}

func (lhs Vec2u) Reciprocal() Vec2u {
	return Vec2u{
		1.0 / lhs[0],
		1.0 / lhs[1],
	}
}

func (lhs Vec2u) Add(rhs Vec2u) Vec2u {
	return Vec2u{
		lhs[0] + rhs[0],
		lhs[1] + rhs[1],
	}
}

func (lhs Vec2u) Sub(rhs Vec2u) Vec2u {
	return Vec2u{
		lhs[0] - rhs[0],
		lhs[1] - rhs[1],
	}
}

func (lhs Vec2u) Mul(rhs Vec2u) Vec2u {
	return Vec2u{
		lhs[0] * rhs[0],
		lhs[1] * rhs[1],
	}
}

func (lhs Vec2u) Div(rhs Vec2u) Vec2u {
	return Vec2u{
		lhs[0] / rhs[0],
		lhs[1] / rhs[1],
	}
}

func (lhs Vec2u) Min(rhs Vec2u) Vec2u {
	return Vec2u{
		min(lhs[0], rhs[0]),
		min(lhs[1], rhs[1]),
	}
}

func (lhs Vec2u) Max(rhs Vec2u) Vec2u {
	return Vec2u{
		max(lhs[0], rhs[0]),
		max(lhs[1], rhs[1]),
	}
}

func (lhs Vec2u) Extend(z uint32) Vec3u {
	return Vec3u{
		lhs[0],
		lhs[1],
		z,
	}
}

// SwizzleXX returns a new vector with the components of this
// vector in the order of XX.
func (lhs Vec2u) SwizzleXX() Vec2u {
	return Vec2u{
		lhs[0],
		lhs[0],
	}
}

// SwizzleXY returns a new vector with the components of this
// vector in the order of XY.
func (lhs Vec2u) SwizzleXY() Vec2u {
	return Vec2u{
		lhs[0],
		lhs[1],
	}
}

// SwizzleYX returns a new vector with the components of this
// vector in the order of YX.
func (lhs Vec2u) SwizzleYX() Vec2u {
	return Vec2u{
		lhs[1],
		lhs[0],
	}
}

// SwizzleYY returns a new vector with the components of this
// vector in the order of YY.
func (lhs Vec2u) SwizzleYY() Vec2u {
	return Vec2u{
		lhs[1],
		lhs[1],
	}
}

func (lhs Vec2u) XY() (x, y uint32) {
	x = lhs[0]
	y = lhs[1]
	return
}

func (lhs Vec2u) ToVec2f() Vec2f {
	return Vec2f{
		float32(lhs[0]),
		float32(lhs[1]),
	}
}

func (lhs Vec2u) ToWGPU() [2]float32 {
	return [2]float32{
		float32(lhs[0]),
		float32(lhs[1]),
	}
}

func (lhs Vec2u) String() string {
	return fmt.Sprintf(
		"vec2(%v, %v)",
		lhs[0],
		lhs[1],
	)
}
