// Code generated by generate.go: DO NOT EDIT.

package glm

import (
	"fmt"
)

type Rectf struct {
	Min Vec2f
	Max Vec2f
}

func RectfFromSize(pos Vec2f, size Vec2f) Rectf {
	return RectfFromPoints(pos, pos.Add(size))
}

func RectfFromXYWH(x, y, w, h float32) Rectf {
	pos := Vec2f{x, y}
	size := Vec2f{w, h}
	return RectfFromSize(pos, size)
}

func RectfFromPoints(a, b Vec2f) Rectf {
	return Rectf{
		Min: Vec2f{
			min(a[0], b[0]),
			min(a[1], b[1]),
		},
		Max: Vec2f{
			max(a[0], b[0]),
			max(a[1], b[1]),
		},
	}
}

func (r Rectf) Extend(point Vec2f) Rectf {
	minX := min(r.Min[0], point[0])
	minY := min(r.Min[1], point[1])

	maxX := max(r.Max[0], point[0])
	maxY := max(r.Max[1], point[1])

	return Rectf{
		Min: Vec2f{minX, minY},
		Max: Vec2f{maxX, maxY},
	}
}

func (r Rectf) Union(other Rectf) Rectf {
	return r.Extend(other.Min).Extend(other.Max)
}

func (r Rectf) Contains(other Rectf) bool {
	return r.Min[0] <= other.Min[0] && r.Min[1] <= other.Min[1] &&
		r.Max[0] >= other.Max[0] && r.Max[1] >= other.Max[1]
}

func (r Rectf) Center() Vec2f {
	return r.Min.Add(r.Max).Div(Vec2f{2, 2})
}

func (r Rectf) Offset() Vec2f {
	return r.Min
}

func (r Rectf) Size() Vec2f {
	return r.Max.Sub(r.Min)
}

func (r Rectf) Width() float32 {
	return r.Max[0] - r.Min[0]
}

func (r Rectf) Height() float32 {
	return r.Max[1] - r.Min[1]
}

func (r Rectf) XYWH() (float32, float32, float32, float32) {
	x, y := r.Min.XY()
	w, h := r.Size().XY()
	return x, y, w, h
}

func (r Rectf) String() string {
	x, y, w, h := r.XYWH()
	return fmt.Sprintf("Rect(x=%v, y=%v, w=%v, h=%v)", x, y, w, h)
}
