// Code generated by generate.go: DO NOT EDIT.

package glm

import "fmt"
import "math"

// Vec3u is a vector of dimension 3.
type Vec3u [3]uint32

func (lhs Vec3u) Dot(rhs Vec3u) uint32 {
	return lhs[0]*rhs[0] + lhs[1]*rhs[1] + lhs[2]*rhs[2]
}

func (lhs Vec3u) LengthSqr() uint32 {
	return lhs.Dot(lhs)
}

func (lhs Vec3u) Length() uint32 {
	return uint32(math.Sqrt(float64(lhs.Dot(lhs))))
}

func (lhs Vec3u) Normalize() Vec3u {
	return lhs.Scale(1.0 / lhs.Length())
}

func (lhs Vec3u) Scale(s uint32) Vec3u {
	return Vec3u{
		lhs[0] * s,
		lhs[1] * s,
		lhs[2] * s,
	}
}

func (lhs Vec3u) Reciprocal() Vec3u {
	return Vec3u{
		1.0 / lhs[0],
		1.0 / lhs[1],
		1.0 / lhs[2],
	}
}

func (lhs Vec3u) Add(rhs Vec3u) Vec3u {
	return Vec3u{
		lhs[0] + rhs[0],
		lhs[1] + rhs[1],
		lhs[2] + rhs[2],
	}
}

func (lhs Vec3u) Sub(rhs Vec3u) Vec3u {
	return Vec3u{
		lhs[0] - rhs[0],
		lhs[1] - rhs[1],
		lhs[2] - rhs[2],
	}
}

func (lhs Vec3u) Mul(rhs Vec3u) Vec3u {
	return Vec3u{
		lhs[0] * rhs[0],
		lhs[1] * rhs[1],
		lhs[2] * rhs[2],
	}
}

func (lhs Vec3u) Div(rhs Vec3u) Vec3u {
	return Vec3u{
		lhs[0] / rhs[0],
		lhs[1] / rhs[1],
		lhs[2] / rhs[2],
	}
}

func (lhs Vec3u) Min(rhs Vec3u) Vec3u {
	return Vec3u{
		min(lhs[0], rhs[0]),
		min(lhs[1], rhs[1]),
		min(lhs[2], rhs[2]),
	}
}

func (lhs Vec3u) Max(rhs Vec3u) Vec3u {
	return Vec3u{
		max(lhs[0], rhs[0]),
		max(lhs[1], rhs[1]),
		max(lhs[2], rhs[2]),
	}
}

func (lhs Vec3u) Extend(w uint32) Vec4u {
	return Vec4u{
		lhs[0],
		lhs[1],
		lhs[2],
		w,
	}
}

func (lhs Vec3u) Truncate() Vec2u {
	return Vec2u{
		lhs[0],
		lhs[1],
	}
}

// SwizzleXX returns a new vector with the components of this
// vector in the order of XX.
func (lhs Vec3u) SwizzleXX() Vec2u {
	return Vec2u{
		lhs[0],
		lhs[0],
	}
}

// SwizzleXY returns a new vector with the components of this
// vector in the order of XY.
func (lhs Vec3u) SwizzleXY() Vec2u {
	return Vec2u{
		lhs[0],
		lhs[1],
	}
}

// SwizzleXZ returns a new vector with the components of this
// vector in the order of XZ.
func (lhs Vec3u) SwizzleXZ() Vec2u {
	return Vec2u{
		lhs[0],
		lhs[2],
	}
}

// SwizzleYX returns a new vector with the components of this
// vector in the order of YX.
func (lhs Vec3u) SwizzleYX() Vec2u {
	return Vec2u{
		lhs[1],
		lhs[0],
	}
}

// SwizzleYY returns a new vector with the components of this
// vector in the order of YY.
func (lhs Vec3u) SwizzleYY() Vec2u {
	return Vec2u{
		lhs[1],
		lhs[1],
	}
}

// SwizzleYZ returns a new vector with the components of this
// vector in the order of YZ.
func (lhs Vec3u) SwizzleYZ() Vec2u {
	return Vec2u{
		lhs[1],
		lhs[2],
	}
}

// SwizzleZX returns a new vector with the components of this
// vector in the order of ZX.
func (lhs Vec3u) SwizzleZX() Vec2u {
	return Vec2u{
		lhs[2],
		lhs[0],
	}
}

// SwizzleZY returns a new vector with the components of this
// vector in the order of ZY.
func (lhs Vec3u) SwizzleZY() Vec2u {
	return Vec2u{
		lhs[2],
		lhs[1],
	}
}

// SwizzleZZ returns a new vector with the components of this
// vector in the order of ZZ.
func (lhs Vec3u) SwizzleZZ() Vec2u {
	return Vec2u{
		lhs[2],
		lhs[2],
	}
}

// SwizzleXXX returns a new vector with the components of this
// vector in the order of XXX.
func (lhs Vec3u) SwizzleXXX() Vec3u {
	return Vec3u{
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXXY returns a new vector with the components of this
// vector in the order of XXY.
func (lhs Vec3u) SwizzleXXY() Vec3u {
	return Vec3u{
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXXZ returns a new vector with the components of this
// vector in the order of XXZ.
func (lhs Vec3u) SwizzleXXZ() Vec3u {
	return Vec3u{
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXYX returns a new vector with the components of this
// vector in the order of XYX.
func (lhs Vec3u) SwizzleXYX() Vec3u {
	return Vec3u{
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXYY returns a new vector with the components of this
// vector in the order of XYY.
func (lhs Vec3u) SwizzleXYY() Vec3u {
	return Vec3u{
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXYZ returns a new vector with the components of this
// vector in the order of XYZ.
func (lhs Vec3u) SwizzleXYZ() Vec3u {
	return Vec3u{
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXZX returns a new vector with the components of this
// vector in the order of XZX.
func (lhs Vec3u) SwizzleXZX() Vec3u {
	return Vec3u{
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXZY returns a new vector with the components of this
// vector in the order of XZY.
func (lhs Vec3u) SwizzleXZY() Vec3u {
	return Vec3u{
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXZZ returns a new vector with the components of this
// vector in the order of XZZ.
func (lhs Vec3u) SwizzleXZZ() Vec3u {
	return Vec3u{
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYXX returns a new vector with the components of this
// vector in the order of YXX.
func (lhs Vec3u) SwizzleYXX() Vec3u {
	return Vec3u{
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYXY returns a new vector with the components of this
// vector in the order of YXY.
func (lhs Vec3u) SwizzleYXY() Vec3u {
	return Vec3u{
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYXZ returns a new vector with the components of this
// vector in the order of YXZ.
func (lhs Vec3u) SwizzleYXZ() Vec3u {
	return Vec3u{
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYYX returns a new vector with the components of this
// vector in the order of YYX.
func (lhs Vec3u) SwizzleYYX() Vec3u {
	return Vec3u{
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYYY returns a new vector with the components of this
// vector in the order of YYY.
func (lhs Vec3u) SwizzleYYY() Vec3u {
	return Vec3u{
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYYZ returns a new vector with the components of this
// vector in the order of YYZ.
func (lhs Vec3u) SwizzleYYZ() Vec3u {
	return Vec3u{
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYZX returns a new vector with the components of this
// vector in the order of YZX.
func (lhs Vec3u) SwizzleYZX() Vec3u {
	return Vec3u{
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYZY returns a new vector with the components of this
// vector in the order of YZY.
func (lhs Vec3u) SwizzleYZY() Vec3u {
	return Vec3u{
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYZZ returns a new vector with the components of this
// vector in the order of YZZ.
func (lhs Vec3u) SwizzleYZZ() Vec3u {
	return Vec3u{
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZXX returns a new vector with the components of this
// vector in the order of ZXX.
func (lhs Vec3u) SwizzleZXX() Vec3u {
	return Vec3u{
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZXY returns a new vector with the components of this
// vector in the order of ZXY.
func (lhs Vec3u) SwizzleZXY() Vec3u {
	return Vec3u{
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZXZ returns a new vector with the components of this
// vector in the order of ZXZ.
func (lhs Vec3u) SwizzleZXZ() Vec3u {
	return Vec3u{
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZYX returns a new vector with the components of this
// vector in the order of ZYX.
func (lhs Vec3u) SwizzleZYX() Vec3u {
	return Vec3u{
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZYY returns a new vector with the components of this
// vector in the order of ZYY.
func (lhs Vec3u) SwizzleZYY() Vec3u {
	return Vec3u{
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZYZ returns a new vector with the components of this
// vector in the order of ZYZ.
func (lhs Vec3u) SwizzleZYZ() Vec3u {
	return Vec3u{
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZZX returns a new vector with the components of this
// vector in the order of ZZX.
func (lhs Vec3u) SwizzleZZX() Vec3u {
	return Vec3u{
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZZY returns a new vector with the components of this
// vector in the order of ZZY.
func (lhs Vec3u) SwizzleZZY() Vec3u {
	return Vec3u{
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZZZ returns a new vector with the components of this
// vector in the order of ZZZ.
func (lhs Vec3u) SwizzleZZZ() Vec3u {
	return Vec3u{
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

func (lhs Vec3u) XY() (x, y uint32) {
	x = lhs[0]
	y = lhs[1]
	return
}

func (lhs Vec3u) XYZ() (x, y, z uint32) {
	x = lhs[0]
	y = lhs[1]
	z = lhs[2]
	return
}

func (lhs Vec3u) ToVec3f() Vec3f {
	return Vec3f{
		float32(lhs[0]),
		float32(lhs[1]),
		float32(lhs[2]),
	}
}

func (lhs Vec3u) ToWGPU() [4]float32 {
	return [4]float32{
		float32(lhs[0]),
		float32(lhs[1]),
		float32(lhs[2]),
	}
}

func (lhs Vec3u) String() string {
	return fmt.Sprintf(
		"vec3(%v, %v, %v)",
		lhs[0],
		lhs[1],
		lhs[2],
	)
}
