// Code generated by generate.go: DO NOT EDIT.

package glm

// Mat3uh is a 3x3 matrix.
// The default value is the identity matrix.
type Mat3uh struct {
	values [3][3]uint16
}

func Mat3uhOf(values [3][3]uint16) Mat3uh {
	return Mat3uh{
		values: [3][3]uint16{
			{
				values[0][0] - 1,
				values[0][1],
				values[0][2],
			},
			{
				values[1][0],
				values[1][1] - 1,
				values[1][2],
			},
			{
				values[2][0],
				values[2][1],
				values[2][2] - 1,
			},
		},
	}
}

func IdentityMat3uh() Mat3uh {
	return Mat3uh{}
}

func (m Mat3uh) Mul(o Mat3uh) Mat3uh {
	mv := &m.values
	ov := &o.values

	return Mat3uh{
		values: [3][3]uint16{
			{
				(mv[0][0]+1)*(ov[0][0]+1) + mv[1][0]*ov[0][1] + mv[2][0]*ov[0][2] - 1,
				mv[0][1]*(ov[0][0]+1) + (mv[1][1]+1)*ov[0][1] + mv[2][1]*ov[0][2],
				mv[0][2]*(ov[0][0]+1) + mv[1][2]*ov[0][1] + (mv[2][2]+1)*ov[0][2],
			},
			{
				(mv[0][0]+1)*ov[1][0] + mv[1][0]*(ov[1][1]+1) + mv[2][0]*ov[1][2],
				mv[0][1]*ov[1][0] + (mv[1][1]+1)*(ov[1][1]+1) + mv[2][1]*ov[1][2] - 1,
				mv[0][2]*ov[1][0] + mv[1][2]*(ov[1][1]+1) + (mv[2][2]+1)*ov[1][2],
			},
			{
				(mv[0][0]+1)*ov[2][0] + mv[1][0]*ov[2][1] + mv[2][0]*(ov[2][2]+1),
				mv[0][1]*ov[2][0] + (mv[1][1]+1)*ov[2][1] + mv[2][1]*(ov[2][2]+1),
				mv[0][2]*ov[2][0] + mv[1][2]*ov[2][1] + (mv[2][2]+1)*(ov[2][2]+1) - 1,
			},
		},
	}
}

func (m Mat3uh) Transpose() Mat3uh {
	mv := &m.values

	return Mat3uh{
		values: [3][3]uint16{
			{
				mv[0][0],
				mv[1][0],
				mv[2][0],
			},
			{
				mv[0][1],
				mv[1][1],
				mv[2][1],
			},
			{
				mv[0][2],
				mv[1][2],
				mv[2][2],
			},
		},
	}
}

func (m Mat3uh) Components() [3][3]uint16 {
	values := m.values
	values[0][0] += 1
	values[1][1] += 1
	values[2][2] += 1
	return values
}

func (m *Mat3uh) m00() uint16 {
	return (m.values[0][0] + 1)
}

func (m *Mat3uh) m01() uint16 {
	return m.values[0][1]
}

func (m *Mat3uh) m02() uint16 {
	return m.values[0][2]
}

func (m *Mat3uh) m10() uint16 {
	return m.values[1][0]
}

func (m *Mat3uh) m11() uint16 {
	return (m.values[1][1] + 1)
}

func (m *Mat3uh) m12() uint16 {
	return m.values[1][2]
}

func (m *Mat3uh) m20() uint16 {
	return m.values[2][0]
}

func (m *Mat3uh) m21() uint16 {
	return m.values[2][1]
}

func (m *Mat3uh) m22() uint16 {
	return (m.values[2][2] + 1)
}

func TranslationMat3uh(x, y uint16) Mat3uh {
	return Mat3uhOf([3][3]uint16{
		{1, 0, 0},
		{0, 1, 0},
		{x, y, 1},
	})
}

func ScaleMat3uh(x, y uint16) Mat3uh {
	return Mat3uhOf([3][3]uint16{
		{x, 0, 0},
		{0, y, 0},
		{0, 0, 1},
	})
}

func (m Mat3uh) Translate(x, y uint16) Mat3uh {
	return m.Mul(TranslationMat3uh(x, y))
}

func (m Mat3uh) Scale(x, y uint16) Mat3uh {
	return m.Mul(ScaleMat3uh(x, y))
}

func (m Mat3uh) Row(i int) Vec3uh {
	if i == 0 {
		return Vec3uh{
			m.m00(),
			m.m10(),
			m.m20(),
		}
	}
	if i == 1 {
		return Vec3uh{m.m01(), m.m11(), m.m21()}
	}
	if i == 2 {
		return Vec3uh{
			m.m02(),
			m.m12(),
			m.m22(),
		}
	}

	panic(i)
}

func (m Mat3uh) ToWGPU() [12]float32 {
	return [12]float32{
		float32(m.m00()), float32(m.m01()), float32(m.m02()), 0,
		float32(m.m10()), float32(m.m11()), float32(m.m12()), 0,
		float32(m.m20()), float32(m.m21()), float32(m.m22()), 0,
	}
}

func (m Mat3uh) Transform(vec Vec3uh) Vec3uh {
	return Vec3uh{
		(m.m00())*vec[0] + (m.m10())*vec[1] + (m.m20())*vec[2],
		(m.m01())*vec[0] + (m.m11())*vec[1] + (m.m21())*vec[2],
		(m.m02())*vec[0] + (m.m12())*vec[1] + (m.m22())*vec[2],
	}
}

func (m Mat3uh) Transform2(vec Vec2uh) Vec2uh {
	return Vec2uh{
		(m.m00())*vec[0] + (m.m10())*vec[1] + (m.m20()),
		(m.m01())*vec[0] + (m.m11())*vec[1] + (m.m21()),
	}
}
