// Code generated by generate.go: DO NOT EDIT.

package glm

import "unsafe"

type _ = unsafe.Pointer

// Mat2f is a 2x2 matrix.
// The default value is filled with all zero values.
type Mat2f [2][2]float32

func IdentityMat2f() Mat2f {
	var m Mat2f
	m[0][0] = 1
	m[1][1] = 1
	return m
}

func (m Mat2f) Mul(o Mat2f) Mat2f {
	mv := &m
	ov := &o

	return Mat2f{
		{
			mv[0][0]*ov[0][0] + mv[1][0]*ov[0][1],
			mv[0][1]*ov[0][0] + mv[1][1]*ov[0][1],
		},
		{
			mv[0][0]*ov[1][0] + mv[1][0]*ov[1][1],
			mv[0][1]*ov[1][0] + mv[1][1]*ov[1][1],
		},
	}
}

func (m Mat2f) Transpose() Mat2f {
	mv := &m

	return Mat2f{
		{
			mv[0][0],
			mv[1][0],
		},
		{
			mv[0][1],
			mv[1][1],
		},
	}
}

// Column returns a reference to the given column
func (m *Mat2f) Column(idx int) Vec2f {
	return *(*Vec2f)(&m[idx])
}
