// Code generated by generate.go: DO NOT EDIT.

package glm

import "unsafe"

type _ = unsafe.Pointer

// Mat3f is a 3x3 matrix.
// The default value is filled with all zero values.
type Mat3f [3][3]float32

func IdentityMat3f() Mat3f {
	var m Mat3f
	m[0][0] = 1
	m[1][1] = 1
	m[2][2] = 1
	return m
}

func (m Mat3f) Mul(o Mat3f) Mat3f {
	mv := &m
	ov := &o

	return Mat3f{
		{
			mv[0][0]*ov[0][0] + mv[1][0]*ov[0][1] + mv[2][0]*ov[0][2],
			mv[0][1]*ov[0][0] + mv[1][1]*ov[0][1] + mv[2][1]*ov[0][2],
			mv[0][2]*ov[0][0] + mv[1][2]*ov[0][1] + mv[2][2]*ov[0][2],
		},
		{
			mv[0][0]*ov[1][0] + mv[1][0]*ov[1][1] + mv[2][0]*ov[1][2],
			mv[0][1]*ov[1][0] + mv[1][1]*ov[1][1] + mv[2][1]*ov[1][2],
			mv[0][2]*ov[1][0] + mv[1][2]*ov[1][1] + mv[2][2]*ov[1][2],
		},
		{
			mv[0][0]*ov[2][0] + mv[1][0]*ov[2][1] + mv[2][0]*ov[2][2],
			mv[0][1]*ov[2][0] + mv[1][1]*ov[2][1] + mv[2][1]*ov[2][2],
			mv[0][2]*ov[2][0] + mv[1][2]*ov[2][1] + mv[2][2]*ov[2][2],
		},
	}
}

func (m Mat3f) Transpose() Mat3f {
	mv := &m

	return Mat3f{
		{
			mv[0][0],
			mv[1][0],
			mv[2][0],
		},
		{
			mv[0][1],
			mv[1][1],
			mv[2][1],
		},
		{
			mv[0][2],
			mv[1][2],
			mv[2][2],
		},
	}
}

// Column returns a reference to the given column
func (m *Mat3f) Column(idx int) Vec3f {
	return *(*Vec3f)(&m[idx])
}

func TranslationMat3f(x, y float32) Mat3f {
	return Mat3f{
		{1, 0, 0},
		{0, 1, 0},
		{x, y, 1},
	}
}

func ScaleMat3f(x, y float32) Mat3f {
	var res Mat3f
	res[0][0] = x
	res[1][1] = y
	res[2][2] = 1
	return res
}

func (m Mat3f) Translate(x, y float32) Mat3f {
	return m.Mul(TranslationMat3f(x, y))
}

func (m Mat3f) Scale(x, y float32) Mat3f {
	return m.Mul(ScaleMat3f(x, y))
}

func RotationMat3f(angle Rad) Mat3f {
	s, c := fastSincos(angle)

	return Mat3f{
		{float32(c), float32(s), 0},
		{-float32(s), float32(c), 0},
		{0, 0, 1},
	}
}

func (m Mat3f) Rotate(angle Rad) Mat3f {
	return m.Mul(RotationMat3f(angle))
}

func (m Mat3f) Row(i int) Vec3f {
	if i == 0 {
		return Vec3f{
			m[0][0],
			m[1][0],
			m[2][0],
		}
	}
	if i == 1 {
		return Vec3f{m[0][1], m[1][1], m[2][1]}
	}
	if i == 2 {
		return Vec3f{
			m[0][2],
			m[1][2],
			m[2][2],
		}
	}

	panic(i)
}

func (m Mat3f) Invert() Mat3f {
	inv, ok := m.TryInvert()
	if !ok {
		panic("matrix not invertible")
	}

	return inv
}

func (m Mat3f) TryInvert() (Mat3f, bool) {
	var inv Mat3f

	// determinant
	det := m[0][0]*(m[1][1]*m[2][2]-m[1][2]*m[2][1]) -
		m[0][1]*(m[1][0]*m[2][2]-m[1][2]*m[2][0]) +
		m[0][2]*(m[1][0]*m[2][1]-m[1][1]*m[2][0])

	if det == 0 {
		// singular
		return Mat3f{}, false
	}

	inv[0][0] = (m[1][1]*m[2][2] - m[1][2]*m[2][1]) / det
	inv[0][1] = (m[0][2]*m[2][1] - m[0][1]*m[2][2]) / det
	inv[0][2] = (m[0][1]*m[1][2] - m[0][2]*m[1][1]) / det

	inv[1][0] = (m[1][2]*m[2][0] - m[1][0]*m[2][2]) / det
	inv[1][1] = (m[0][0]*m[2][2] - m[0][2]*m[2][0]) / det
	inv[1][2] = (m[0][2]*m[1][0] - m[0][0]*m[1][2]) / det

	inv[2][0] = (m[1][0]*m[2][1] - m[1][1]*m[2][0]) / det
	inv[2][1] = (m[0][1]*m[2][0] - m[0][0]*m[2][1]) / det
	inv[2][2] = (m[0][0]*m[1][1] - m[0][1]*m[1][0]) / det

	return inv, true
}

func (m Mat3f) Transform(vec Vec3f) Vec3f {
	return Vec3f{
		(m[0][0])*vec[0] + (m[1][0])*vec[1] + (m[2][0])*vec[2],
		(m[0][1])*vec[0] + (m[1][1])*vec[1] + (m[2][1])*vec[2],
		(m[0][2])*vec[0] + (m[1][2])*vec[1] + (m[2][2])*vec[2],
	}
}

func (m Mat3f) Transform2(vec Vec2f) Vec2f {
	return Vec2f{
		(m[0][0])*vec[0] + (m[1][0])*vec[1] + (m[2][0]),
		(m[0][1])*vec[0] + (m[1][1])*vec[1] + (m[2][1]),
	}
}
