// Code generated by generate.go: DO NOT EDIT.

package glm

import "fmt"
import "math"

// Vec3uh is a vector of dimension 3.
type Vec3uh [3]uint16

func (lhs Vec3uh) Dot(rhs Vec3uh) uint16 {
	return lhs[0]*rhs[0] + lhs[1]*rhs[1] + lhs[2]*rhs[2]
}

func (lhs Vec3uh) LengthSqr() uint16 {
	return lhs.Dot(lhs)
}

func (lhs Vec3uh) Length() uint16 {
	return uint16(math.Sqrt(float64(lhs.Dot(lhs))))
}

func (lhs Vec3uh) Normalize() Vec3uh {
	return lhs.Scale(1.0 / lhs.Length())
}

func (lhs Vec3uh) Scale(s uint16) Vec3uh {
	return Vec3uh{
		lhs[0] * s,
		lhs[1] * s,
		lhs[2] * s,
	}
}

func (lhs Vec3uh) Reciprocal() Vec3uh {
	return Vec3uh{
		1.0 / lhs[0],
		1.0 / lhs[1],
		1.0 / lhs[2],
	}
}

func (lhs Vec3uh) Add(rhs Vec3uh) Vec3uh {
	return Vec3uh{
		lhs[0] + rhs[0],
		lhs[1] + rhs[1],
		lhs[2] + rhs[2],
	}
}

func (lhs Vec3uh) Sub(rhs Vec3uh) Vec3uh {
	return Vec3uh{
		lhs[0] - rhs[0],
		lhs[1] - rhs[1],
		lhs[2] - rhs[2],
	}
}

func (lhs Vec3uh) Mul(rhs Vec3uh) Vec3uh {
	return Vec3uh{
		lhs[0] * rhs[0],
		lhs[1] * rhs[1],
		lhs[2] * rhs[2],
	}
}

func (lhs Vec3uh) Div(rhs Vec3uh) Vec3uh {
	return Vec3uh{
		lhs[0] / rhs[0],
		lhs[1] / rhs[1],
		lhs[2] / rhs[2],
	}
}

func (lhs Vec3uh) Min(rhs Vec3uh) Vec3uh {
	return Vec3uh{
		min(lhs[0], rhs[0]),
		min(lhs[1], rhs[1]),
		min(lhs[2], rhs[2]),
	}
}

func (lhs Vec3uh) Max(rhs Vec3uh) Vec3uh {
	return Vec3uh{
		max(lhs[0], rhs[0]),
		max(lhs[1], rhs[1]),
		max(lhs[2], rhs[2]),
	}
}

func (lhs Vec3uh) Extend(w uint16) Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[1],
		lhs[2],
		w,
	}
}

func (lhs Vec3uh) Truncate() Vec2uh {
	return Vec2uh{
		lhs[0],
		lhs[1],
	}
}

// SwizzleXX returns a new vector with the components of this
// vector in the order of XX.
func (lhs Vec3uh) SwizzleXX() Vec2uh {
	return Vec2uh{
		lhs[0],
		lhs[0],
	}
}

// SwizzleXY returns a new vector with the components of this
// vector in the order of XY.
func (lhs Vec3uh) SwizzleXY() Vec2uh {
	return Vec2uh{
		lhs[0],
		lhs[1],
	}
}

// SwizzleXZ returns a new vector with the components of this
// vector in the order of XZ.
func (lhs Vec3uh) SwizzleXZ() Vec2uh {
	return Vec2uh{
		lhs[0],
		lhs[2],
	}
}

// SwizzleYX returns a new vector with the components of this
// vector in the order of YX.
func (lhs Vec3uh) SwizzleYX() Vec2uh {
	return Vec2uh{
		lhs[1],
		lhs[0],
	}
}

// SwizzleYY returns a new vector with the components of this
// vector in the order of YY.
func (lhs Vec3uh) SwizzleYY() Vec2uh {
	return Vec2uh{
		lhs[1],
		lhs[1],
	}
}

// SwizzleYZ returns a new vector with the components of this
// vector in the order of YZ.
func (lhs Vec3uh) SwizzleYZ() Vec2uh {
	return Vec2uh{
		lhs[1],
		lhs[2],
	}
}

// SwizzleZX returns a new vector with the components of this
// vector in the order of ZX.
func (lhs Vec3uh) SwizzleZX() Vec2uh {
	return Vec2uh{
		lhs[2],
		lhs[0],
	}
}

// SwizzleZY returns a new vector with the components of this
// vector in the order of ZY.
func (lhs Vec3uh) SwizzleZY() Vec2uh {
	return Vec2uh{
		lhs[2],
		lhs[1],
	}
}

// SwizzleZZ returns a new vector with the components of this
// vector in the order of ZZ.
func (lhs Vec3uh) SwizzleZZ() Vec2uh {
	return Vec2uh{
		lhs[2],
		lhs[2],
	}
}

// SwizzleXXX returns a new vector with the components of this
// vector in the order of XXX.
func (lhs Vec3uh) SwizzleXXX() Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXXY returns a new vector with the components of this
// vector in the order of XXY.
func (lhs Vec3uh) SwizzleXXY() Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXXZ returns a new vector with the components of this
// vector in the order of XXZ.
func (lhs Vec3uh) SwizzleXXZ() Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXYX returns a new vector with the components of this
// vector in the order of XYX.
func (lhs Vec3uh) SwizzleXYX() Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXYY returns a new vector with the components of this
// vector in the order of XYY.
func (lhs Vec3uh) SwizzleXYY() Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXYZ returns a new vector with the components of this
// vector in the order of XYZ.
func (lhs Vec3uh) SwizzleXYZ() Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXZX returns a new vector with the components of this
// vector in the order of XZX.
func (lhs Vec3uh) SwizzleXZX() Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXZY returns a new vector with the components of this
// vector in the order of XZY.
func (lhs Vec3uh) SwizzleXZY() Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXZZ returns a new vector with the components of this
// vector in the order of XZZ.
func (lhs Vec3uh) SwizzleXZZ() Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYXX returns a new vector with the components of this
// vector in the order of YXX.
func (lhs Vec3uh) SwizzleYXX() Vec3uh {
	return Vec3uh{
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYXY returns a new vector with the components of this
// vector in the order of YXY.
func (lhs Vec3uh) SwizzleYXY() Vec3uh {
	return Vec3uh{
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYXZ returns a new vector with the components of this
// vector in the order of YXZ.
func (lhs Vec3uh) SwizzleYXZ() Vec3uh {
	return Vec3uh{
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYYX returns a new vector with the components of this
// vector in the order of YYX.
func (lhs Vec3uh) SwizzleYYX() Vec3uh {
	return Vec3uh{
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYYY returns a new vector with the components of this
// vector in the order of YYY.
func (lhs Vec3uh) SwizzleYYY() Vec3uh {
	return Vec3uh{
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYYZ returns a new vector with the components of this
// vector in the order of YYZ.
func (lhs Vec3uh) SwizzleYYZ() Vec3uh {
	return Vec3uh{
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYZX returns a new vector with the components of this
// vector in the order of YZX.
func (lhs Vec3uh) SwizzleYZX() Vec3uh {
	return Vec3uh{
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYZY returns a new vector with the components of this
// vector in the order of YZY.
func (lhs Vec3uh) SwizzleYZY() Vec3uh {
	return Vec3uh{
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYZZ returns a new vector with the components of this
// vector in the order of YZZ.
func (lhs Vec3uh) SwizzleYZZ() Vec3uh {
	return Vec3uh{
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZXX returns a new vector with the components of this
// vector in the order of ZXX.
func (lhs Vec3uh) SwizzleZXX() Vec3uh {
	return Vec3uh{
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZXY returns a new vector with the components of this
// vector in the order of ZXY.
func (lhs Vec3uh) SwizzleZXY() Vec3uh {
	return Vec3uh{
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZXZ returns a new vector with the components of this
// vector in the order of ZXZ.
func (lhs Vec3uh) SwizzleZXZ() Vec3uh {
	return Vec3uh{
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZYX returns a new vector with the components of this
// vector in the order of ZYX.
func (lhs Vec3uh) SwizzleZYX() Vec3uh {
	return Vec3uh{
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZYY returns a new vector with the components of this
// vector in the order of ZYY.
func (lhs Vec3uh) SwizzleZYY() Vec3uh {
	return Vec3uh{
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZYZ returns a new vector with the components of this
// vector in the order of ZYZ.
func (lhs Vec3uh) SwizzleZYZ() Vec3uh {
	return Vec3uh{
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZZX returns a new vector with the components of this
// vector in the order of ZZX.
func (lhs Vec3uh) SwizzleZZX() Vec3uh {
	return Vec3uh{
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZZY returns a new vector with the components of this
// vector in the order of ZZY.
func (lhs Vec3uh) SwizzleZZY() Vec3uh {
	return Vec3uh{
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZZZ returns a new vector with the components of this
// vector in the order of ZZZ.
func (lhs Vec3uh) SwizzleZZZ() Vec3uh {
	return Vec3uh{
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

func (lhs Vec3uh) XY() (x, y uint16) {
	x = lhs[0]
	y = lhs[1]
	return
}

func (lhs Vec3uh) XYZ() (x, y, z uint16) {
	x = lhs[0]
	y = lhs[1]
	z = lhs[2]
	return
}

func (lhs Vec3uh) ToVec3f() Vec3f {
	return Vec3f{
		float32(lhs[0]),
		float32(lhs[1]),
		float32(lhs[2]),
	}
}

func (lhs Vec3uh) ToWGPU() [4]float32 {
	return [4]float32{
		float32(lhs[0]),
		float32(lhs[1]),
		float32(lhs[2]),
	}
}

func (lhs Vec3uh) String() string {
	return fmt.Sprintf(
		"vec3(%v, %v, %v)",
		lhs[0],
		lhs[1],
		lhs[2],
	)
}
