// Code generated by generate.go: DO NOT EDIT.

package glm

import "unsafe"

type _ = unsafe.Pointer

// Mat3d is a 3x3 matrix.
// The default value is filled with all zero values.
type Mat3d [3][3]float64

func IdentityMat3d() Mat3d {
	var m Mat3d
	m[0][0] = 1
	m[1][1] = 1
	m[2][2] = 1
	return m
}

func (m Mat3d) Mul(o Mat3d) Mat3d {
	mv := &m
	ov := &o

	return Mat3d{
		{
			mv[0][0]*ov[0][0] + mv[1][0]*ov[0][1] + mv[2][0]*ov[0][2],
			mv[0][1]*ov[0][0] + mv[1][1]*ov[0][1] + mv[2][1]*ov[0][2],
			mv[0][2]*ov[0][0] + mv[1][2]*ov[0][1] + mv[2][2]*ov[0][2],
		},
		{
			mv[0][0]*ov[1][0] + mv[1][0]*ov[1][1] + mv[2][0]*ov[1][2],
			mv[0][1]*ov[1][0] + mv[1][1]*ov[1][1] + mv[2][1]*ov[1][2],
			mv[0][2]*ov[1][0] + mv[1][2]*ov[1][1] + mv[2][2]*ov[1][2],
		},
		{
			mv[0][0]*ov[2][0] + mv[1][0]*ov[2][1] + mv[2][0]*ov[2][2],
			mv[0][1]*ov[2][0] + mv[1][1]*ov[2][1] + mv[2][1]*ov[2][2],
			mv[0][2]*ov[2][0] + mv[1][2]*ov[2][1] + mv[2][2]*ov[2][2],
		},
	}
}

func (m Mat3d) Transpose() Mat3d {
	mv := &m

	return Mat3d{
		{
			mv[0][0],
			mv[1][0],
			mv[2][0],
		},
		{
			mv[0][1],
			mv[1][1],
			mv[2][1],
		},
		{
			mv[0][2],
			mv[1][2],
			mv[2][2],
		},
	}
}

// Column returns a reference to the given column
func (m *Mat3d) Column(idx int) Vec3d {
	return *(*Vec3d)(&m[idx])
}

func TranslationMat3d(x, y float64) Mat3d {
	return Mat3d{
		{1, 0, 0},
		{0, 1, 0},
		{x, y, 1},
	}
}

func ScaleMat3d(x, y float64) Mat3d {
	var res Mat3d
	res[0][0] = x
	res[1][1] = y
	res[2][2] = 1
	return res
}

func (m Mat3d) Translate(x, y float64) Mat3d {
	return m.Mul(TranslationMat3d(x, y))
}

func (m Mat3d) Scale(x, y float64) Mat3d {
	return m.Mul(ScaleMat3d(x, y))
}

func RotationMat3d(angle Rad) Mat3d {
	s, c := fastSincos(angle)

	return Mat3d{
		{float64(c), float64(s), 0},
		{-float64(s), float64(c), 0},
		{0, 0, 1},
	}
}

func (m Mat3d) Rotate(angle Rad) Mat3d {
	return m.Mul(RotationMat3d(angle))
}

func (m Mat3d) Row(i int) Vec3d {
	if i == 0 {
		return Vec3d{
			m[0][0],
			m[1][0],
			m[2][0],
		}
	}
	if i == 1 {
		return Vec3d{m[0][1], m[1][1], m[2][1]}
	}
	if i == 2 {
		return Vec3d{
			m[0][2],
			m[1][2],
			m[2][2],
		}
	}

	panic(i)
}

func (m Mat3d) Invert() Mat3d {
	inv, ok := m.TryInvert()
	if !ok {
		panic("matrix not invertible")
	}

	return inv
}

func (m Mat3d) TryInvert() (Mat3d, bool) {
	var inv Mat3d

	// determinant
	det := m[0][0]*(m[1][1]*m[2][2]-m[1][2]*m[2][1]) -
		m[0][1]*(m[1][0]*m[2][2]-m[1][2]*m[2][0]) +
		m[0][2]*(m[1][0]*m[2][1]-m[1][1]*m[2][0])

	if det == 0 {
		// singular
		return Mat3d{}, false
	}

	inv[0][0] = (m[1][1]*m[2][2] - m[1][2]*m[2][1]) / det
	inv[0][1] = (m[0][2]*m[2][1] - m[0][1]*m[2][2]) / det
	inv[0][2] = (m[0][1]*m[1][2] - m[0][2]*m[1][1]) / det

	inv[1][0] = (m[1][2]*m[2][0] - m[1][0]*m[2][2]) / det
	inv[1][1] = (m[0][0]*m[2][2] - m[0][2]*m[2][0]) / det
	inv[1][2] = (m[0][2]*m[1][0] - m[0][0]*m[1][2]) / det

	inv[2][0] = (m[1][0]*m[2][1] - m[1][1]*m[2][0]) / det
	inv[2][1] = (m[0][1]*m[2][0] - m[0][0]*m[2][1]) / det
	inv[2][2] = (m[0][0]*m[1][1] - m[0][1]*m[1][0]) / det

	return inv, true
}

func (m Mat3d) Transform(vec Vec3d) Vec3d {
	return Vec3d{
		(m[0][0])*vec[0] + (m[1][0])*vec[1] + (m[2][0])*vec[2],
		(m[0][1])*vec[0] + (m[1][1])*vec[1] + (m[2][1])*vec[2],
		(m[0][2])*vec[0] + (m[1][2])*vec[1] + (m[2][2])*vec[2],
	}
}

func (m Mat3d) Transform2(vec Vec2d) Vec2d {
	return Vec2d{
		(m[0][0])*vec[0] + (m[1][0])*vec[1] + (m[2][0]),
		(m[0][1])*vec[0] + (m[1][1])*vec[1] + (m[2][1]),
	}
}
