// Code generated by generate.go: DO NOT EDIT.

package glm

import "fmt"
import "math"

// Vec2d is a vector of dimension 2.
type Vec2d [2]float64

func (lhs Vec2d) Dot(rhs Vec2d) float64 {
	return lhs[0]*rhs[0] + lhs[1]*rhs[1]
}

func (lhs Vec2d) LengthSqr() float64 {
	return lhs.Dot(lhs)
}

func (lhs Vec2d) Length() float64 {
	return float64(math.Sqrt(float64(lhs.Dot(lhs))))
}

func (lhs Vec2d) Normalize() Vec2d {
	return lhs.Scale(1.0 / lhs.Length())
}

func (lhs Vec2d) Scale(s float64) Vec2d {
	return Vec2d{
		lhs[0] * s,
		lhs[1] * s,
	}
}

func (lhs Vec2d) Reciprocal() Vec2d {
	return Vec2d{
		1.0 / lhs[0],
		1.0 / lhs[1],
	}
}

func (lhs Vec2d) Add(rhs Vec2d) Vec2d {
	return Vec2d{
		lhs[0] + rhs[0],
		lhs[1] + rhs[1],
	}
}

func (lhs Vec2d) Sub(rhs Vec2d) Vec2d {
	return Vec2d{
		lhs[0] - rhs[0],
		lhs[1] - rhs[1],
	}
}

func (lhs Vec2d) Mul(rhs Vec2d) Vec2d {
	return Vec2d{
		lhs[0] * rhs[0],
		lhs[1] * rhs[1],
	}
}

func (lhs Vec2d) Div(rhs Vec2d) Vec2d {
	return Vec2d{
		lhs[0] / rhs[0],
		lhs[1] / rhs[1],
	}
}

func (lhs Vec2d) Min(rhs Vec2d) Vec2d {
	return Vec2d{
		min(lhs[0], rhs[0]),
		min(lhs[1], rhs[1]),
	}
}

func (lhs Vec2d) Max(rhs Vec2d) Vec2d {
	return Vec2d{
		max(lhs[0], rhs[0]),
		max(lhs[1], rhs[1]),
	}
}

func (lhs Vec2d) Extend(z float64) Vec3d {
	return Vec3d{
		lhs[0],
		lhs[1],
		z,
	}
}

// SwizzleXX returns a new vector with the components of this
// vector in the order of XX.
func (lhs Vec2d) SwizzleXX() Vec2d {
	return Vec2d{
		lhs[0],
		lhs[0],
	}
}

// SwizzleXY returns a new vector with the components of this
// vector in the order of XY.
func (lhs Vec2d) SwizzleXY() Vec2d {
	return Vec2d{
		lhs[0],
		lhs[1],
	}
}

// SwizzleYX returns a new vector with the components of this
// vector in the order of YX.
func (lhs Vec2d) SwizzleYX() Vec2d {
	return Vec2d{
		lhs[1],
		lhs[0],
	}
}

// SwizzleYY returns a new vector with the components of this
// vector in the order of YY.
func (lhs Vec2d) SwizzleYY() Vec2d {
	return Vec2d{
		lhs[1],
		lhs[1],
	}
}

func (lhs Vec2d) XY() (x, y float64) {
	x = lhs[0]
	y = lhs[1]
	return
}

func (lhs Vec2d) ToVec2f() Vec2f {
	return Vec2f{
		float32(lhs[0]),
		float32(lhs[1]),
	}
}

func (lhs Vec2d) ToWGPU() [2]float32 {
	return [2]float32{
		float32(lhs[0]),
		float32(lhs[1]),
	}
}

func (lhs Vec2d) String() string {
	return fmt.Sprintf(
		"vec2(%v, %v)",
		lhs[0],
		lhs[1],
	)
}
