// Code generated by generate.go: DO NOT EDIT.

package glm

// Mat2d is a 2x2 matrix.
// The default value is the identity matrix.
type Mat2d struct {
	values [2][2]float64
}

func Mat2dOf(values [2][2]float64) Mat2d {
	return Mat2d{
		values: [2][2]float64{
			{
				values[0][0] - 1,
				values[0][1],
			},
			{
				values[1][0],
				values[1][1] - 1,
			},
		},
	}
}

func IdentityMat2d() Mat2d {
	return Mat2d{}
}

func (m Mat2d) Mul(o Mat2d) Mat2d {
	mv := &m.values
	ov := &o.values

	return Mat2d{
		values: [2][2]float64{
			{
				(mv[0][0]+1)*(ov[0][0]+1) + mv[1][0]*ov[0][1] - 1,
				mv[0][1]*(ov[0][0]+1) + (mv[1][1]+1)*ov[0][1],
			},
			{
				(mv[0][0]+1)*ov[1][0] + mv[1][0]*(ov[1][1]+1),
				mv[0][1]*ov[1][0] + (mv[1][1]+1)*(ov[1][1]+1) - 1,
			},
		},
	}
}

func (m Mat2d) Transpose() Mat2d {
	mv := &m.values

	return Mat2d{
		values: [2][2]float64{
			{
				mv[0][0],
				mv[1][0],
			},
			{
				mv[0][1],
				mv[1][1],
			},
		},
	}
}

func (m Mat2d) Components() [2][2]float64 {
	values := m.values
	values[0][0] += 1
	values[1][1] += 1
	return values
}

func (m *Mat2d) m00() float64 {
	return (m.values[0][0] + 1)
}

func (m *Mat2d) m01() float64 {
	return m.values[0][1]
}

func (m *Mat2d) m10() float64 {
	return m.values[1][0]
}

func (m *Mat2d) m11() float64 {
	return (m.values[1][1] + 1)
}
