// Code generated by generate.go: DO NOT EDIT.

package glm

import (
	"fmt"
)

type Rectuh struct {
	Min Vec2uh
	Max Vec2uh
}

func RectuhFromSize(pos Vec2uh, size Vec2uh) Rectuh {
	return RectuhFromPoints(pos, pos.Add(size))
}

func RectuhFromXYWH(x, y, w, h uint16) Rectuh {
	pos := Vec2uh{x, y}
	size := Vec2uh{w, h}
	return RectuhFromSize(pos, size)
}

func RectuhFromPoints(a, b Vec2uh) Rectuh {
	return Rectuh{
		Min: Vec2uh{
			min(a[0], b[0]),
			min(a[1], b[1]),
		},
		Max: Vec2uh{
			max(a[0], b[0]),
			max(a[1], b[1]),
		},
	}
}

func (r Rectuh) Extend(point Vec2uh) Rectuh {
	minX := min(r.Min[0], point[0])
	minY := min(r.Min[1], point[1])

	maxX := max(r.Max[0], point[0])
	maxY := max(r.Max[1], point[1])

	return Rectuh{
		Min: Vec2uh{minX, minY},
		Max: Vec2uh{maxX, maxY},
	}
}

func (r Rectuh) Union(other Rectuh) Rectuh {
	return r.Extend(other.Min).Extend(other.Max)
}

func (r Rectuh) Contains(other Rectuh) bool {
	return r.Min[0] <= other.Min[0] && r.Min[1] <= other.Min[1] &&
		r.Max[0] >= other.Max[0] && r.Max[1] >= other.Max[1]
}

func (r Rectuh) Center() Vec2uh {
	return r.Min.Add(r.Max).Div(Vec2uh{2, 2})
}

func (r Rectuh) Offset() Vec2uh {
	return r.Min
}

func (r Rectuh) Size() Vec2uh {
	return r.Max.Sub(r.Min)
}

func (r Rectuh) Width() uint16 {
	return r.Max[0] - r.Min[0]
}

func (r Rectuh) Height() uint16 {
	return r.Max[1] - r.Min[1]
}

func (r Rectuh) XYWH() (uint16, uint16, uint16, uint16) {
	x, y := r.Min.XY()
	w, h := r.Size().XY()
	return x, y, w, h
}

func (r Rectuh) String() string {
	x, y, w, h := r.XYWH()
	return fmt.Sprintf("Rect(x=%v, y=%v, w=%v, h=%v)", x, y, w, h)
}
