// Code generated by generate.go: DO NOT EDIT.

package glm

import "unsafe"

type _ = unsafe.Pointer

// Mat3u is a 3x3 matrix.
// The default value is filled with all zero values.
type Mat3u [3][3]uint32

func IdentityMat3u() Mat3u {
	var m Mat3u
	m[0][0] = 1
	m[1][1] = 1
	m[2][2] = 1
	return m
}

func (m Mat3u) Mul(o Mat3u) Mat3u {
	mv := &m
	ov := &o

	return Mat3u{
		{
			mv[0][0]*ov[0][0] + mv[1][0]*ov[0][1] + mv[2][0]*ov[0][2],
			mv[0][1]*ov[0][0] + mv[1][1]*ov[0][1] + mv[2][1]*ov[0][2],
			mv[0][2]*ov[0][0] + mv[1][2]*ov[0][1] + mv[2][2]*ov[0][2],
		},
		{
			mv[0][0]*ov[1][0] + mv[1][0]*ov[1][1] + mv[2][0]*ov[1][2],
			mv[0][1]*ov[1][0] + mv[1][1]*ov[1][1] + mv[2][1]*ov[1][2],
			mv[0][2]*ov[1][0] + mv[1][2]*ov[1][1] + mv[2][2]*ov[1][2],
		},
		{
			mv[0][0]*ov[2][0] + mv[1][0]*ov[2][1] + mv[2][0]*ov[2][2],
			mv[0][1]*ov[2][0] + mv[1][1]*ov[2][1] + mv[2][1]*ov[2][2],
			mv[0][2]*ov[2][0] + mv[1][2]*ov[2][1] + mv[2][2]*ov[2][2],
		},
	}
}

func (m Mat3u) Transpose() Mat3u {
	mv := &m

	return Mat3u{
		{
			mv[0][0],
			mv[1][0],
			mv[2][0],
		},
		{
			mv[0][1],
			mv[1][1],
			mv[2][1],
		},
		{
			mv[0][2],
			mv[1][2],
			mv[2][2],
		},
	}
}

// Column returns a reference to the given column
func (m *Mat3u) Column(idx int) Vec3u {
	return *(*Vec3u)(&m[idx])
}

func TranslationMat3u(x, y uint32) Mat3u {
	return Mat3u{
		{1, 0, 0},
		{0, 1, 0},
		{x, y, 1},
	}
}

func ScaleMat3u(x, y uint32) Mat3u {
	var res Mat3u
	res[0][0] = x
	res[1][1] = y
	res[2][2] = 1
	return res
}

func (m Mat3u) Translate(x, y uint32) Mat3u {
	return m.Mul(TranslationMat3u(x, y))
}

func (m Mat3u) Scale(x, y uint32) Mat3u {
	return m.Mul(ScaleMat3u(x, y))
}

func (m Mat3u) Row(i int) Vec3u {
	if i == 0 {
		return Vec3u{
			m[0][0],
			m[1][0],
			m[2][0],
		}
	}
	if i == 1 {
		return Vec3u{m[0][1], m[1][1], m[2][1]}
	}
	if i == 2 {
		return Vec3u{
			m[0][2],
			m[1][2],
			m[2][2],
		}
	}

	panic(i)
}

func (m Mat3u) Transform(vec Vec3u) Vec3u {
	return Vec3u{
		(m[0][0])*vec[0] + (m[1][0])*vec[1] + (m[2][0])*vec[2],
		(m[0][1])*vec[0] + (m[1][1])*vec[1] + (m[2][1])*vec[2],
		(m[0][2])*vec[0] + (m[1][2])*vec[1] + (m[2][2])*vec[2],
	}
}

func (m Mat3u) Transform2(vec Vec2u) Vec2u {
	return Vec2u{
		(m[0][0])*vec[0] + (m[1][0])*vec[1] + (m[2][0]),
		(m[0][1])*vec[0] + (m[1][1])*vec[1] + (m[2][1]),
	}
}
