// Code generated by generate.go: DO NOT EDIT.

package glm

import "fmt"
import "math"

// Vec2f is a vector of dimension 2.
type Vec2f [2]float32

func (lhs Vec2f) Dot(rhs Vec2f) float32 {
	return lhs[0]*rhs[0] + lhs[1]*rhs[1]
}

func (lhs Vec2f) LengthSqr() float32 {
	return lhs.Dot(lhs)
}

func (lhs Vec2f) Length() float32 {
	return float32(math.Sqrt(float64(lhs.Dot(lhs))))
}

func (lhs Vec2f) Normalize() Vec2f {
	return lhs.Scale(1.0 / lhs.Length())
}

func (lhs Vec2f) Scale(s float32) Vec2f {
	return Vec2f{
		lhs[0] * s,
		lhs[1] * s,
	}
}

func (lhs Vec2f) Reciprocal() Vec2f {
	return Vec2f{
		1.0 / lhs[0],
		1.0 / lhs[1],
	}
}

func (lhs Vec2f) Add(rhs Vec2f) Vec2f {
	return Vec2f{
		lhs[0] + rhs[0],
		lhs[1] + rhs[1],
	}
}

func (lhs Vec2f) Sub(rhs Vec2f) Vec2f {
	return Vec2f{
		lhs[0] - rhs[0],
		lhs[1] - rhs[1],
	}
}

func (lhs Vec2f) Mul(rhs Vec2f) Vec2f {
	return Vec2f{
		lhs[0] * rhs[0],
		lhs[1] * rhs[1],
	}
}

func (lhs Vec2f) Div(rhs Vec2f) Vec2f {
	return Vec2f{
		lhs[0] / rhs[0],
		lhs[1] / rhs[1],
	}
}

func (lhs Vec2f) Min(rhs Vec2f) Vec2f {
	return Vec2f{
		min(lhs[0], rhs[0]),
		min(lhs[1], rhs[1]),
	}
}

func (lhs Vec2f) Max(rhs Vec2f) Vec2f {
	return Vec2f{
		max(lhs[0], rhs[0]),
		max(lhs[1], rhs[1]),
	}
}

func (lhs Vec2f) Extend(z float32) Vec3f {
	return Vec3f{
		lhs[0],
		lhs[1],
		z,
	}
}

// SwizzleXX returns a new vector with the components of this
// vector in the order of XX.
func (lhs Vec2f) SwizzleXX() Vec2f {
	return Vec2f{
		lhs[0],
		lhs[0],
	}
}

// SwizzleXY returns a new vector with the components of this
// vector in the order of XY.
func (lhs Vec2f) SwizzleXY() Vec2f {
	return Vec2f{
		lhs[0],
		lhs[1],
	}
}

// SwizzleYX returns a new vector with the components of this
// vector in the order of YX.
func (lhs Vec2f) SwizzleYX() Vec2f {
	return Vec2f{
		lhs[1],
		lhs[0],
	}
}

// SwizzleYY returns a new vector with the components of this
// vector in the order of YY.
func (lhs Vec2f) SwizzleYY() Vec2f {
	return Vec2f{
		lhs[1],
		lhs[1],
	}
}

func (lhs Vec2f) XY() (x, y float32) {
	x = lhs[0]
	y = lhs[1]
	return
}

func (lhs Vec2f) ToVec2f() Vec2f {
	return Vec2f{
		float32(lhs[0]),
		float32(lhs[1]),
	}
}

func (lhs Vec2f) ToWGPU() [2]float32 {
	return [2]float32{
		float32(lhs[0]),
		float32(lhs[1]),
	}
}

func (lhs Vec2f) String() string {
	return fmt.Sprintf(
		"vec2(%v, %v)",
		lhs[0],
		lhs[1],
	)
}
