// Code generated by generate.go: DO NOT EDIT.

package glm

import "fmt"
import "math"

// Vec4f is a vector of dimension 4.
type Vec4f [4]float32

func (lhs Vec4f) Dot(rhs Vec4f) float32 {
	return lhs[0]*rhs[0] + lhs[1]*rhs[1] + lhs[2]*rhs[2] + lhs[3]*rhs[3]
}

func (lhs Vec4f) LengthSqr() float32 {
	return lhs.Dot(lhs)
}

func (lhs Vec4f) Length() float32 {
	return float32(math.Sqrt(float64(lhs.Dot(lhs))))
}

func (lhs Vec4f) Normalize() Vec4f {
	return lhs.Scale(1.0 / lhs.Length())
}

func (lhs Vec4f) Scale(s float32) Vec4f {
	return Vec4f{
		lhs[0] * s,
		lhs[1] * s,
		lhs[2] * s,
		lhs[3] * s,
	}
}

func (lhs Vec4f) Reciprocal() Vec4f {
	return Vec4f{
		1.0 / lhs[0],
		1.0 / lhs[1],
		1.0 / lhs[2],
		1.0 / lhs[3],
	}
}

func (lhs Vec4f) Add(rhs Vec4f) Vec4f {
	return Vec4f{
		lhs[0] + rhs[0],
		lhs[1] + rhs[1],
		lhs[2] + rhs[2],
		lhs[3] + rhs[3],
	}
}

func (lhs Vec4f) Sub(rhs Vec4f) Vec4f {
	return Vec4f{
		lhs[0] - rhs[0],
		lhs[1] - rhs[1],
		lhs[2] - rhs[2],
		lhs[3] - rhs[3],
	}
}

func (lhs Vec4f) Mul(rhs Vec4f) Vec4f {
	return Vec4f{
		lhs[0] * rhs[0],
		lhs[1] * rhs[1],
		lhs[2] * rhs[2],
		lhs[3] * rhs[3],
	}
}

func (lhs Vec4f) Div(rhs Vec4f) Vec4f {
	return Vec4f{
		lhs[0] / rhs[0],
		lhs[1] / rhs[1],
		lhs[2] / rhs[2],
		lhs[3] / rhs[3],
	}
}

func (lhs Vec4f) Min(rhs Vec4f) Vec4f {
	return Vec4f{
		min(lhs[0], rhs[0]),
		min(lhs[1], rhs[1]),
		min(lhs[2], rhs[2]),
		min(lhs[3], rhs[3]),
	}
}

func (lhs Vec4f) Max(rhs Vec4f) Vec4f {
	return Vec4f{
		max(lhs[0], rhs[0]),
		max(lhs[1], rhs[1]),
		max(lhs[2], rhs[2]),
		max(lhs[3], rhs[3]),
	}
}

func (lhs Vec4f) Truncate() Vec3f {
	return Vec3f{
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXX returns a new vector with the components of this
// vector in the order of XX.
func (lhs Vec4f) SwizzleXX() Vec2f {
	return Vec2f{
		lhs[0],
		lhs[0],
	}
}

// SwizzleXY returns a new vector with the components of this
// vector in the order of XY.
func (lhs Vec4f) SwizzleXY() Vec2f {
	return Vec2f{
		lhs[0],
		lhs[1],
	}
}

// SwizzleXZ returns a new vector with the components of this
// vector in the order of XZ.
func (lhs Vec4f) SwizzleXZ() Vec2f {
	return Vec2f{
		lhs[0],
		lhs[2],
	}
}

// SwizzleXW returns a new vector with the components of this
// vector in the order of XW.
func (lhs Vec4f) SwizzleXW() Vec2f {
	return Vec2f{
		lhs[0],
		lhs[3],
	}
}

// SwizzleYX returns a new vector with the components of this
// vector in the order of YX.
func (lhs Vec4f) SwizzleYX() Vec2f {
	return Vec2f{
		lhs[1],
		lhs[0],
	}
}

// SwizzleYY returns a new vector with the components of this
// vector in the order of YY.
func (lhs Vec4f) SwizzleYY() Vec2f {
	return Vec2f{
		lhs[1],
		lhs[1],
	}
}

// SwizzleYZ returns a new vector with the components of this
// vector in the order of YZ.
func (lhs Vec4f) SwizzleYZ() Vec2f {
	return Vec2f{
		lhs[1],
		lhs[2],
	}
}

// SwizzleYW returns a new vector with the components of this
// vector in the order of YW.
func (lhs Vec4f) SwizzleYW() Vec2f {
	return Vec2f{
		lhs[1],
		lhs[3],
	}
}

// SwizzleZX returns a new vector with the components of this
// vector in the order of ZX.
func (lhs Vec4f) SwizzleZX() Vec2f {
	return Vec2f{
		lhs[2],
		lhs[0],
	}
}

// SwizzleZY returns a new vector with the components of this
// vector in the order of ZY.
func (lhs Vec4f) SwizzleZY() Vec2f {
	return Vec2f{
		lhs[2],
		lhs[1],
	}
}

// SwizzleZZ returns a new vector with the components of this
// vector in the order of ZZ.
func (lhs Vec4f) SwizzleZZ() Vec2f {
	return Vec2f{
		lhs[2],
		lhs[2],
	}
}

// SwizzleZW returns a new vector with the components of this
// vector in the order of ZW.
func (lhs Vec4f) SwizzleZW() Vec2f {
	return Vec2f{
		lhs[2],
		lhs[3],
	}
}

// SwizzleWX returns a new vector with the components of this
// vector in the order of WX.
func (lhs Vec4f) SwizzleWX() Vec2f {
	return Vec2f{
		lhs[3],
		lhs[0],
	}
}

// SwizzleWY returns a new vector with the components of this
// vector in the order of WY.
func (lhs Vec4f) SwizzleWY() Vec2f {
	return Vec2f{
		lhs[3],
		lhs[1],
	}
}

// SwizzleWZ returns a new vector with the components of this
// vector in the order of WZ.
func (lhs Vec4f) SwizzleWZ() Vec2f {
	return Vec2f{
		lhs[3],
		lhs[2],
	}
}

// SwizzleWW returns a new vector with the components of this
// vector in the order of WW.
func (lhs Vec4f) SwizzleWW() Vec2f {
	return Vec2f{
		lhs[3],
		lhs[3],
	}
}

// SwizzleXXX returns a new vector with the components of this
// vector in the order of XXX.
func (lhs Vec4f) SwizzleXXX() Vec3f {
	return Vec3f{
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXXY returns a new vector with the components of this
// vector in the order of XXY.
func (lhs Vec4f) SwizzleXXY() Vec3f {
	return Vec3f{
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXXZ returns a new vector with the components of this
// vector in the order of XXZ.
func (lhs Vec4f) SwizzleXXZ() Vec3f {
	return Vec3f{
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXXW returns a new vector with the components of this
// vector in the order of XXW.
func (lhs Vec4f) SwizzleXXW() Vec3f {
	return Vec3f{
		lhs[0],
		lhs[0],
		lhs[3],
	}
}

// SwizzleXYX returns a new vector with the components of this
// vector in the order of XYX.
func (lhs Vec4f) SwizzleXYX() Vec3f {
	return Vec3f{
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXYY returns a new vector with the components of this
// vector in the order of XYY.
func (lhs Vec4f) SwizzleXYY() Vec3f {
	return Vec3f{
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXYZ returns a new vector with the components of this
// vector in the order of XYZ.
func (lhs Vec4f) SwizzleXYZ() Vec3f {
	return Vec3f{
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXYW returns a new vector with the components of this
// vector in the order of XYW.
func (lhs Vec4f) SwizzleXYW() Vec3f {
	return Vec3f{
		lhs[0],
		lhs[1],
		lhs[3],
	}
}

// SwizzleXZX returns a new vector with the components of this
// vector in the order of XZX.
func (lhs Vec4f) SwizzleXZX() Vec3f {
	return Vec3f{
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXZY returns a new vector with the components of this
// vector in the order of XZY.
func (lhs Vec4f) SwizzleXZY() Vec3f {
	return Vec3f{
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXZZ returns a new vector with the components of this
// vector in the order of XZZ.
func (lhs Vec4f) SwizzleXZZ() Vec3f {
	return Vec3f{
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleXZW returns a new vector with the components of this
// vector in the order of XZW.
func (lhs Vec4f) SwizzleXZW() Vec3f {
	return Vec3f{
		lhs[0],
		lhs[2],
		lhs[3],
	}
}

// SwizzleXWX returns a new vector with the components of this
// vector in the order of XWX.
func (lhs Vec4f) SwizzleXWX() Vec3f {
	return Vec3f{
		lhs[0],
		lhs[3],
		lhs[0],
	}
}

// SwizzleXWY returns a new vector with the components of this
// vector in the order of XWY.
func (lhs Vec4f) SwizzleXWY() Vec3f {
	return Vec3f{
		lhs[0],
		lhs[3],
		lhs[1],
	}
}

// SwizzleXWZ returns a new vector with the components of this
// vector in the order of XWZ.
func (lhs Vec4f) SwizzleXWZ() Vec3f {
	return Vec3f{
		lhs[0],
		lhs[3],
		lhs[2],
	}
}

// SwizzleXWW returns a new vector with the components of this
// vector in the order of XWW.
func (lhs Vec4f) SwizzleXWW() Vec3f {
	return Vec3f{
		lhs[0],
		lhs[3],
		lhs[3],
	}
}

// SwizzleYXX returns a new vector with the components of this
// vector in the order of YXX.
func (lhs Vec4f) SwizzleYXX() Vec3f {
	return Vec3f{
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYXY returns a new vector with the components of this
// vector in the order of YXY.
func (lhs Vec4f) SwizzleYXY() Vec3f {
	return Vec3f{
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYXZ returns a new vector with the components of this
// vector in the order of YXZ.
func (lhs Vec4f) SwizzleYXZ() Vec3f {
	return Vec3f{
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYXW returns a new vector with the components of this
// vector in the order of YXW.
func (lhs Vec4f) SwizzleYXW() Vec3f {
	return Vec3f{
		lhs[1],
		lhs[0],
		lhs[3],
	}
}

// SwizzleYYX returns a new vector with the components of this
// vector in the order of YYX.
func (lhs Vec4f) SwizzleYYX() Vec3f {
	return Vec3f{
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYYY returns a new vector with the components of this
// vector in the order of YYY.
func (lhs Vec4f) SwizzleYYY() Vec3f {
	return Vec3f{
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYYZ returns a new vector with the components of this
// vector in the order of YYZ.
func (lhs Vec4f) SwizzleYYZ() Vec3f {
	return Vec3f{
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYYW returns a new vector with the components of this
// vector in the order of YYW.
func (lhs Vec4f) SwizzleYYW() Vec3f {
	return Vec3f{
		lhs[1],
		lhs[1],
		lhs[3],
	}
}

// SwizzleYZX returns a new vector with the components of this
// vector in the order of YZX.
func (lhs Vec4f) SwizzleYZX() Vec3f {
	return Vec3f{
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYZY returns a new vector with the components of this
// vector in the order of YZY.
func (lhs Vec4f) SwizzleYZY() Vec3f {
	return Vec3f{
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYZZ returns a new vector with the components of this
// vector in the order of YZZ.
func (lhs Vec4f) SwizzleYZZ() Vec3f {
	return Vec3f{
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYZW returns a new vector with the components of this
// vector in the order of YZW.
func (lhs Vec4f) SwizzleYZW() Vec3f {
	return Vec3f{
		lhs[1],
		lhs[2],
		lhs[3],
	}
}

// SwizzleYWX returns a new vector with the components of this
// vector in the order of YWX.
func (lhs Vec4f) SwizzleYWX() Vec3f {
	return Vec3f{
		lhs[1],
		lhs[3],
		lhs[0],
	}
}

// SwizzleYWY returns a new vector with the components of this
// vector in the order of YWY.
func (lhs Vec4f) SwizzleYWY() Vec3f {
	return Vec3f{
		lhs[1],
		lhs[3],
		lhs[1],
	}
}

// SwizzleYWZ returns a new vector with the components of this
// vector in the order of YWZ.
func (lhs Vec4f) SwizzleYWZ() Vec3f {
	return Vec3f{
		lhs[1],
		lhs[3],
		lhs[2],
	}
}

// SwizzleYWW returns a new vector with the components of this
// vector in the order of YWW.
func (lhs Vec4f) SwizzleYWW() Vec3f {
	return Vec3f{
		lhs[1],
		lhs[3],
		lhs[3],
	}
}

// SwizzleZXX returns a new vector with the components of this
// vector in the order of ZXX.
func (lhs Vec4f) SwizzleZXX() Vec3f {
	return Vec3f{
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZXY returns a new vector with the components of this
// vector in the order of ZXY.
func (lhs Vec4f) SwizzleZXY() Vec3f {
	return Vec3f{
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZXZ returns a new vector with the components of this
// vector in the order of ZXZ.
func (lhs Vec4f) SwizzleZXZ() Vec3f {
	return Vec3f{
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZXW returns a new vector with the components of this
// vector in the order of ZXW.
func (lhs Vec4f) SwizzleZXW() Vec3f {
	return Vec3f{
		lhs[2],
		lhs[0],
		lhs[3],
	}
}

// SwizzleZYX returns a new vector with the components of this
// vector in the order of ZYX.
func (lhs Vec4f) SwizzleZYX() Vec3f {
	return Vec3f{
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZYY returns a new vector with the components of this
// vector in the order of ZYY.
func (lhs Vec4f) SwizzleZYY() Vec3f {
	return Vec3f{
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZYZ returns a new vector with the components of this
// vector in the order of ZYZ.
func (lhs Vec4f) SwizzleZYZ() Vec3f {
	return Vec3f{
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZYW returns a new vector with the components of this
// vector in the order of ZYW.
func (lhs Vec4f) SwizzleZYW() Vec3f {
	return Vec3f{
		lhs[2],
		lhs[1],
		lhs[3],
	}
}

// SwizzleZZX returns a new vector with the components of this
// vector in the order of ZZX.
func (lhs Vec4f) SwizzleZZX() Vec3f {
	return Vec3f{
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZZY returns a new vector with the components of this
// vector in the order of ZZY.
func (lhs Vec4f) SwizzleZZY() Vec3f {
	return Vec3f{
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZZZ returns a new vector with the components of this
// vector in the order of ZZZ.
func (lhs Vec4f) SwizzleZZZ() Vec3f {
	return Vec3f{
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZZW returns a new vector with the components of this
// vector in the order of ZZW.
func (lhs Vec4f) SwizzleZZW() Vec3f {
	return Vec3f{
		lhs[2],
		lhs[2],
		lhs[3],
	}
}

// SwizzleZWX returns a new vector with the components of this
// vector in the order of ZWX.
func (lhs Vec4f) SwizzleZWX() Vec3f {
	return Vec3f{
		lhs[2],
		lhs[3],
		lhs[0],
	}
}

// SwizzleZWY returns a new vector with the components of this
// vector in the order of ZWY.
func (lhs Vec4f) SwizzleZWY() Vec3f {
	return Vec3f{
		lhs[2],
		lhs[3],
		lhs[1],
	}
}

// SwizzleZWZ returns a new vector with the components of this
// vector in the order of ZWZ.
func (lhs Vec4f) SwizzleZWZ() Vec3f {
	return Vec3f{
		lhs[2],
		lhs[3],
		lhs[2],
	}
}

// SwizzleZWW returns a new vector with the components of this
// vector in the order of ZWW.
func (lhs Vec4f) SwizzleZWW() Vec3f {
	return Vec3f{
		lhs[2],
		lhs[3],
		lhs[3],
	}
}

// SwizzleWXX returns a new vector with the components of this
// vector in the order of WXX.
func (lhs Vec4f) SwizzleWXX() Vec3f {
	return Vec3f{
		lhs[3],
		lhs[0],
		lhs[0],
	}
}

// SwizzleWXY returns a new vector with the components of this
// vector in the order of WXY.
func (lhs Vec4f) SwizzleWXY() Vec3f {
	return Vec3f{
		lhs[3],
		lhs[0],
		lhs[1],
	}
}

// SwizzleWXZ returns a new vector with the components of this
// vector in the order of WXZ.
func (lhs Vec4f) SwizzleWXZ() Vec3f {
	return Vec3f{
		lhs[3],
		lhs[0],
		lhs[2],
	}
}

// SwizzleWXW returns a new vector with the components of this
// vector in the order of WXW.
func (lhs Vec4f) SwizzleWXW() Vec3f {
	return Vec3f{
		lhs[3],
		lhs[0],
		lhs[3],
	}
}

// SwizzleWYX returns a new vector with the components of this
// vector in the order of WYX.
func (lhs Vec4f) SwizzleWYX() Vec3f {
	return Vec3f{
		lhs[3],
		lhs[1],
		lhs[0],
	}
}

// SwizzleWYY returns a new vector with the components of this
// vector in the order of WYY.
func (lhs Vec4f) SwizzleWYY() Vec3f {
	return Vec3f{
		lhs[3],
		lhs[1],
		lhs[1],
	}
}

// SwizzleWYZ returns a new vector with the components of this
// vector in the order of WYZ.
func (lhs Vec4f) SwizzleWYZ() Vec3f {
	return Vec3f{
		lhs[3],
		lhs[1],
		lhs[2],
	}
}

// SwizzleWYW returns a new vector with the components of this
// vector in the order of WYW.
func (lhs Vec4f) SwizzleWYW() Vec3f {
	return Vec3f{
		lhs[3],
		lhs[1],
		lhs[3],
	}
}

// SwizzleWZX returns a new vector with the components of this
// vector in the order of WZX.
func (lhs Vec4f) SwizzleWZX() Vec3f {
	return Vec3f{
		lhs[3],
		lhs[2],
		lhs[0],
	}
}

// SwizzleWZY returns a new vector with the components of this
// vector in the order of WZY.
func (lhs Vec4f) SwizzleWZY() Vec3f {
	return Vec3f{
		lhs[3],
		lhs[2],
		lhs[1],
	}
}

// SwizzleWZZ returns a new vector with the components of this
// vector in the order of WZZ.
func (lhs Vec4f) SwizzleWZZ() Vec3f {
	return Vec3f{
		lhs[3],
		lhs[2],
		lhs[2],
	}
}

// SwizzleWZW returns a new vector with the components of this
// vector in the order of WZW.
func (lhs Vec4f) SwizzleWZW() Vec3f {
	return Vec3f{
		lhs[3],
		lhs[2],
		lhs[3],
	}
}

// SwizzleWWX returns a new vector with the components of this
// vector in the order of WWX.
func (lhs Vec4f) SwizzleWWX() Vec3f {
	return Vec3f{
		lhs[3],
		lhs[3],
		lhs[0],
	}
}

// SwizzleWWY returns a new vector with the components of this
// vector in the order of WWY.
func (lhs Vec4f) SwizzleWWY() Vec3f {
	return Vec3f{
		lhs[3],
		lhs[3],
		lhs[1],
	}
}

// SwizzleWWZ returns a new vector with the components of this
// vector in the order of WWZ.
func (lhs Vec4f) SwizzleWWZ() Vec3f {
	return Vec3f{
		lhs[3],
		lhs[3],
		lhs[2],
	}
}

// SwizzleWWW returns a new vector with the components of this
// vector in the order of WWW.
func (lhs Vec4f) SwizzleWWW() Vec3f {
	return Vec3f{
		lhs[3],
		lhs[3],
		lhs[3],
	}
}

// SwizzleXXXX returns a new vector with the components of this
// vector in the order of XXXX.
func (lhs Vec4f) SwizzleXXXX() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXXXY returns a new vector with the components of this
// vector in the order of XXXY.
func (lhs Vec4f) SwizzleXXXY() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXXXZ returns a new vector with the components of this
// vector in the order of XXXZ.
func (lhs Vec4f) SwizzleXXXZ() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXXXW returns a new vector with the components of this
// vector in the order of XXXW.
func (lhs Vec4f) SwizzleXXXW() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[0],
		lhs[0],
		lhs[3],
	}
}

// SwizzleXXYX returns a new vector with the components of this
// vector in the order of XXYX.
func (lhs Vec4f) SwizzleXXYX() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXXYY returns a new vector with the components of this
// vector in the order of XXYY.
func (lhs Vec4f) SwizzleXXYY() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXXYZ returns a new vector with the components of this
// vector in the order of XXYZ.
func (lhs Vec4f) SwizzleXXYZ() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXXYW returns a new vector with the components of this
// vector in the order of XXYW.
func (lhs Vec4f) SwizzleXXYW() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[0],
		lhs[1],
		lhs[3],
	}
}

// SwizzleXXZX returns a new vector with the components of this
// vector in the order of XXZX.
func (lhs Vec4f) SwizzleXXZX() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXXZY returns a new vector with the components of this
// vector in the order of XXZY.
func (lhs Vec4f) SwizzleXXZY() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXXZZ returns a new vector with the components of this
// vector in the order of XXZZ.
func (lhs Vec4f) SwizzleXXZZ() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleXXZW returns a new vector with the components of this
// vector in the order of XXZW.
func (lhs Vec4f) SwizzleXXZW() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[0],
		lhs[2],
		lhs[3],
	}
}

// SwizzleXXWX returns a new vector with the components of this
// vector in the order of XXWX.
func (lhs Vec4f) SwizzleXXWX() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[0],
		lhs[3],
		lhs[0],
	}
}

// SwizzleXXWY returns a new vector with the components of this
// vector in the order of XXWY.
func (lhs Vec4f) SwizzleXXWY() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[0],
		lhs[3],
		lhs[1],
	}
}

// SwizzleXXWZ returns a new vector with the components of this
// vector in the order of XXWZ.
func (lhs Vec4f) SwizzleXXWZ() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[0],
		lhs[3],
		lhs[2],
	}
}

// SwizzleXXWW returns a new vector with the components of this
// vector in the order of XXWW.
func (lhs Vec4f) SwizzleXXWW() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[0],
		lhs[3],
		lhs[3],
	}
}

// SwizzleXYXX returns a new vector with the components of this
// vector in the order of XYXX.
func (lhs Vec4f) SwizzleXYXX() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXYXY returns a new vector with the components of this
// vector in the order of XYXY.
func (lhs Vec4f) SwizzleXYXY() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXYXZ returns a new vector with the components of this
// vector in the order of XYXZ.
func (lhs Vec4f) SwizzleXYXZ() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXYXW returns a new vector with the components of this
// vector in the order of XYXW.
func (lhs Vec4f) SwizzleXYXW() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[1],
		lhs[0],
		lhs[3],
	}
}

// SwizzleXYYX returns a new vector with the components of this
// vector in the order of XYYX.
func (lhs Vec4f) SwizzleXYYX() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXYYY returns a new vector with the components of this
// vector in the order of XYYY.
func (lhs Vec4f) SwizzleXYYY() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXYYZ returns a new vector with the components of this
// vector in the order of XYYZ.
func (lhs Vec4f) SwizzleXYYZ() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXYYW returns a new vector with the components of this
// vector in the order of XYYW.
func (lhs Vec4f) SwizzleXYYW() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[1],
		lhs[1],
		lhs[3],
	}
}

// SwizzleXYZX returns a new vector with the components of this
// vector in the order of XYZX.
func (lhs Vec4f) SwizzleXYZX() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXYZY returns a new vector with the components of this
// vector in the order of XYZY.
func (lhs Vec4f) SwizzleXYZY() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXYZZ returns a new vector with the components of this
// vector in the order of XYZZ.
func (lhs Vec4f) SwizzleXYZZ() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleXYZW returns a new vector with the components of this
// vector in the order of XYZW.
func (lhs Vec4f) SwizzleXYZW() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[1],
		lhs[2],
		lhs[3],
	}
}

// SwizzleXYWX returns a new vector with the components of this
// vector in the order of XYWX.
func (lhs Vec4f) SwizzleXYWX() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[1],
		lhs[3],
		lhs[0],
	}
}

// SwizzleXYWY returns a new vector with the components of this
// vector in the order of XYWY.
func (lhs Vec4f) SwizzleXYWY() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[1],
		lhs[3],
		lhs[1],
	}
}

// SwizzleXYWZ returns a new vector with the components of this
// vector in the order of XYWZ.
func (lhs Vec4f) SwizzleXYWZ() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[1],
		lhs[3],
		lhs[2],
	}
}

// SwizzleXYWW returns a new vector with the components of this
// vector in the order of XYWW.
func (lhs Vec4f) SwizzleXYWW() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[1],
		lhs[3],
		lhs[3],
	}
}

// SwizzleXZXX returns a new vector with the components of this
// vector in the order of XZXX.
func (lhs Vec4f) SwizzleXZXX() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXZXY returns a new vector with the components of this
// vector in the order of XZXY.
func (lhs Vec4f) SwizzleXZXY() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXZXZ returns a new vector with the components of this
// vector in the order of XZXZ.
func (lhs Vec4f) SwizzleXZXZ() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXZXW returns a new vector with the components of this
// vector in the order of XZXW.
func (lhs Vec4f) SwizzleXZXW() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[2],
		lhs[0],
		lhs[3],
	}
}

// SwizzleXZYX returns a new vector with the components of this
// vector in the order of XZYX.
func (lhs Vec4f) SwizzleXZYX() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXZYY returns a new vector with the components of this
// vector in the order of XZYY.
func (lhs Vec4f) SwizzleXZYY() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXZYZ returns a new vector with the components of this
// vector in the order of XZYZ.
func (lhs Vec4f) SwizzleXZYZ() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXZYW returns a new vector with the components of this
// vector in the order of XZYW.
func (lhs Vec4f) SwizzleXZYW() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[2],
		lhs[1],
		lhs[3],
	}
}

// SwizzleXZZX returns a new vector with the components of this
// vector in the order of XZZX.
func (lhs Vec4f) SwizzleXZZX() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXZZY returns a new vector with the components of this
// vector in the order of XZZY.
func (lhs Vec4f) SwizzleXZZY() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXZZZ returns a new vector with the components of this
// vector in the order of XZZZ.
func (lhs Vec4f) SwizzleXZZZ() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

// SwizzleXZZW returns a new vector with the components of this
// vector in the order of XZZW.
func (lhs Vec4f) SwizzleXZZW() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[2],
		lhs[2],
		lhs[3],
	}
}

// SwizzleXZWX returns a new vector with the components of this
// vector in the order of XZWX.
func (lhs Vec4f) SwizzleXZWX() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[2],
		lhs[3],
		lhs[0],
	}
}

// SwizzleXZWY returns a new vector with the components of this
// vector in the order of XZWY.
func (lhs Vec4f) SwizzleXZWY() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[2],
		lhs[3],
		lhs[1],
	}
}

// SwizzleXZWZ returns a new vector with the components of this
// vector in the order of XZWZ.
func (lhs Vec4f) SwizzleXZWZ() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[2],
		lhs[3],
		lhs[2],
	}
}

// SwizzleXZWW returns a new vector with the components of this
// vector in the order of XZWW.
func (lhs Vec4f) SwizzleXZWW() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[2],
		lhs[3],
		lhs[3],
	}
}

// SwizzleXWXX returns a new vector with the components of this
// vector in the order of XWXX.
func (lhs Vec4f) SwizzleXWXX() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[3],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXWXY returns a new vector with the components of this
// vector in the order of XWXY.
func (lhs Vec4f) SwizzleXWXY() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[3],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXWXZ returns a new vector with the components of this
// vector in the order of XWXZ.
func (lhs Vec4f) SwizzleXWXZ() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[3],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXWXW returns a new vector with the components of this
// vector in the order of XWXW.
func (lhs Vec4f) SwizzleXWXW() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[3],
		lhs[0],
		lhs[3],
	}
}

// SwizzleXWYX returns a new vector with the components of this
// vector in the order of XWYX.
func (lhs Vec4f) SwizzleXWYX() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[3],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXWYY returns a new vector with the components of this
// vector in the order of XWYY.
func (lhs Vec4f) SwizzleXWYY() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[3],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXWYZ returns a new vector with the components of this
// vector in the order of XWYZ.
func (lhs Vec4f) SwizzleXWYZ() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[3],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXWYW returns a new vector with the components of this
// vector in the order of XWYW.
func (lhs Vec4f) SwizzleXWYW() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[3],
		lhs[1],
		lhs[3],
	}
}

// SwizzleXWZX returns a new vector with the components of this
// vector in the order of XWZX.
func (lhs Vec4f) SwizzleXWZX() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[3],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXWZY returns a new vector with the components of this
// vector in the order of XWZY.
func (lhs Vec4f) SwizzleXWZY() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[3],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXWZZ returns a new vector with the components of this
// vector in the order of XWZZ.
func (lhs Vec4f) SwizzleXWZZ() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[3],
		lhs[2],
		lhs[2],
	}
}

// SwizzleXWZW returns a new vector with the components of this
// vector in the order of XWZW.
func (lhs Vec4f) SwizzleXWZW() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[3],
		lhs[2],
		lhs[3],
	}
}

// SwizzleXWWX returns a new vector with the components of this
// vector in the order of XWWX.
func (lhs Vec4f) SwizzleXWWX() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[3],
		lhs[3],
		lhs[0],
	}
}

// SwizzleXWWY returns a new vector with the components of this
// vector in the order of XWWY.
func (lhs Vec4f) SwizzleXWWY() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[3],
		lhs[3],
		lhs[1],
	}
}

// SwizzleXWWZ returns a new vector with the components of this
// vector in the order of XWWZ.
func (lhs Vec4f) SwizzleXWWZ() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[3],
		lhs[3],
		lhs[2],
	}
}

// SwizzleXWWW returns a new vector with the components of this
// vector in the order of XWWW.
func (lhs Vec4f) SwizzleXWWW() Vec4f {
	return Vec4f{
		lhs[0],
		lhs[3],
		lhs[3],
		lhs[3],
	}
}

// SwizzleYXXX returns a new vector with the components of this
// vector in the order of YXXX.
func (lhs Vec4f) SwizzleYXXX() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYXXY returns a new vector with the components of this
// vector in the order of YXXY.
func (lhs Vec4f) SwizzleYXXY() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYXXZ returns a new vector with the components of this
// vector in the order of YXXZ.
func (lhs Vec4f) SwizzleYXXZ() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYXXW returns a new vector with the components of this
// vector in the order of YXXW.
func (lhs Vec4f) SwizzleYXXW() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[0],
		lhs[0],
		lhs[3],
	}
}

// SwizzleYXYX returns a new vector with the components of this
// vector in the order of YXYX.
func (lhs Vec4f) SwizzleYXYX() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYXYY returns a new vector with the components of this
// vector in the order of YXYY.
func (lhs Vec4f) SwizzleYXYY() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYXYZ returns a new vector with the components of this
// vector in the order of YXYZ.
func (lhs Vec4f) SwizzleYXYZ() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYXYW returns a new vector with the components of this
// vector in the order of YXYW.
func (lhs Vec4f) SwizzleYXYW() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[0],
		lhs[1],
		lhs[3],
	}
}

// SwizzleYXZX returns a new vector with the components of this
// vector in the order of YXZX.
func (lhs Vec4f) SwizzleYXZX() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYXZY returns a new vector with the components of this
// vector in the order of YXZY.
func (lhs Vec4f) SwizzleYXZY() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYXZZ returns a new vector with the components of this
// vector in the order of YXZZ.
func (lhs Vec4f) SwizzleYXZZ() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYXZW returns a new vector with the components of this
// vector in the order of YXZW.
func (lhs Vec4f) SwizzleYXZW() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[0],
		lhs[2],
		lhs[3],
	}
}

// SwizzleYXWX returns a new vector with the components of this
// vector in the order of YXWX.
func (lhs Vec4f) SwizzleYXWX() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[0],
		lhs[3],
		lhs[0],
	}
}

// SwizzleYXWY returns a new vector with the components of this
// vector in the order of YXWY.
func (lhs Vec4f) SwizzleYXWY() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[0],
		lhs[3],
		lhs[1],
	}
}

// SwizzleYXWZ returns a new vector with the components of this
// vector in the order of YXWZ.
func (lhs Vec4f) SwizzleYXWZ() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[0],
		lhs[3],
		lhs[2],
	}
}

// SwizzleYXWW returns a new vector with the components of this
// vector in the order of YXWW.
func (lhs Vec4f) SwizzleYXWW() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[0],
		lhs[3],
		lhs[3],
	}
}

// SwizzleYYXX returns a new vector with the components of this
// vector in the order of YYXX.
func (lhs Vec4f) SwizzleYYXX() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYYXY returns a new vector with the components of this
// vector in the order of YYXY.
func (lhs Vec4f) SwizzleYYXY() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYYXZ returns a new vector with the components of this
// vector in the order of YYXZ.
func (lhs Vec4f) SwizzleYYXZ() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYYXW returns a new vector with the components of this
// vector in the order of YYXW.
func (lhs Vec4f) SwizzleYYXW() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[1],
		lhs[0],
		lhs[3],
	}
}

// SwizzleYYYX returns a new vector with the components of this
// vector in the order of YYYX.
func (lhs Vec4f) SwizzleYYYX() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYYYY returns a new vector with the components of this
// vector in the order of YYYY.
func (lhs Vec4f) SwizzleYYYY() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYYYZ returns a new vector with the components of this
// vector in the order of YYYZ.
func (lhs Vec4f) SwizzleYYYZ() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYYYW returns a new vector with the components of this
// vector in the order of YYYW.
func (lhs Vec4f) SwizzleYYYW() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[1],
		lhs[1],
		lhs[3],
	}
}

// SwizzleYYZX returns a new vector with the components of this
// vector in the order of YYZX.
func (lhs Vec4f) SwizzleYYZX() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYYZY returns a new vector with the components of this
// vector in the order of YYZY.
func (lhs Vec4f) SwizzleYYZY() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYYZZ returns a new vector with the components of this
// vector in the order of YYZZ.
func (lhs Vec4f) SwizzleYYZZ() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYYZW returns a new vector with the components of this
// vector in the order of YYZW.
func (lhs Vec4f) SwizzleYYZW() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[1],
		lhs[2],
		lhs[3],
	}
}

// SwizzleYYWX returns a new vector with the components of this
// vector in the order of YYWX.
func (lhs Vec4f) SwizzleYYWX() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[1],
		lhs[3],
		lhs[0],
	}
}

// SwizzleYYWY returns a new vector with the components of this
// vector in the order of YYWY.
func (lhs Vec4f) SwizzleYYWY() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[1],
		lhs[3],
		lhs[1],
	}
}

// SwizzleYYWZ returns a new vector with the components of this
// vector in the order of YYWZ.
func (lhs Vec4f) SwizzleYYWZ() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[1],
		lhs[3],
		lhs[2],
	}
}

// SwizzleYYWW returns a new vector with the components of this
// vector in the order of YYWW.
func (lhs Vec4f) SwizzleYYWW() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[1],
		lhs[3],
		lhs[3],
	}
}

// SwizzleYZXX returns a new vector with the components of this
// vector in the order of YZXX.
func (lhs Vec4f) SwizzleYZXX() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYZXY returns a new vector with the components of this
// vector in the order of YZXY.
func (lhs Vec4f) SwizzleYZXY() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYZXZ returns a new vector with the components of this
// vector in the order of YZXZ.
func (lhs Vec4f) SwizzleYZXZ() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYZXW returns a new vector with the components of this
// vector in the order of YZXW.
func (lhs Vec4f) SwizzleYZXW() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[2],
		lhs[0],
		lhs[3],
	}
}

// SwizzleYZYX returns a new vector with the components of this
// vector in the order of YZYX.
func (lhs Vec4f) SwizzleYZYX() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYZYY returns a new vector with the components of this
// vector in the order of YZYY.
func (lhs Vec4f) SwizzleYZYY() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYZYZ returns a new vector with the components of this
// vector in the order of YZYZ.
func (lhs Vec4f) SwizzleYZYZ() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYZYW returns a new vector with the components of this
// vector in the order of YZYW.
func (lhs Vec4f) SwizzleYZYW() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[2],
		lhs[1],
		lhs[3],
	}
}

// SwizzleYZZX returns a new vector with the components of this
// vector in the order of YZZX.
func (lhs Vec4f) SwizzleYZZX() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYZZY returns a new vector with the components of this
// vector in the order of YZZY.
func (lhs Vec4f) SwizzleYZZY() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYZZZ returns a new vector with the components of this
// vector in the order of YZZZ.
func (lhs Vec4f) SwizzleYZZZ() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYZZW returns a new vector with the components of this
// vector in the order of YZZW.
func (lhs Vec4f) SwizzleYZZW() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[2],
		lhs[2],
		lhs[3],
	}
}

// SwizzleYZWX returns a new vector with the components of this
// vector in the order of YZWX.
func (lhs Vec4f) SwizzleYZWX() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[2],
		lhs[3],
		lhs[0],
	}
}

// SwizzleYZWY returns a new vector with the components of this
// vector in the order of YZWY.
func (lhs Vec4f) SwizzleYZWY() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[2],
		lhs[3],
		lhs[1],
	}
}

// SwizzleYZWZ returns a new vector with the components of this
// vector in the order of YZWZ.
func (lhs Vec4f) SwizzleYZWZ() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[2],
		lhs[3],
		lhs[2],
	}
}

// SwizzleYZWW returns a new vector with the components of this
// vector in the order of YZWW.
func (lhs Vec4f) SwizzleYZWW() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[2],
		lhs[3],
		lhs[3],
	}
}

// SwizzleYWXX returns a new vector with the components of this
// vector in the order of YWXX.
func (lhs Vec4f) SwizzleYWXX() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[3],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYWXY returns a new vector with the components of this
// vector in the order of YWXY.
func (lhs Vec4f) SwizzleYWXY() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[3],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYWXZ returns a new vector with the components of this
// vector in the order of YWXZ.
func (lhs Vec4f) SwizzleYWXZ() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[3],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYWXW returns a new vector with the components of this
// vector in the order of YWXW.
func (lhs Vec4f) SwizzleYWXW() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[3],
		lhs[0],
		lhs[3],
	}
}

// SwizzleYWYX returns a new vector with the components of this
// vector in the order of YWYX.
func (lhs Vec4f) SwizzleYWYX() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[3],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYWYY returns a new vector with the components of this
// vector in the order of YWYY.
func (lhs Vec4f) SwizzleYWYY() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[3],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYWYZ returns a new vector with the components of this
// vector in the order of YWYZ.
func (lhs Vec4f) SwizzleYWYZ() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[3],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYWYW returns a new vector with the components of this
// vector in the order of YWYW.
func (lhs Vec4f) SwizzleYWYW() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[3],
		lhs[1],
		lhs[3],
	}
}

// SwizzleYWZX returns a new vector with the components of this
// vector in the order of YWZX.
func (lhs Vec4f) SwizzleYWZX() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[3],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYWZY returns a new vector with the components of this
// vector in the order of YWZY.
func (lhs Vec4f) SwizzleYWZY() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[3],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYWZZ returns a new vector with the components of this
// vector in the order of YWZZ.
func (lhs Vec4f) SwizzleYWZZ() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[3],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYWZW returns a new vector with the components of this
// vector in the order of YWZW.
func (lhs Vec4f) SwizzleYWZW() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[3],
		lhs[2],
		lhs[3],
	}
}

// SwizzleYWWX returns a new vector with the components of this
// vector in the order of YWWX.
func (lhs Vec4f) SwizzleYWWX() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[3],
		lhs[3],
		lhs[0],
	}
}

// SwizzleYWWY returns a new vector with the components of this
// vector in the order of YWWY.
func (lhs Vec4f) SwizzleYWWY() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[3],
		lhs[3],
		lhs[1],
	}
}

// SwizzleYWWZ returns a new vector with the components of this
// vector in the order of YWWZ.
func (lhs Vec4f) SwizzleYWWZ() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[3],
		lhs[3],
		lhs[2],
	}
}

// SwizzleYWWW returns a new vector with the components of this
// vector in the order of YWWW.
func (lhs Vec4f) SwizzleYWWW() Vec4f {
	return Vec4f{
		lhs[1],
		lhs[3],
		lhs[3],
		lhs[3],
	}
}

// SwizzleZXXX returns a new vector with the components of this
// vector in the order of ZXXX.
func (lhs Vec4f) SwizzleZXXX() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZXXY returns a new vector with the components of this
// vector in the order of ZXXY.
func (lhs Vec4f) SwizzleZXXY() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZXXZ returns a new vector with the components of this
// vector in the order of ZXXZ.
func (lhs Vec4f) SwizzleZXXZ() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZXXW returns a new vector with the components of this
// vector in the order of ZXXW.
func (lhs Vec4f) SwizzleZXXW() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[0],
		lhs[0],
		lhs[3],
	}
}

// SwizzleZXYX returns a new vector with the components of this
// vector in the order of ZXYX.
func (lhs Vec4f) SwizzleZXYX() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZXYY returns a new vector with the components of this
// vector in the order of ZXYY.
func (lhs Vec4f) SwizzleZXYY() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZXYZ returns a new vector with the components of this
// vector in the order of ZXYZ.
func (lhs Vec4f) SwizzleZXYZ() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZXYW returns a new vector with the components of this
// vector in the order of ZXYW.
func (lhs Vec4f) SwizzleZXYW() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[0],
		lhs[1],
		lhs[3],
	}
}

// SwizzleZXZX returns a new vector with the components of this
// vector in the order of ZXZX.
func (lhs Vec4f) SwizzleZXZX() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZXZY returns a new vector with the components of this
// vector in the order of ZXZY.
func (lhs Vec4f) SwizzleZXZY() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZXZZ returns a new vector with the components of this
// vector in the order of ZXZZ.
func (lhs Vec4f) SwizzleZXZZ() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZXZW returns a new vector with the components of this
// vector in the order of ZXZW.
func (lhs Vec4f) SwizzleZXZW() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[0],
		lhs[2],
		lhs[3],
	}
}

// SwizzleZXWX returns a new vector with the components of this
// vector in the order of ZXWX.
func (lhs Vec4f) SwizzleZXWX() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[0],
		lhs[3],
		lhs[0],
	}
}

// SwizzleZXWY returns a new vector with the components of this
// vector in the order of ZXWY.
func (lhs Vec4f) SwizzleZXWY() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[0],
		lhs[3],
		lhs[1],
	}
}

// SwizzleZXWZ returns a new vector with the components of this
// vector in the order of ZXWZ.
func (lhs Vec4f) SwizzleZXWZ() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[0],
		lhs[3],
		lhs[2],
	}
}

// SwizzleZXWW returns a new vector with the components of this
// vector in the order of ZXWW.
func (lhs Vec4f) SwizzleZXWW() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[0],
		lhs[3],
		lhs[3],
	}
}

// SwizzleZYXX returns a new vector with the components of this
// vector in the order of ZYXX.
func (lhs Vec4f) SwizzleZYXX() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZYXY returns a new vector with the components of this
// vector in the order of ZYXY.
func (lhs Vec4f) SwizzleZYXY() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZYXZ returns a new vector with the components of this
// vector in the order of ZYXZ.
func (lhs Vec4f) SwizzleZYXZ() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZYXW returns a new vector with the components of this
// vector in the order of ZYXW.
func (lhs Vec4f) SwizzleZYXW() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[1],
		lhs[0],
		lhs[3],
	}
}

// SwizzleZYYX returns a new vector with the components of this
// vector in the order of ZYYX.
func (lhs Vec4f) SwizzleZYYX() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZYYY returns a new vector with the components of this
// vector in the order of ZYYY.
func (lhs Vec4f) SwizzleZYYY() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZYYZ returns a new vector with the components of this
// vector in the order of ZYYZ.
func (lhs Vec4f) SwizzleZYYZ() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZYYW returns a new vector with the components of this
// vector in the order of ZYYW.
func (lhs Vec4f) SwizzleZYYW() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[1],
		lhs[1],
		lhs[3],
	}
}

// SwizzleZYZX returns a new vector with the components of this
// vector in the order of ZYZX.
func (lhs Vec4f) SwizzleZYZX() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZYZY returns a new vector with the components of this
// vector in the order of ZYZY.
func (lhs Vec4f) SwizzleZYZY() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZYZZ returns a new vector with the components of this
// vector in the order of ZYZZ.
func (lhs Vec4f) SwizzleZYZZ() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZYZW returns a new vector with the components of this
// vector in the order of ZYZW.
func (lhs Vec4f) SwizzleZYZW() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[1],
		lhs[2],
		lhs[3],
	}
}

// SwizzleZYWX returns a new vector with the components of this
// vector in the order of ZYWX.
func (lhs Vec4f) SwizzleZYWX() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[1],
		lhs[3],
		lhs[0],
	}
}

// SwizzleZYWY returns a new vector with the components of this
// vector in the order of ZYWY.
func (lhs Vec4f) SwizzleZYWY() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[1],
		lhs[3],
		lhs[1],
	}
}

// SwizzleZYWZ returns a new vector with the components of this
// vector in the order of ZYWZ.
func (lhs Vec4f) SwizzleZYWZ() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[1],
		lhs[3],
		lhs[2],
	}
}

// SwizzleZYWW returns a new vector with the components of this
// vector in the order of ZYWW.
func (lhs Vec4f) SwizzleZYWW() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[1],
		lhs[3],
		lhs[3],
	}
}

// SwizzleZZXX returns a new vector with the components of this
// vector in the order of ZZXX.
func (lhs Vec4f) SwizzleZZXX() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZZXY returns a new vector with the components of this
// vector in the order of ZZXY.
func (lhs Vec4f) SwizzleZZXY() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZZXZ returns a new vector with the components of this
// vector in the order of ZZXZ.
func (lhs Vec4f) SwizzleZZXZ() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZZXW returns a new vector with the components of this
// vector in the order of ZZXW.
func (lhs Vec4f) SwizzleZZXW() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[2],
		lhs[0],
		lhs[3],
	}
}

// SwizzleZZYX returns a new vector with the components of this
// vector in the order of ZZYX.
func (lhs Vec4f) SwizzleZZYX() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZZYY returns a new vector with the components of this
// vector in the order of ZZYY.
func (lhs Vec4f) SwizzleZZYY() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZZYZ returns a new vector with the components of this
// vector in the order of ZZYZ.
func (lhs Vec4f) SwizzleZZYZ() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZZYW returns a new vector with the components of this
// vector in the order of ZZYW.
func (lhs Vec4f) SwizzleZZYW() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[2],
		lhs[1],
		lhs[3],
	}
}

// SwizzleZZZX returns a new vector with the components of this
// vector in the order of ZZZX.
func (lhs Vec4f) SwizzleZZZX() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZZZY returns a new vector with the components of this
// vector in the order of ZZZY.
func (lhs Vec4f) SwizzleZZZY() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZZZZ returns a new vector with the components of this
// vector in the order of ZZZZ.
func (lhs Vec4f) SwizzleZZZZ() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZZZW returns a new vector with the components of this
// vector in the order of ZZZW.
func (lhs Vec4f) SwizzleZZZW() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[2],
		lhs[2],
		lhs[3],
	}
}

// SwizzleZZWX returns a new vector with the components of this
// vector in the order of ZZWX.
func (lhs Vec4f) SwizzleZZWX() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[2],
		lhs[3],
		lhs[0],
	}
}

// SwizzleZZWY returns a new vector with the components of this
// vector in the order of ZZWY.
func (lhs Vec4f) SwizzleZZWY() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[2],
		lhs[3],
		lhs[1],
	}
}

// SwizzleZZWZ returns a new vector with the components of this
// vector in the order of ZZWZ.
func (lhs Vec4f) SwizzleZZWZ() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[2],
		lhs[3],
		lhs[2],
	}
}

// SwizzleZZWW returns a new vector with the components of this
// vector in the order of ZZWW.
func (lhs Vec4f) SwizzleZZWW() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[2],
		lhs[3],
		lhs[3],
	}
}

// SwizzleZWXX returns a new vector with the components of this
// vector in the order of ZWXX.
func (lhs Vec4f) SwizzleZWXX() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[3],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZWXY returns a new vector with the components of this
// vector in the order of ZWXY.
func (lhs Vec4f) SwizzleZWXY() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[3],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZWXZ returns a new vector with the components of this
// vector in the order of ZWXZ.
func (lhs Vec4f) SwizzleZWXZ() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[3],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZWXW returns a new vector with the components of this
// vector in the order of ZWXW.
func (lhs Vec4f) SwizzleZWXW() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[3],
		lhs[0],
		lhs[3],
	}
}

// SwizzleZWYX returns a new vector with the components of this
// vector in the order of ZWYX.
func (lhs Vec4f) SwizzleZWYX() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[3],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZWYY returns a new vector with the components of this
// vector in the order of ZWYY.
func (lhs Vec4f) SwizzleZWYY() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[3],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZWYZ returns a new vector with the components of this
// vector in the order of ZWYZ.
func (lhs Vec4f) SwizzleZWYZ() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[3],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZWYW returns a new vector with the components of this
// vector in the order of ZWYW.
func (lhs Vec4f) SwizzleZWYW() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[3],
		lhs[1],
		lhs[3],
	}
}

// SwizzleZWZX returns a new vector with the components of this
// vector in the order of ZWZX.
func (lhs Vec4f) SwizzleZWZX() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[3],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZWZY returns a new vector with the components of this
// vector in the order of ZWZY.
func (lhs Vec4f) SwizzleZWZY() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[3],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZWZZ returns a new vector with the components of this
// vector in the order of ZWZZ.
func (lhs Vec4f) SwizzleZWZZ() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[3],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZWZW returns a new vector with the components of this
// vector in the order of ZWZW.
func (lhs Vec4f) SwizzleZWZW() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[3],
		lhs[2],
		lhs[3],
	}
}

// SwizzleZWWX returns a new vector with the components of this
// vector in the order of ZWWX.
func (lhs Vec4f) SwizzleZWWX() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[3],
		lhs[3],
		lhs[0],
	}
}

// SwizzleZWWY returns a new vector with the components of this
// vector in the order of ZWWY.
func (lhs Vec4f) SwizzleZWWY() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[3],
		lhs[3],
		lhs[1],
	}
}

// SwizzleZWWZ returns a new vector with the components of this
// vector in the order of ZWWZ.
func (lhs Vec4f) SwizzleZWWZ() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[3],
		lhs[3],
		lhs[2],
	}
}

// SwizzleZWWW returns a new vector with the components of this
// vector in the order of ZWWW.
func (lhs Vec4f) SwizzleZWWW() Vec4f {
	return Vec4f{
		lhs[2],
		lhs[3],
		lhs[3],
		lhs[3],
	}
}

// SwizzleWXXX returns a new vector with the components of this
// vector in the order of WXXX.
func (lhs Vec4f) SwizzleWXXX() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleWXXY returns a new vector with the components of this
// vector in the order of WXXY.
func (lhs Vec4f) SwizzleWXXY() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleWXXZ returns a new vector with the components of this
// vector in the order of WXXZ.
func (lhs Vec4f) SwizzleWXXZ() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleWXXW returns a new vector with the components of this
// vector in the order of WXXW.
func (lhs Vec4f) SwizzleWXXW() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[0],
		lhs[0],
		lhs[3],
	}
}

// SwizzleWXYX returns a new vector with the components of this
// vector in the order of WXYX.
func (lhs Vec4f) SwizzleWXYX() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleWXYY returns a new vector with the components of this
// vector in the order of WXYY.
func (lhs Vec4f) SwizzleWXYY() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleWXYZ returns a new vector with the components of this
// vector in the order of WXYZ.
func (lhs Vec4f) SwizzleWXYZ() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleWXYW returns a new vector with the components of this
// vector in the order of WXYW.
func (lhs Vec4f) SwizzleWXYW() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[0],
		lhs[1],
		lhs[3],
	}
}

// SwizzleWXZX returns a new vector with the components of this
// vector in the order of WXZX.
func (lhs Vec4f) SwizzleWXZX() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleWXZY returns a new vector with the components of this
// vector in the order of WXZY.
func (lhs Vec4f) SwizzleWXZY() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleWXZZ returns a new vector with the components of this
// vector in the order of WXZZ.
func (lhs Vec4f) SwizzleWXZZ() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleWXZW returns a new vector with the components of this
// vector in the order of WXZW.
func (lhs Vec4f) SwizzleWXZW() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[0],
		lhs[2],
		lhs[3],
	}
}

// SwizzleWXWX returns a new vector with the components of this
// vector in the order of WXWX.
func (lhs Vec4f) SwizzleWXWX() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[0],
		lhs[3],
		lhs[0],
	}
}

// SwizzleWXWY returns a new vector with the components of this
// vector in the order of WXWY.
func (lhs Vec4f) SwizzleWXWY() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[0],
		lhs[3],
		lhs[1],
	}
}

// SwizzleWXWZ returns a new vector with the components of this
// vector in the order of WXWZ.
func (lhs Vec4f) SwizzleWXWZ() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[0],
		lhs[3],
		lhs[2],
	}
}

// SwizzleWXWW returns a new vector with the components of this
// vector in the order of WXWW.
func (lhs Vec4f) SwizzleWXWW() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[0],
		lhs[3],
		lhs[3],
	}
}

// SwizzleWYXX returns a new vector with the components of this
// vector in the order of WYXX.
func (lhs Vec4f) SwizzleWYXX() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleWYXY returns a new vector with the components of this
// vector in the order of WYXY.
func (lhs Vec4f) SwizzleWYXY() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleWYXZ returns a new vector with the components of this
// vector in the order of WYXZ.
func (lhs Vec4f) SwizzleWYXZ() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleWYXW returns a new vector with the components of this
// vector in the order of WYXW.
func (lhs Vec4f) SwizzleWYXW() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[1],
		lhs[0],
		lhs[3],
	}
}

// SwizzleWYYX returns a new vector with the components of this
// vector in the order of WYYX.
func (lhs Vec4f) SwizzleWYYX() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleWYYY returns a new vector with the components of this
// vector in the order of WYYY.
func (lhs Vec4f) SwizzleWYYY() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleWYYZ returns a new vector with the components of this
// vector in the order of WYYZ.
func (lhs Vec4f) SwizzleWYYZ() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleWYYW returns a new vector with the components of this
// vector in the order of WYYW.
func (lhs Vec4f) SwizzleWYYW() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[1],
		lhs[1],
		lhs[3],
	}
}

// SwizzleWYZX returns a new vector with the components of this
// vector in the order of WYZX.
func (lhs Vec4f) SwizzleWYZX() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleWYZY returns a new vector with the components of this
// vector in the order of WYZY.
func (lhs Vec4f) SwizzleWYZY() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleWYZZ returns a new vector with the components of this
// vector in the order of WYZZ.
func (lhs Vec4f) SwizzleWYZZ() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleWYZW returns a new vector with the components of this
// vector in the order of WYZW.
func (lhs Vec4f) SwizzleWYZW() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[1],
		lhs[2],
		lhs[3],
	}
}

// SwizzleWYWX returns a new vector with the components of this
// vector in the order of WYWX.
func (lhs Vec4f) SwizzleWYWX() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[1],
		lhs[3],
		lhs[0],
	}
}

// SwizzleWYWY returns a new vector with the components of this
// vector in the order of WYWY.
func (lhs Vec4f) SwizzleWYWY() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[1],
		lhs[3],
		lhs[1],
	}
}

// SwizzleWYWZ returns a new vector with the components of this
// vector in the order of WYWZ.
func (lhs Vec4f) SwizzleWYWZ() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[1],
		lhs[3],
		lhs[2],
	}
}

// SwizzleWYWW returns a new vector with the components of this
// vector in the order of WYWW.
func (lhs Vec4f) SwizzleWYWW() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[1],
		lhs[3],
		lhs[3],
	}
}

// SwizzleWZXX returns a new vector with the components of this
// vector in the order of WZXX.
func (lhs Vec4f) SwizzleWZXX() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleWZXY returns a new vector with the components of this
// vector in the order of WZXY.
func (lhs Vec4f) SwizzleWZXY() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleWZXZ returns a new vector with the components of this
// vector in the order of WZXZ.
func (lhs Vec4f) SwizzleWZXZ() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleWZXW returns a new vector with the components of this
// vector in the order of WZXW.
func (lhs Vec4f) SwizzleWZXW() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[2],
		lhs[0],
		lhs[3],
	}
}

// SwizzleWZYX returns a new vector with the components of this
// vector in the order of WZYX.
func (lhs Vec4f) SwizzleWZYX() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleWZYY returns a new vector with the components of this
// vector in the order of WZYY.
func (lhs Vec4f) SwizzleWZYY() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleWZYZ returns a new vector with the components of this
// vector in the order of WZYZ.
func (lhs Vec4f) SwizzleWZYZ() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleWZYW returns a new vector with the components of this
// vector in the order of WZYW.
func (lhs Vec4f) SwizzleWZYW() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[2],
		lhs[1],
		lhs[3],
	}
}

// SwizzleWZZX returns a new vector with the components of this
// vector in the order of WZZX.
func (lhs Vec4f) SwizzleWZZX() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleWZZY returns a new vector with the components of this
// vector in the order of WZZY.
func (lhs Vec4f) SwizzleWZZY() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleWZZZ returns a new vector with the components of this
// vector in the order of WZZZ.
func (lhs Vec4f) SwizzleWZZZ() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

// SwizzleWZZW returns a new vector with the components of this
// vector in the order of WZZW.
func (lhs Vec4f) SwizzleWZZW() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[2],
		lhs[2],
		lhs[3],
	}
}

// SwizzleWZWX returns a new vector with the components of this
// vector in the order of WZWX.
func (lhs Vec4f) SwizzleWZWX() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[2],
		lhs[3],
		lhs[0],
	}
}

// SwizzleWZWY returns a new vector with the components of this
// vector in the order of WZWY.
func (lhs Vec4f) SwizzleWZWY() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[2],
		lhs[3],
		lhs[1],
	}
}

// SwizzleWZWZ returns a new vector with the components of this
// vector in the order of WZWZ.
func (lhs Vec4f) SwizzleWZWZ() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[2],
		lhs[3],
		lhs[2],
	}
}

// SwizzleWZWW returns a new vector with the components of this
// vector in the order of WZWW.
func (lhs Vec4f) SwizzleWZWW() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[2],
		lhs[3],
		lhs[3],
	}
}

// SwizzleWWXX returns a new vector with the components of this
// vector in the order of WWXX.
func (lhs Vec4f) SwizzleWWXX() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[3],
		lhs[0],
		lhs[0],
	}
}

// SwizzleWWXY returns a new vector with the components of this
// vector in the order of WWXY.
func (lhs Vec4f) SwizzleWWXY() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[3],
		lhs[0],
		lhs[1],
	}
}

// SwizzleWWXZ returns a new vector with the components of this
// vector in the order of WWXZ.
func (lhs Vec4f) SwizzleWWXZ() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[3],
		lhs[0],
		lhs[2],
	}
}

// SwizzleWWXW returns a new vector with the components of this
// vector in the order of WWXW.
func (lhs Vec4f) SwizzleWWXW() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[3],
		lhs[0],
		lhs[3],
	}
}

// SwizzleWWYX returns a new vector with the components of this
// vector in the order of WWYX.
func (lhs Vec4f) SwizzleWWYX() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[3],
		lhs[1],
		lhs[0],
	}
}

// SwizzleWWYY returns a new vector with the components of this
// vector in the order of WWYY.
func (lhs Vec4f) SwizzleWWYY() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[3],
		lhs[1],
		lhs[1],
	}
}

// SwizzleWWYZ returns a new vector with the components of this
// vector in the order of WWYZ.
func (lhs Vec4f) SwizzleWWYZ() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[3],
		lhs[1],
		lhs[2],
	}
}

// SwizzleWWYW returns a new vector with the components of this
// vector in the order of WWYW.
func (lhs Vec4f) SwizzleWWYW() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[3],
		lhs[1],
		lhs[3],
	}
}

// SwizzleWWZX returns a new vector with the components of this
// vector in the order of WWZX.
func (lhs Vec4f) SwizzleWWZX() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[3],
		lhs[2],
		lhs[0],
	}
}

// SwizzleWWZY returns a new vector with the components of this
// vector in the order of WWZY.
func (lhs Vec4f) SwizzleWWZY() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[3],
		lhs[2],
		lhs[1],
	}
}

// SwizzleWWZZ returns a new vector with the components of this
// vector in the order of WWZZ.
func (lhs Vec4f) SwizzleWWZZ() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[3],
		lhs[2],
		lhs[2],
	}
}

// SwizzleWWZW returns a new vector with the components of this
// vector in the order of WWZW.
func (lhs Vec4f) SwizzleWWZW() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[3],
		lhs[2],
		lhs[3],
	}
}

// SwizzleWWWX returns a new vector with the components of this
// vector in the order of WWWX.
func (lhs Vec4f) SwizzleWWWX() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[3],
		lhs[3],
		lhs[0],
	}
}

// SwizzleWWWY returns a new vector with the components of this
// vector in the order of WWWY.
func (lhs Vec4f) SwizzleWWWY() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[3],
		lhs[3],
		lhs[1],
	}
}

// SwizzleWWWZ returns a new vector with the components of this
// vector in the order of WWWZ.
func (lhs Vec4f) SwizzleWWWZ() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[3],
		lhs[3],
		lhs[2],
	}
}

// SwizzleWWWW returns a new vector with the components of this
// vector in the order of WWWW.
func (lhs Vec4f) SwizzleWWWW() Vec4f {
	return Vec4f{
		lhs[3],
		lhs[3],
		lhs[3],
		lhs[3],
	}
}

func (lhs Vec4f) XY() (x, y float32) {
	x = lhs[0]
	y = lhs[1]
	return
}

func (lhs Vec4f) XYZ() (x, y, z float32) {
	x = lhs[0]
	y = lhs[1]
	z = lhs[2]
	return
}

func (lhs Vec4f) XYZW() (x, y, z, w float32) {
	x = lhs[0]
	y = lhs[1]
	z = lhs[2]
	w = lhs[3]
	return
}

func (lhs Vec4f) ToVec4f() Vec4f {
	return Vec4f{
		float32(lhs[0]),
		float32(lhs[1]),
		float32(lhs[2]),
		float32(lhs[3]),
	}
}

func (lhs Vec4f) ToWGPU() [4]float32 {
	return [4]float32{
		float32(lhs[0]),
		float32(lhs[1]),
		float32(lhs[2]),
		float32(lhs[3]),
	}
}

func (lhs Vec4f) String() string {
	return fmt.Sprintf(
		"vec4(%v, %v, %v, %v)",
		lhs[0],
		lhs[1],
		lhs[2],
		lhs[3],
	)
}
