// Code generated by generate.go: DO NOT EDIT.

package glm

import "fmt"
import "math"

// Vec4uh is a vector of dimension 4.
type Vec4uh [4]uint16

func (lhs Vec4uh) Dot(rhs Vec4uh) uint16 {
	return lhs[0]*rhs[0] + lhs[1]*rhs[1] + lhs[2]*rhs[2] + lhs[3]*rhs[3]
}

func (lhs Vec4uh) LengthSqr() uint16 {
	return lhs.Dot(lhs)
}

func (lhs Vec4uh) Length() uint16 {
	return uint16(math.Sqrt(float64(lhs.Dot(lhs))))
}

func (lhs Vec4uh) Normalize() Vec4uh {
	return lhs.Scale(1.0 / lhs.Length())
}

func (lhs Vec4uh) Scale(s uint16) Vec4uh {
	return Vec4uh{
		lhs[0] * s,
		lhs[1] * s,
		lhs[2] * s,
		lhs[3] * s,
	}
}

func (lhs Vec4uh) Reciprocal() Vec4uh {
	return Vec4uh{
		1.0 / lhs[0],
		1.0 / lhs[1],
		1.0 / lhs[2],
		1.0 / lhs[3],
	}
}

func (lhs Vec4uh) Add(rhs Vec4uh) Vec4uh {
	return Vec4uh{
		lhs[0] + rhs[0],
		lhs[1] + rhs[1],
		lhs[2] + rhs[2],
		lhs[3] + rhs[3],
	}
}

func (lhs Vec4uh) Sub(rhs Vec4uh) Vec4uh {
	return Vec4uh{
		lhs[0] - rhs[0],
		lhs[1] - rhs[1],
		lhs[2] - rhs[2],
		lhs[3] - rhs[3],
	}
}

func (lhs Vec4uh) Mul(rhs Vec4uh) Vec4uh {
	return Vec4uh{
		lhs[0] * rhs[0],
		lhs[1] * rhs[1],
		lhs[2] * rhs[2],
		lhs[3] * rhs[3],
	}
}

func (lhs Vec4uh) Div(rhs Vec4uh) Vec4uh {
	return Vec4uh{
		lhs[0] / rhs[0],
		lhs[1] / rhs[1],
		lhs[2] / rhs[2],
		lhs[3] / rhs[3],
	}
}

func (lhs Vec4uh) Min(rhs Vec4uh) Vec4uh {
	return Vec4uh{
		min(lhs[0], rhs[0]),
		min(lhs[1], rhs[1]),
		min(lhs[2], rhs[2]),
		min(lhs[3], rhs[3]),
	}
}

func (lhs Vec4uh) Max(rhs Vec4uh) Vec4uh {
	return Vec4uh{
		max(lhs[0], rhs[0]),
		max(lhs[1], rhs[1]),
		max(lhs[2], rhs[2]),
		max(lhs[3], rhs[3]),
	}
}

func (lhs Vec4uh) Truncate() Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXX returns a new vector with the components of this
// vector in the order of XX.
func (lhs Vec4uh) SwizzleXX() Vec2uh {
	return Vec2uh{
		lhs[0],
		lhs[0],
	}
}

// SwizzleXY returns a new vector with the components of this
// vector in the order of XY.
func (lhs Vec4uh) SwizzleXY() Vec2uh {
	return Vec2uh{
		lhs[0],
		lhs[1],
	}
}

// SwizzleXZ returns a new vector with the components of this
// vector in the order of XZ.
func (lhs Vec4uh) SwizzleXZ() Vec2uh {
	return Vec2uh{
		lhs[0],
		lhs[2],
	}
}

// SwizzleXW returns a new vector with the components of this
// vector in the order of XW.
func (lhs Vec4uh) SwizzleXW() Vec2uh {
	return Vec2uh{
		lhs[0],
		lhs[3],
	}
}

// SwizzleYX returns a new vector with the components of this
// vector in the order of YX.
func (lhs Vec4uh) SwizzleYX() Vec2uh {
	return Vec2uh{
		lhs[1],
		lhs[0],
	}
}

// SwizzleYY returns a new vector with the components of this
// vector in the order of YY.
func (lhs Vec4uh) SwizzleYY() Vec2uh {
	return Vec2uh{
		lhs[1],
		lhs[1],
	}
}

// SwizzleYZ returns a new vector with the components of this
// vector in the order of YZ.
func (lhs Vec4uh) SwizzleYZ() Vec2uh {
	return Vec2uh{
		lhs[1],
		lhs[2],
	}
}

// SwizzleYW returns a new vector with the components of this
// vector in the order of YW.
func (lhs Vec4uh) SwizzleYW() Vec2uh {
	return Vec2uh{
		lhs[1],
		lhs[3],
	}
}

// SwizzleZX returns a new vector with the components of this
// vector in the order of ZX.
func (lhs Vec4uh) SwizzleZX() Vec2uh {
	return Vec2uh{
		lhs[2],
		lhs[0],
	}
}

// SwizzleZY returns a new vector with the components of this
// vector in the order of ZY.
func (lhs Vec4uh) SwizzleZY() Vec2uh {
	return Vec2uh{
		lhs[2],
		lhs[1],
	}
}

// SwizzleZZ returns a new vector with the components of this
// vector in the order of ZZ.
func (lhs Vec4uh) SwizzleZZ() Vec2uh {
	return Vec2uh{
		lhs[2],
		lhs[2],
	}
}

// SwizzleZW returns a new vector with the components of this
// vector in the order of ZW.
func (lhs Vec4uh) SwizzleZW() Vec2uh {
	return Vec2uh{
		lhs[2],
		lhs[3],
	}
}

// SwizzleWX returns a new vector with the components of this
// vector in the order of WX.
func (lhs Vec4uh) SwizzleWX() Vec2uh {
	return Vec2uh{
		lhs[3],
		lhs[0],
	}
}

// SwizzleWY returns a new vector with the components of this
// vector in the order of WY.
func (lhs Vec4uh) SwizzleWY() Vec2uh {
	return Vec2uh{
		lhs[3],
		lhs[1],
	}
}

// SwizzleWZ returns a new vector with the components of this
// vector in the order of WZ.
func (lhs Vec4uh) SwizzleWZ() Vec2uh {
	return Vec2uh{
		lhs[3],
		lhs[2],
	}
}

// SwizzleWW returns a new vector with the components of this
// vector in the order of WW.
func (lhs Vec4uh) SwizzleWW() Vec2uh {
	return Vec2uh{
		lhs[3],
		lhs[3],
	}
}

// SwizzleXXX returns a new vector with the components of this
// vector in the order of XXX.
func (lhs Vec4uh) SwizzleXXX() Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXXY returns a new vector with the components of this
// vector in the order of XXY.
func (lhs Vec4uh) SwizzleXXY() Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXXZ returns a new vector with the components of this
// vector in the order of XXZ.
func (lhs Vec4uh) SwizzleXXZ() Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXXW returns a new vector with the components of this
// vector in the order of XXW.
func (lhs Vec4uh) SwizzleXXW() Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[0],
		lhs[3],
	}
}

// SwizzleXYX returns a new vector with the components of this
// vector in the order of XYX.
func (lhs Vec4uh) SwizzleXYX() Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXYY returns a new vector with the components of this
// vector in the order of XYY.
func (lhs Vec4uh) SwizzleXYY() Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXYZ returns a new vector with the components of this
// vector in the order of XYZ.
func (lhs Vec4uh) SwizzleXYZ() Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXYW returns a new vector with the components of this
// vector in the order of XYW.
func (lhs Vec4uh) SwizzleXYW() Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[1],
		lhs[3],
	}
}

// SwizzleXZX returns a new vector with the components of this
// vector in the order of XZX.
func (lhs Vec4uh) SwizzleXZX() Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXZY returns a new vector with the components of this
// vector in the order of XZY.
func (lhs Vec4uh) SwizzleXZY() Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXZZ returns a new vector with the components of this
// vector in the order of XZZ.
func (lhs Vec4uh) SwizzleXZZ() Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleXZW returns a new vector with the components of this
// vector in the order of XZW.
func (lhs Vec4uh) SwizzleXZW() Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[2],
		lhs[3],
	}
}

// SwizzleXWX returns a new vector with the components of this
// vector in the order of XWX.
func (lhs Vec4uh) SwizzleXWX() Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[3],
		lhs[0],
	}
}

// SwizzleXWY returns a new vector with the components of this
// vector in the order of XWY.
func (lhs Vec4uh) SwizzleXWY() Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[3],
		lhs[1],
	}
}

// SwizzleXWZ returns a new vector with the components of this
// vector in the order of XWZ.
func (lhs Vec4uh) SwizzleXWZ() Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[3],
		lhs[2],
	}
}

// SwizzleXWW returns a new vector with the components of this
// vector in the order of XWW.
func (lhs Vec4uh) SwizzleXWW() Vec3uh {
	return Vec3uh{
		lhs[0],
		lhs[3],
		lhs[3],
	}
}

// SwizzleYXX returns a new vector with the components of this
// vector in the order of YXX.
func (lhs Vec4uh) SwizzleYXX() Vec3uh {
	return Vec3uh{
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYXY returns a new vector with the components of this
// vector in the order of YXY.
func (lhs Vec4uh) SwizzleYXY() Vec3uh {
	return Vec3uh{
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYXZ returns a new vector with the components of this
// vector in the order of YXZ.
func (lhs Vec4uh) SwizzleYXZ() Vec3uh {
	return Vec3uh{
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYXW returns a new vector with the components of this
// vector in the order of YXW.
func (lhs Vec4uh) SwizzleYXW() Vec3uh {
	return Vec3uh{
		lhs[1],
		lhs[0],
		lhs[3],
	}
}

// SwizzleYYX returns a new vector with the components of this
// vector in the order of YYX.
func (lhs Vec4uh) SwizzleYYX() Vec3uh {
	return Vec3uh{
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYYY returns a new vector with the components of this
// vector in the order of YYY.
func (lhs Vec4uh) SwizzleYYY() Vec3uh {
	return Vec3uh{
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYYZ returns a new vector with the components of this
// vector in the order of YYZ.
func (lhs Vec4uh) SwizzleYYZ() Vec3uh {
	return Vec3uh{
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYYW returns a new vector with the components of this
// vector in the order of YYW.
func (lhs Vec4uh) SwizzleYYW() Vec3uh {
	return Vec3uh{
		lhs[1],
		lhs[1],
		lhs[3],
	}
}

// SwizzleYZX returns a new vector with the components of this
// vector in the order of YZX.
func (lhs Vec4uh) SwizzleYZX() Vec3uh {
	return Vec3uh{
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYZY returns a new vector with the components of this
// vector in the order of YZY.
func (lhs Vec4uh) SwizzleYZY() Vec3uh {
	return Vec3uh{
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYZZ returns a new vector with the components of this
// vector in the order of YZZ.
func (lhs Vec4uh) SwizzleYZZ() Vec3uh {
	return Vec3uh{
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYZW returns a new vector with the components of this
// vector in the order of YZW.
func (lhs Vec4uh) SwizzleYZW() Vec3uh {
	return Vec3uh{
		lhs[1],
		lhs[2],
		lhs[3],
	}
}

// SwizzleYWX returns a new vector with the components of this
// vector in the order of YWX.
func (lhs Vec4uh) SwizzleYWX() Vec3uh {
	return Vec3uh{
		lhs[1],
		lhs[3],
		lhs[0],
	}
}

// SwizzleYWY returns a new vector with the components of this
// vector in the order of YWY.
func (lhs Vec4uh) SwizzleYWY() Vec3uh {
	return Vec3uh{
		lhs[1],
		lhs[3],
		lhs[1],
	}
}

// SwizzleYWZ returns a new vector with the components of this
// vector in the order of YWZ.
func (lhs Vec4uh) SwizzleYWZ() Vec3uh {
	return Vec3uh{
		lhs[1],
		lhs[3],
		lhs[2],
	}
}

// SwizzleYWW returns a new vector with the components of this
// vector in the order of YWW.
func (lhs Vec4uh) SwizzleYWW() Vec3uh {
	return Vec3uh{
		lhs[1],
		lhs[3],
		lhs[3],
	}
}

// SwizzleZXX returns a new vector with the components of this
// vector in the order of ZXX.
func (lhs Vec4uh) SwizzleZXX() Vec3uh {
	return Vec3uh{
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZXY returns a new vector with the components of this
// vector in the order of ZXY.
func (lhs Vec4uh) SwizzleZXY() Vec3uh {
	return Vec3uh{
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZXZ returns a new vector with the components of this
// vector in the order of ZXZ.
func (lhs Vec4uh) SwizzleZXZ() Vec3uh {
	return Vec3uh{
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZXW returns a new vector with the components of this
// vector in the order of ZXW.
func (lhs Vec4uh) SwizzleZXW() Vec3uh {
	return Vec3uh{
		lhs[2],
		lhs[0],
		lhs[3],
	}
}

// SwizzleZYX returns a new vector with the components of this
// vector in the order of ZYX.
func (lhs Vec4uh) SwizzleZYX() Vec3uh {
	return Vec3uh{
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZYY returns a new vector with the components of this
// vector in the order of ZYY.
func (lhs Vec4uh) SwizzleZYY() Vec3uh {
	return Vec3uh{
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZYZ returns a new vector with the components of this
// vector in the order of ZYZ.
func (lhs Vec4uh) SwizzleZYZ() Vec3uh {
	return Vec3uh{
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZYW returns a new vector with the components of this
// vector in the order of ZYW.
func (lhs Vec4uh) SwizzleZYW() Vec3uh {
	return Vec3uh{
		lhs[2],
		lhs[1],
		lhs[3],
	}
}

// SwizzleZZX returns a new vector with the components of this
// vector in the order of ZZX.
func (lhs Vec4uh) SwizzleZZX() Vec3uh {
	return Vec3uh{
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZZY returns a new vector with the components of this
// vector in the order of ZZY.
func (lhs Vec4uh) SwizzleZZY() Vec3uh {
	return Vec3uh{
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZZZ returns a new vector with the components of this
// vector in the order of ZZZ.
func (lhs Vec4uh) SwizzleZZZ() Vec3uh {
	return Vec3uh{
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZZW returns a new vector with the components of this
// vector in the order of ZZW.
func (lhs Vec4uh) SwizzleZZW() Vec3uh {
	return Vec3uh{
		lhs[2],
		lhs[2],
		lhs[3],
	}
}

// SwizzleZWX returns a new vector with the components of this
// vector in the order of ZWX.
func (lhs Vec4uh) SwizzleZWX() Vec3uh {
	return Vec3uh{
		lhs[2],
		lhs[3],
		lhs[0],
	}
}

// SwizzleZWY returns a new vector with the components of this
// vector in the order of ZWY.
func (lhs Vec4uh) SwizzleZWY() Vec3uh {
	return Vec3uh{
		lhs[2],
		lhs[3],
		lhs[1],
	}
}

// SwizzleZWZ returns a new vector with the components of this
// vector in the order of ZWZ.
func (lhs Vec4uh) SwizzleZWZ() Vec3uh {
	return Vec3uh{
		lhs[2],
		lhs[3],
		lhs[2],
	}
}

// SwizzleZWW returns a new vector with the components of this
// vector in the order of ZWW.
func (lhs Vec4uh) SwizzleZWW() Vec3uh {
	return Vec3uh{
		lhs[2],
		lhs[3],
		lhs[3],
	}
}

// SwizzleWXX returns a new vector with the components of this
// vector in the order of WXX.
func (lhs Vec4uh) SwizzleWXX() Vec3uh {
	return Vec3uh{
		lhs[3],
		lhs[0],
		lhs[0],
	}
}

// SwizzleWXY returns a new vector with the components of this
// vector in the order of WXY.
func (lhs Vec4uh) SwizzleWXY() Vec3uh {
	return Vec3uh{
		lhs[3],
		lhs[0],
		lhs[1],
	}
}

// SwizzleWXZ returns a new vector with the components of this
// vector in the order of WXZ.
func (lhs Vec4uh) SwizzleWXZ() Vec3uh {
	return Vec3uh{
		lhs[3],
		lhs[0],
		lhs[2],
	}
}

// SwizzleWXW returns a new vector with the components of this
// vector in the order of WXW.
func (lhs Vec4uh) SwizzleWXW() Vec3uh {
	return Vec3uh{
		lhs[3],
		lhs[0],
		lhs[3],
	}
}

// SwizzleWYX returns a new vector with the components of this
// vector in the order of WYX.
func (lhs Vec4uh) SwizzleWYX() Vec3uh {
	return Vec3uh{
		lhs[3],
		lhs[1],
		lhs[0],
	}
}

// SwizzleWYY returns a new vector with the components of this
// vector in the order of WYY.
func (lhs Vec4uh) SwizzleWYY() Vec3uh {
	return Vec3uh{
		lhs[3],
		lhs[1],
		lhs[1],
	}
}

// SwizzleWYZ returns a new vector with the components of this
// vector in the order of WYZ.
func (lhs Vec4uh) SwizzleWYZ() Vec3uh {
	return Vec3uh{
		lhs[3],
		lhs[1],
		lhs[2],
	}
}

// SwizzleWYW returns a new vector with the components of this
// vector in the order of WYW.
func (lhs Vec4uh) SwizzleWYW() Vec3uh {
	return Vec3uh{
		lhs[3],
		lhs[1],
		lhs[3],
	}
}

// SwizzleWZX returns a new vector with the components of this
// vector in the order of WZX.
func (lhs Vec4uh) SwizzleWZX() Vec3uh {
	return Vec3uh{
		lhs[3],
		lhs[2],
		lhs[0],
	}
}

// SwizzleWZY returns a new vector with the components of this
// vector in the order of WZY.
func (lhs Vec4uh) SwizzleWZY() Vec3uh {
	return Vec3uh{
		lhs[3],
		lhs[2],
		lhs[1],
	}
}

// SwizzleWZZ returns a new vector with the components of this
// vector in the order of WZZ.
func (lhs Vec4uh) SwizzleWZZ() Vec3uh {
	return Vec3uh{
		lhs[3],
		lhs[2],
		lhs[2],
	}
}

// SwizzleWZW returns a new vector with the components of this
// vector in the order of WZW.
func (lhs Vec4uh) SwizzleWZW() Vec3uh {
	return Vec3uh{
		lhs[3],
		lhs[2],
		lhs[3],
	}
}

// SwizzleWWX returns a new vector with the components of this
// vector in the order of WWX.
func (lhs Vec4uh) SwizzleWWX() Vec3uh {
	return Vec3uh{
		lhs[3],
		lhs[3],
		lhs[0],
	}
}

// SwizzleWWY returns a new vector with the components of this
// vector in the order of WWY.
func (lhs Vec4uh) SwizzleWWY() Vec3uh {
	return Vec3uh{
		lhs[3],
		lhs[3],
		lhs[1],
	}
}

// SwizzleWWZ returns a new vector with the components of this
// vector in the order of WWZ.
func (lhs Vec4uh) SwizzleWWZ() Vec3uh {
	return Vec3uh{
		lhs[3],
		lhs[3],
		lhs[2],
	}
}

// SwizzleWWW returns a new vector with the components of this
// vector in the order of WWW.
func (lhs Vec4uh) SwizzleWWW() Vec3uh {
	return Vec3uh{
		lhs[3],
		lhs[3],
		lhs[3],
	}
}

// SwizzleXXXX returns a new vector with the components of this
// vector in the order of XXXX.
func (lhs Vec4uh) SwizzleXXXX() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXXXY returns a new vector with the components of this
// vector in the order of XXXY.
func (lhs Vec4uh) SwizzleXXXY() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXXXZ returns a new vector with the components of this
// vector in the order of XXXZ.
func (lhs Vec4uh) SwizzleXXXZ() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXXXW returns a new vector with the components of this
// vector in the order of XXXW.
func (lhs Vec4uh) SwizzleXXXW() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[0],
		lhs[0],
		lhs[3],
	}
}

// SwizzleXXYX returns a new vector with the components of this
// vector in the order of XXYX.
func (lhs Vec4uh) SwizzleXXYX() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXXYY returns a new vector with the components of this
// vector in the order of XXYY.
func (lhs Vec4uh) SwizzleXXYY() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXXYZ returns a new vector with the components of this
// vector in the order of XXYZ.
func (lhs Vec4uh) SwizzleXXYZ() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXXYW returns a new vector with the components of this
// vector in the order of XXYW.
func (lhs Vec4uh) SwizzleXXYW() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[0],
		lhs[1],
		lhs[3],
	}
}

// SwizzleXXZX returns a new vector with the components of this
// vector in the order of XXZX.
func (lhs Vec4uh) SwizzleXXZX() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXXZY returns a new vector with the components of this
// vector in the order of XXZY.
func (lhs Vec4uh) SwizzleXXZY() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXXZZ returns a new vector with the components of this
// vector in the order of XXZZ.
func (lhs Vec4uh) SwizzleXXZZ() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleXXZW returns a new vector with the components of this
// vector in the order of XXZW.
func (lhs Vec4uh) SwizzleXXZW() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[0],
		lhs[2],
		lhs[3],
	}
}

// SwizzleXXWX returns a new vector with the components of this
// vector in the order of XXWX.
func (lhs Vec4uh) SwizzleXXWX() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[0],
		lhs[3],
		lhs[0],
	}
}

// SwizzleXXWY returns a new vector with the components of this
// vector in the order of XXWY.
func (lhs Vec4uh) SwizzleXXWY() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[0],
		lhs[3],
		lhs[1],
	}
}

// SwizzleXXWZ returns a new vector with the components of this
// vector in the order of XXWZ.
func (lhs Vec4uh) SwizzleXXWZ() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[0],
		lhs[3],
		lhs[2],
	}
}

// SwizzleXXWW returns a new vector with the components of this
// vector in the order of XXWW.
func (lhs Vec4uh) SwizzleXXWW() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[0],
		lhs[3],
		lhs[3],
	}
}

// SwizzleXYXX returns a new vector with the components of this
// vector in the order of XYXX.
func (lhs Vec4uh) SwizzleXYXX() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXYXY returns a new vector with the components of this
// vector in the order of XYXY.
func (lhs Vec4uh) SwizzleXYXY() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXYXZ returns a new vector with the components of this
// vector in the order of XYXZ.
func (lhs Vec4uh) SwizzleXYXZ() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXYXW returns a new vector with the components of this
// vector in the order of XYXW.
func (lhs Vec4uh) SwizzleXYXW() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[1],
		lhs[0],
		lhs[3],
	}
}

// SwizzleXYYX returns a new vector with the components of this
// vector in the order of XYYX.
func (lhs Vec4uh) SwizzleXYYX() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXYYY returns a new vector with the components of this
// vector in the order of XYYY.
func (lhs Vec4uh) SwizzleXYYY() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXYYZ returns a new vector with the components of this
// vector in the order of XYYZ.
func (lhs Vec4uh) SwizzleXYYZ() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXYYW returns a new vector with the components of this
// vector in the order of XYYW.
func (lhs Vec4uh) SwizzleXYYW() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[1],
		lhs[1],
		lhs[3],
	}
}

// SwizzleXYZX returns a new vector with the components of this
// vector in the order of XYZX.
func (lhs Vec4uh) SwizzleXYZX() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXYZY returns a new vector with the components of this
// vector in the order of XYZY.
func (lhs Vec4uh) SwizzleXYZY() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXYZZ returns a new vector with the components of this
// vector in the order of XYZZ.
func (lhs Vec4uh) SwizzleXYZZ() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleXYZW returns a new vector with the components of this
// vector in the order of XYZW.
func (lhs Vec4uh) SwizzleXYZW() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[1],
		lhs[2],
		lhs[3],
	}
}

// SwizzleXYWX returns a new vector with the components of this
// vector in the order of XYWX.
func (lhs Vec4uh) SwizzleXYWX() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[1],
		lhs[3],
		lhs[0],
	}
}

// SwizzleXYWY returns a new vector with the components of this
// vector in the order of XYWY.
func (lhs Vec4uh) SwizzleXYWY() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[1],
		lhs[3],
		lhs[1],
	}
}

// SwizzleXYWZ returns a new vector with the components of this
// vector in the order of XYWZ.
func (lhs Vec4uh) SwizzleXYWZ() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[1],
		lhs[3],
		lhs[2],
	}
}

// SwizzleXYWW returns a new vector with the components of this
// vector in the order of XYWW.
func (lhs Vec4uh) SwizzleXYWW() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[1],
		lhs[3],
		lhs[3],
	}
}

// SwizzleXZXX returns a new vector with the components of this
// vector in the order of XZXX.
func (lhs Vec4uh) SwizzleXZXX() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXZXY returns a new vector with the components of this
// vector in the order of XZXY.
func (lhs Vec4uh) SwizzleXZXY() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXZXZ returns a new vector with the components of this
// vector in the order of XZXZ.
func (lhs Vec4uh) SwizzleXZXZ() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXZXW returns a new vector with the components of this
// vector in the order of XZXW.
func (lhs Vec4uh) SwizzleXZXW() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[2],
		lhs[0],
		lhs[3],
	}
}

// SwizzleXZYX returns a new vector with the components of this
// vector in the order of XZYX.
func (lhs Vec4uh) SwizzleXZYX() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXZYY returns a new vector with the components of this
// vector in the order of XZYY.
func (lhs Vec4uh) SwizzleXZYY() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXZYZ returns a new vector with the components of this
// vector in the order of XZYZ.
func (lhs Vec4uh) SwizzleXZYZ() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXZYW returns a new vector with the components of this
// vector in the order of XZYW.
func (lhs Vec4uh) SwizzleXZYW() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[2],
		lhs[1],
		lhs[3],
	}
}

// SwizzleXZZX returns a new vector with the components of this
// vector in the order of XZZX.
func (lhs Vec4uh) SwizzleXZZX() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXZZY returns a new vector with the components of this
// vector in the order of XZZY.
func (lhs Vec4uh) SwizzleXZZY() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXZZZ returns a new vector with the components of this
// vector in the order of XZZZ.
func (lhs Vec4uh) SwizzleXZZZ() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

// SwizzleXZZW returns a new vector with the components of this
// vector in the order of XZZW.
func (lhs Vec4uh) SwizzleXZZW() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[2],
		lhs[2],
		lhs[3],
	}
}

// SwizzleXZWX returns a new vector with the components of this
// vector in the order of XZWX.
func (lhs Vec4uh) SwizzleXZWX() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[2],
		lhs[3],
		lhs[0],
	}
}

// SwizzleXZWY returns a new vector with the components of this
// vector in the order of XZWY.
func (lhs Vec4uh) SwizzleXZWY() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[2],
		lhs[3],
		lhs[1],
	}
}

// SwizzleXZWZ returns a new vector with the components of this
// vector in the order of XZWZ.
func (lhs Vec4uh) SwizzleXZWZ() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[2],
		lhs[3],
		lhs[2],
	}
}

// SwizzleXZWW returns a new vector with the components of this
// vector in the order of XZWW.
func (lhs Vec4uh) SwizzleXZWW() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[2],
		lhs[3],
		lhs[3],
	}
}

// SwizzleXWXX returns a new vector with the components of this
// vector in the order of XWXX.
func (lhs Vec4uh) SwizzleXWXX() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[3],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXWXY returns a new vector with the components of this
// vector in the order of XWXY.
func (lhs Vec4uh) SwizzleXWXY() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[3],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXWXZ returns a new vector with the components of this
// vector in the order of XWXZ.
func (lhs Vec4uh) SwizzleXWXZ() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[3],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXWXW returns a new vector with the components of this
// vector in the order of XWXW.
func (lhs Vec4uh) SwizzleXWXW() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[3],
		lhs[0],
		lhs[3],
	}
}

// SwizzleXWYX returns a new vector with the components of this
// vector in the order of XWYX.
func (lhs Vec4uh) SwizzleXWYX() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[3],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXWYY returns a new vector with the components of this
// vector in the order of XWYY.
func (lhs Vec4uh) SwizzleXWYY() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[3],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXWYZ returns a new vector with the components of this
// vector in the order of XWYZ.
func (lhs Vec4uh) SwizzleXWYZ() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[3],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXWYW returns a new vector with the components of this
// vector in the order of XWYW.
func (lhs Vec4uh) SwizzleXWYW() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[3],
		lhs[1],
		lhs[3],
	}
}

// SwizzleXWZX returns a new vector with the components of this
// vector in the order of XWZX.
func (lhs Vec4uh) SwizzleXWZX() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[3],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXWZY returns a new vector with the components of this
// vector in the order of XWZY.
func (lhs Vec4uh) SwizzleXWZY() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[3],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXWZZ returns a new vector with the components of this
// vector in the order of XWZZ.
func (lhs Vec4uh) SwizzleXWZZ() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[3],
		lhs[2],
		lhs[2],
	}
}

// SwizzleXWZW returns a new vector with the components of this
// vector in the order of XWZW.
func (lhs Vec4uh) SwizzleXWZW() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[3],
		lhs[2],
		lhs[3],
	}
}

// SwizzleXWWX returns a new vector with the components of this
// vector in the order of XWWX.
func (lhs Vec4uh) SwizzleXWWX() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[3],
		lhs[3],
		lhs[0],
	}
}

// SwizzleXWWY returns a new vector with the components of this
// vector in the order of XWWY.
func (lhs Vec4uh) SwizzleXWWY() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[3],
		lhs[3],
		lhs[1],
	}
}

// SwizzleXWWZ returns a new vector with the components of this
// vector in the order of XWWZ.
func (lhs Vec4uh) SwizzleXWWZ() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[3],
		lhs[3],
		lhs[2],
	}
}

// SwizzleXWWW returns a new vector with the components of this
// vector in the order of XWWW.
func (lhs Vec4uh) SwizzleXWWW() Vec4uh {
	return Vec4uh{
		lhs[0],
		lhs[3],
		lhs[3],
		lhs[3],
	}
}

// SwizzleYXXX returns a new vector with the components of this
// vector in the order of YXXX.
func (lhs Vec4uh) SwizzleYXXX() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYXXY returns a new vector with the components of this
// vector in the order of YXXY.
func (lhs Vec4uh) SwizzleYXXY() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYXXZ returns a new vector with the components of this
// vector in the order of YXXZ.
func (lhs Vec4uh) SwizzleYXXZ() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYXXW returns a new vector with the components of this
// vector in the order of YXXW.
func (lhs Vec4uh) SwizzleYXXW() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[0],
		lhs[0],
		lhs[3],
	}
}

// SwizzleYXYX returns a new vector with the components of this
// vector in the order of YXYX.
func (lhs Vec4uh) SwizzleYXYX() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYXYY returns a new vector with the components of this
// vector in the order of YXYY.
func (lhs Vec4uh) SwizzleYXYY() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYXYZ returns a new vector with the components of this
// vector in the order of YXYZ.
func (lhs Vec4uh) SwizzleYXYZ() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYXYW returns a new vector with the components of this
// vector in the order of YXYW.
func (lhs Vec4uh) SwizzleYXYW() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[0],
		lhs[1],
		lhs[3],
	}
}

// SwizzleYXZX returns a new vector with the components of this
// vector in the order of YXZX.
func (lhs Vec4uh) SwizzleYXZX() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYXZY returns a new vector with the components of this
// vector in the order of YXZY.
func (lhs Vec4uh) SwizzleYXZY() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYXZZ returns a new vector with the components of this
// vector in the order of YXZZ.
func (lhs Vec4uh) SwizzleYXZZ() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYXZW returns a new vector with the components of this
// vector in the order of YXZW.
func (lhs Vec4uh) SwizzleYXZW() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[0],
		lhs[2],
		lhs[3],
	}
}

// SwizzleYXWX returns a new vector with the components of this
// vector in the order of YXWX.
func (lhs Vec4uh) SwizzleYXWX() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[0],
		lhs[3],
		lhs[0],
	}
}

// SwizzleYXWY returns a new vector with the components of this
// vector in the order of YXWY.
func (lhs Vec4uh) SwizzleYXWY() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[0],
		lhs[3],
		lhs[1],
	}
}

// SwizzleYXWZ returns a new vector with the components of this
// vector in the order of YXWZ.
func (lhs Vec4uh) SwizzleYXWZ() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[0],
		lhs[3],
		lhs[2],
	}
}

// SwizzleYXWW returns a new vector with the components of this
// vector in the order of YXWW.
func (lhs Vec4uh) SwizzleYXWW() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[0],
		lhs[3],
		lhs[3],
	}
}

// SwizzleYYXX returns a new vector with the components of this
// vector in the order of YYXX.
func (lhs Vec4uh) SwizzleYYXX() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYYXY returns a new vector with the components of this
// vector in the order of YYXY.
func (lhs Vec4uh) SwizzleYYXY() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYYXZ returns a new vector with the components of this
// vector in the order of YYXZ.
func (lhs Vec4uh) SwizzleYYXZ() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYYXW returns a new vector with the components of this
// vector in the order of YYXW.
func (lhs Vec4uh) SwizzleYYXW() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[1],
		lhs[0],
		lhs[3],
	}
}

// SwizzleYYYX returns a new vector with the components of this
// vector in the order of YYYX.
func (lhs Vec4uh) SwizzleYYYX() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYYYY returns a new vector with the components of this
// vector in the order of YYYY.
func (lhs Vec4uh) SwizzleYYYY() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYYYZ returns a new vector with the components of this
// vector in the order of YYYZ.
func (lhs Vec4uh) SwizzleYYYZ() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYYYW returns a new vector with the components of this
// vector in the order of YYYW.
func (lhs Vec4uh) SwizzleYYYW() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[1],
		lhs[1],
		lhs[3],
	}
}

// SwizzleYYZX returns a new vector with the components of this
// vector in the order of YYZX.
func (lhs Vec4uh) SwizzleYYZX() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYYZY returns a new vector with the components of this
// vector in the order of YYZY.
func (lhs Vec4uh) SwizzleYYZY() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYYZZ returns a new vector with the components of this
// vector in the order of YYZZ.
func (lhs Vec4uh) SwizzleYYZZ() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYYZW returns a new vector with the components of this
// vector in the order of YYZW.
func (lhs Vec4uh) SwizzleYYZW() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[1],
		lhs[2],
		lhs[3],
	}
}

// SwizzleYYWX returns a new vector with the components of this
// vector in the order of YYWX.
func (lhs Vec4uh) SwizzleYYWX() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[1],
		lhs[3],
		lhs[0],
	}
}

// SwizzleYYWY returns a new vector with the components of this
// vector in the order of YYWY.
func (lhs Vec4uh) SwizzleYYWY() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[1],
		lhs[3],
		lhs[1],
	}
}

// SwizzleYYWZ returns a new vector with the components of this
// vector in the order of YYWZ.
func (lhs Vec4uh) SwizzleYYWZ() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[1],
		lhs[3],
		lhs[2],
	}
}

// SwizzleYYWW returns a new vector with the components of this
// vector in the order of YYWW.
func (lhs Vec4uh) SwizzleYYWW() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[1],
		lhs[3],
		lhs[3],
	}
}

// SwizzleYZXX returns a new vector with the components of this
// vector in the order of YZXX.
func (lhs Vec4uh) SwizzleYZXX() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYZXY returns a new vector with the components of this
// vector in the order of YZXY.
func (lhs Vec4uh) SwizzleYZXY() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYZXZ returns a new vector with the components of this
// vector in the order of YZXZ.
func (lhs Vec4uh) SwizzleYZXZ() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYZXW returns a new vector with the components of this
// vector in the order of YZXW.
func (lhs Vec4uh) SwizzleYZXW() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[2],
		lhs[0],
		lhs[3],
	}
}

// SwizzleYZYX returns a new vector with the components of this
// vector in the order of YZYX.
func (lhs Vec4uh) SwizzleYZYX() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYZYY returns a new vector with the components of this
// vector in the order of YZYY.
func (lhs Vec4uh) SwizzleYZYY() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYZYZ returns a new vector with the components of this
// vector in the order of YZYZ.
func (lhs Vec4uh) SwizzleYZYZ() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYZYW returns a new vector with the components of this
// vector in the order of YZYW.
func (lhs Vec4uh) SwizzleYZYW() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[2],
		lhs[1],
		lhs[3],
	}
}

// SwizzleYZZX returns a new vector with the components of this
// vector in the order of YZZX.
func (lhs Vec4uh) SwizzleYZZX() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYZZY returns a new vector with the components of this
// vector in the order of YZZY.
func (lhs Vec4uh) SwizzleYZZY() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYZZZ returns a new vector with the components of this
// vector in the order of YZZZ.
func (lhs Vec4uh) SwizzleYZZZ() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYZZW returns a new vector with the components of this
// vector in the order of YZZW.
func (lhs Vec4uh) SwizzleYZZW() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[2],
		lhs[2],
		lhs[3],
	}
}

// SwizzleYZWX returns a new vector with the components of this
// vector in the order of YZWX.
func (lhs Vec4uh) SwizzleYZWX() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[2],
		lhs[3],
		lhs[0],
	}
}

// SwizzleYZWY returns a new vector with the components of this
// vector in the order of YZWY.
func (lhs Vec4uh) SwizzleYZWY() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[2],
		lhs[3],
		lhs[1],
	}
}

// SwizzleYZWZ returns a new vector with the components of this
// vector in the order of YZWZ.
func (lhs Vec4uh) SwizzleYZWZ() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[2],
		lhs[3],
		lhs[2],
	}
}

// SwizzleYZWW returns a new vector with the components of this
// vector in the order of YZWW.
func (lhs Vec4uh) SwizzleYZWW() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[2],
		lhs[3],
		lhs[3],
	}
}

// SwizzleYWXX returns a new vector with the components of this
// vector in the order of YWXX.
func (lhs Vec4uh) SwizzleYWXX() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[3],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYWXY returns a new vector with the components of this
// vector in the order of YWXY.
func (lhs Vec4uh) SwizzleYWXY() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[3],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYWXZ returns a new vector with the components of this
// vector in the order of YWXZ.
func (lhs Vec4uh) SwizzleYWXZ() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[3],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYWXW returns a new vector with the components of this
// vector in the order of YWXW.
func (lhs Vec4uh) SwizzleYWXW() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[3],
		lhs[0],
		lhs[3],
	}
}

// SwizzleYWYX returns a new vector with the components of this
// vector in the order of YWYX.
func (lhs Vec4uh) SwizzleYWYX() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[3],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYWYY returns a new vector with the components of this
// vector in the order of YWYY.
func (lhs Vec4uh) SwizzleYWYY() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[3],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYWYZ returns a new vector with the components of this
// vector in the order of YWYZ.
func (lhs Vec4uh) SwizzleYWYZ() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[3],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYWYW returns a new vector with the components of this
// vector in the order of YWYW.
func (lhs Vec4uh) SwizzleYWYW() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[3],
		lhs[1],
		lhs[3],
	}
}

// SwizzleYWZX returns a new vector with the components of this
// vector in the order of YWZX.
func (lhs Vec4uh) SwizzleYWZX() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[3],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYWZY returns a new vector with the components of this
// vector in the order of YWZY.
func (lhs Vec4uh) SwizzleYWZY() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[3],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYWZZ returns a new vector with the components of this
// vector in the order of YWZZ.
func (lhs Vec4uh) SwizzleYWZZ() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[3],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYWZW returns a new vector with the components of this
// vector in the order of YWZW.
func (lhs Vec4uh) SwizzleYWZW() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[3],
		lhs[2],
		lhs[3],
	}
}

// SwizzleYWWX returns a new vector with the components of this
// vector in the order of YWWX.
func (lhs Vec4uh) SwizzleYWWX() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[3],
		lhs[3],
		lhs[0],
	}
}

// SwizzleYWWY returns a new vector with the components of this
// vector in the order of YWWY.
func (lhs Vec4uh) SwizzleYWWY() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[3],
		lhs[3],
		lhs[1],
	}
}

// SwizzleYWWZ returns a new vector with the components of this
// vector in the order of YWWZ.
func (lhs Vec4uh) SwizzleYWWZ() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[3],
		lhs[3],
		lhs[2],
	}
}

// SwizzleYWWW returns a new vector with the components of this
// vector in the order of YWWW.
func (lhs Vec4uh) SwizzleYWWW() Vec4uh {
	return Vec4uh{
		lhs[1],
		lhs[3],
		lhs[3],
		lhs[3],
	}
}

// SwizzleZXXX returns a new vector with the components of this
// vector in the order of ZXXX.
func (lhs Vec4uh) SwizzleZXXX() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZXXY returns a new vector with the components of this
// vector in the order of ZXXY.
func (lhs Vec4uh) SwizzleZXXY() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZXXZ returns a new vector with the components of this
// vector in the order of ZXXZ.
func (lhs Vec4uh) SwizzleZXXZ() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZXXW returns a new vector with the components of this
// vector in the order of ZXXW.
func (lhs Vec4uh) SwizzleZXXW() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[0],
		lhs[0],
		lhs[3],
	}
}

// SwizzleZXYX returns a new vector with the components of this
// vector in the order of ZXYX.
func (lhs Vec4uh) SwizzleZXYX() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZXYY returns a new vector with the components of this
// vector in the order of ZXYY.
func (lhs Vec4uh) SwizzleZXYY() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZXYZ returns a new vector with the components of this
// vector in the order of ZXYZ.
func (lhs Vec4uh) SwizzleZXYZ() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZXYW returns a new vector with the components of this
// vector in the order of ZXYW.
func (lhs Vec4uh) SwizzleZXYW() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[0],
		lhs[1],
		lhs[3],
	}
}

// SwizzleZXZX returns a new vector with the components of this
// vector in the order of ZXZX.
func (lhs Vec4uh) SwizzleZXZX() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZXZY returns a new vector with the components of this
// vector in the order of ZXZY.
func (lhs Vec4uh) SwizzleZXZY() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZXZZ returns a new vector with the components of this
// vector in the order of ZXZZ.
func (lhs Vec4uh) SwizzleZXZZ() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZXZW returns a new vector with the components of this
// vector in the order of ZXZW.
func (lhs Vec4uh) SwizzleZXZW() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[0],
		lhs[2],
		lhs[3],
	}
}

// SwizzleZXWX returns a new vector with the components of this
// vector in the order of ZXWX.
func (lhs Vec4uh) SwizzleZXWX() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[0],
		lhs[3],
		lhs[0],
	}
}

// SwizzleZXWY returns a new vector with the components of this
// vector in the order of ZXWY.
func (lhs Vec4uh) SwizzleZXWY() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[0],
		lhs[3],
		lhs[1],
	}
}

// SwizzleZXWZ returns a new vector with the components of this
// vector in the order of ZXWZ.
func (lhs Vec4uh) SwizzleZXWZ() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[0],
		lhs[3],
		lhs[2],
	}
}

// SwizzleZXWW returns a new vector with the components of this
// vector in the order of ZXWW.
func (lhs Vec4uh) SwizzleZXWW() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[0],
		lhs[3],
		lhs[3],
	}
}

// SwizzleZYXX returns a new vector with the components of this
// vector in the order of ZYXX.
func (lhs Vec4uh) SwizzleZYXX() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZYXY returns a new vector with the components of this
// vector in the order of ZYXY.
func (lhs Vec4uh) SwizzleZYXY() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZYXZ returns a new vector with the components of this
// vector in the order of ZYXZ.
func (lhs Vec4uh) SwizzleZYXZ() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZYXW returns a new vector with the components of this
// vector in the order of ZYXW.
func (lhs Vec4uh) SwizzleZYXW() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[1],
		lhs[0],
		lhs[3],
	}
}

// SwizzleZYYX returns a new vector with the components of this
// vector in the order of ZYYX.
func (lhs Vec4uh) SwizzleZYYX() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZYYY returns a new vector with the components of this
// vector in the order of ZYYY.
func (lhs Vec4uh) SwizzleZYYY() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZYYZ returns a new vector with the components of this
// vector in the order of ZYYZ.
func (lhs Vec4uh) SwizzleZYYZ() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZYYW returns a new vector with the components of this
// vector in the order of ZYYW.
func (lhs Vec4uh) SwizzleZYYW() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[1],
		lhs[1],
		lhs[3],
	}
}

// SwizzleZYZX returns a new vector with the components of this
// vector in the order of ZYZX.
func (lhs Vec4uh) SwizzleZYZX() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZYZY returns a new vector with the components of this
// vector in the order of ZYZY.
func (lhs Vec4uh) SwizzleZYZY() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZYZZ returns a new vector with the components of this
// vector in the order of ZYZZ.
func (lhs Vec4uh) SwizzleZYZZ() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZYZW returns a new vector with the components of this
// vector in the order of ZYZW.
func (lhs Vec4uh) SwizzleZYZW() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[1],
		lhs[2],
		lhs[3],
	}
}

// SwizzleZYWX returns a new vector with the components of this
// vector in the order of ZYWX.
func (lhs Vec4uh) SwizzleZYWX() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[1],
		lhs[3],
		lhs[0],
	}
}

// SwizzleZYWY returns a new vector with the components of this
// vector in the order of ZYWY.
func (lhs Vec4uh) SwizzleZYWY() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[1],
		lhs[3],
		lhs[1],
	}
}

// SwizzleZYWZ returns a new vector with the components of this
// vector in the order of ZYWZ.
func (lhs Vec4uh) SwizzleZYWZ() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[1],
		lhs[3],
		lhs[2],
	}
}

// SwizzleZYWW returns a new vector with the components of this
// vector in the order of ZYWW.
func (lhs Vec4uh) SwizzleZYWW() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[1],
		lhs[3],
		lhs[3],
	}
}

// SwizzleZZXX returns a new vector with the components of this
// vector in the order of ZZXX.
func (lhs Vec4uh) SwizzleZZXX() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZZXY returns a new vector with the components of this
// vector in the order of ZZXY.
func (lhs Vec4uh) SwizzleZZXY() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZZXZ returns a new vector with the components of this
// vector in the order of ZZXZ.
func (lhs Vec4uh) SwizzleZZXZ() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZZXW returns a new vector with the components of this
// vector in the order of ZZXW.
func (lhs Vec4uh) SwizzleZZXW() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[2],
		lhs[0],
		lhs[3],
	}
}

// SwizzleZZYX returns a new vector with the components of this
// vector in the order of ZZYX.
func (lhs Vec4uh) SwizzleZZYX() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZZYY returns a new vector with the components of this
// vector in the order of ZZYY.
func (lhs Vec4uh) SwizzleZZYY() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZZYZ returns a new vector with the components of this
// vector in the order of ZZYZ.
func (lhs Vec4uh) SwizzleZZYZ() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZZYW returns a new vector with the components of this
// vector in the order of ZZYW.
func (lhs Vec4uh) SwizzleZZYW() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[2],
		lhs[1],
		lhs[3],
	}
}

// SwizzleZZZX returns a new vector with the components of this
// vector in the order of ZZZX.
func (lhs Vec4uh) SwizzleZZZX() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZZZY returns a new vector with the components of this
// vector in the order of ZZZY.
func (lhs Vec4uh) SwizzleZZZY() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZZZZ returns a new vector with the components of this
// vector in the order of ZZZZ.
func (lhs Vec4uh) SwizzleZZZZ() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZZZW returns a new vector with the components of this
// vector in the order of ZZZW.
func (lhs Vec4uh) SwizzleZZZW() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[2],
		lhs[2],
		lhs[3],
	}
}

// SwizzleZZWX returns a new vector with the components of this
// vector in the order of ZZWX.
func (lhs Vec4uh) SwizzleZZWX() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[2],
		lhs[3],
		lhs[0],
	}
}

// SwizzleZZWY returns a new vector with the components of this
// vector in the order of ZZWY.
func (lhs Vec4uh) SwizzleZZWY() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[2],
		lhs[3],
		lhs[1],
	}
}

// SwizzleZZWZ returns a new vector with the components of this
// vector in the order of ZZWZ.
func (lhs Vec4uh) SwizzleZZWZ() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[2],
		lhs[3],
		lhs[2],
	}
}

// SwizzleZZWW returns a new vector with the components of this
// vector in the order of ZZWW.
func (lhs Vec4uh) SwizzleZZWW() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[2],
		lhs[3],
		lhs[3],
	}
}

// SwizzleZWXX returns a new vector with the components of this
// vector in the order of ZWXX.
func (lhs Vec4uh) SwizzleZWXX() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[3],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZWXY returns a new vector with the components of this
// vector in the order of ZWXY.
func (lhs Vec4uh) SwizzleZWXY() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[3],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZWXZ returns a new vector with the components of this
// vector in the order of ZWXZ.
func (lhs Vec4uh) SwizzleZWXZ() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[3],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZWXW returns a new vector with the components of this
// vector in the order of ZWXW.
func (lhs Vec4uh) SwizzleZWXW() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[3],
		lhs[0],
		lhs[3],
	}
}

// SwizzleZWYX returns a new vector with the components of this
// vector in the order of ZWYX.
func (lhs Vec4uh) SwizzleZWYX() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[3],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZWYY returns a new vector with the components of this
// vector in the order of ZWYY.
func (lhs Vec4uh) SwizzleZWYY() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[3],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZWYZ returns a new vector with the components of this
// vector in the order of ZWYZ.
func (lhs Vec4uh) SwizzleZWYZ() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[3],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZWYW returns a new vector with the components of this
// vector in the order of ZWYW.
func (lhs Vec4uh) SwizzleZWYW() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[3],
		lhs[1],
		lhs[3],
	}
}

// SwizzleZWZX returns a new vector with the components of this
// vector in the order of ZWZX.
func (lhs Vec4uh) SwizzleZWZX() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[3],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZWZY returns a new vector with the components of this
// vector in the order of ZWZY.
func (lhs Vec4uh) SwizzleZWZY() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[3],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZWZZ returns a new vector with the components of this
// vector in the order of ZWZZ.
func (lhs Vec4uh) SwizzleZWZZ() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[3],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZWZW returns a new vector with the components of this
// vector in the order of ZWZW.
func (lhs Vec4uh) SwizzleZWZW() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[3],
		lhs[2],
		lhs[3],
	}
}

// SwizzleZWWX returns a new vector with the components of this
// vector in the order of ZWWX.
func (lhs Vec4uh) SwizzleZWWX() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[3],
		lhs[3],
		lhs[0],
	}
}

// SwizzleZWWY returns a new vector with the components of this
// vector in the order of ZWWY.
func (lhs Vec4uh) SwizzleZWWY() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[3],
		lhs[3],
		lhs[1],
	}
}

// SwizzleZWWZ returns a new vector with the components of this
// vector in the order of ZWWZ.
func (lhs Vec4uh) SwizzleZWWZ() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[3],
		lhs[3],
		lhs[2],
	}
}

// SwizzleZWWW returns a new vector with the components of this
// vector in the order of ZWWW.
func (lhs Vec4uh) SwizzleZWWW() Vec4uh {
	return Vec4uh{
		lhs[2],
		lhs[3],
		lhs[3],
		lhs[3],
	}
}

// SwizzleWXXX returns a new vector with the components of this
// vector in the order of WXXX.
func (lhs Vec4uh) SwizzleWXXX() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleWXXY returns a new vector with the components of this
// vector in the order of WXXY.
func (lhs Vec4uh) SwizzleWXXY() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleWXXZ returns a new vector with the components of this
// vector in the order of WXXZ.
func (lhs Vec4uh) SwizzleWXXZ() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleWXXW returns a new vector with the components of this
// vector in the order of WXXW.
func (lhs Vec4uh) SwizzleWXXW() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[0],
		lhs[0],
		lhs[3],
	}
}

// SwizzleWXYX returns a new vector with the components of this
// vector in the order of WXYX.
func (lhs Vec4uh) SwizzleWXYX() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleWXYY returns a new vector with the components of this
// vector in the order of WXYY.
func (lhs Vec4uh) SwizzleWXYY() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleWXYZ returns a new vector with the components of this
// vector in the order of WXYZ.
func (lhs Vec4uh) SwizzleWXYZ() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleWXYW returns a new vector with the components of this
// vector in the order of WXYW.
func (lhs Vec4uh) SwizzleWXYW() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[0],
		lhs[1],
		lhs[3],
	}
}

// SwizzleWXZX returns a new vector with the components of this
// vector in the order of WXZX.
func (lhs Vec4uh) SwizzleWXZX() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleWXZY returns a new vector with the components of this
// vector in the order of WXZY.
func (lhs Vec4uh) SwizzleWXZY() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleWXZZ returns a new vector with the components of this
// vector in the order of WXZZ.
func (lhs Vec4uh) SwizzleWXZZ() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleWXZW returns a new vector with the components of this
// vector in the order of WXZW.
func (lhs Vec4uh) SwizzleWXZW() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[0],
		lhs[2],
		lhs[3],
	}
}

// SwizzleWXWX returns a new vector with the components of this
// vector in the order of WXWX.
func (lhs Vec4uh) SwizzleWXWX() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[0],
		lhs[3],
		lhs[0],
	}
}

// SwizzleWXWY returns a new vector with the components of this
// vector in the order of WXWY.
func (lhs Vec4uh) SwizzleWXWY() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[0],
		lhs[3],
		lhs[1],
	}
}

// SwizzleWXWZ returns a new vector with the components of this
// vector in the order of WXWZ.
func (lhs Vec4uh) SwizzleWXWZ() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[0],
		lhs[3],
		lhs[2],
	}
}

// SwizzleWXWW returns a new vector with the components of this
// vector in the order of WXWW.
func (lhs Vec4uh) SwizzleWXWW() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[0],
		lhs[3],
		lhs[3],
	}
}

// SwizzleWYXX returns a new vector with the components of this
// vector in the order of WYXX.
func (lhs Vec4uh) SwizzleWYXX() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleWYXY returns a new vector with the components of this
// vector in the order of WYXY.
func (lhs Vec4uh) SwizzleWYXY() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleWYXZ returns a new vector with the components of this
// vector in the order of WYXZ.
func (lhs Vec4uh) SwizzleWYXZ() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleWYXW returns a new vector with the components of this
// vector in the order of WYXW.
func (lhs Vec4uh) SwizzleWYXW() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[1],
		lhs[0],
		lhs[3],
	}
}

// SwizzleWYYX returns a new vector with the components of this
// vector in the order of WYYX.
func (lhs Vec4uh) SwizzleWYYX() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleWYYY returns a new vector with the components of this
// vector in the order of WYYY.
func (lhs Vec4uh) SwizzleWYYY() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleWYYZ returns a new vector with the components of this
// vector in the order of WYYZ.
func (lhs Vec4uh) SwizzleWYYZ() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleWYYW returns a new vector with the components of this
// vector in the order of WYYW.
func (lhs Vec4uh) SwizzleWYYW() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[1],
		lhs[1],
		lhs[3],
	}
}

// SwizzleWYZX returns a new vector with the components of this
// vector in the order of WYZX.
func (lhs Vec4uh) SwizzleWYZX() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleWYZY returns a new vector with the components of this
// vector in the order of WYZY.
func (lhs Vec4uh) SwizzleWYZY() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleWYZZ returns a new vector with the components of this
// vector in the order of WYZZ.
func (lhs Vec4uh) SwizzleWYZZ() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleWYZW returns a new vector with the components of this
// vector in the order of WYZW.
func (lhs Vec4uh) SwizzleWYZW() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[1],
		lhs[2],
		lhs[3],
	}
}

// SwizzleWYWX returns a new vector with the components of this
// vector in the order of WYWX.
func (lhs Vec4uh) SwizzleWYWX() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[1],
		lhs[3],
		lhs[0],
	}
}

// SwizzleWYWY returns a new vector with the components of this
// vector in the order of WYWY.
func (lhs Vec4uh) SwizzleWYWY() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[1],
		lhs[3],
		lhs[1],
	}
}

// SwizzleWYWZ returns a new vector with the components of this
// vector in the order of WYWZ.
func (lhs Vec4uh) SwizzleWYWZ() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[1],
		lhs[3],
		lhs[2],
	}
}

// SwizzleWYWW returns a new vector with the components of this
// vector in the order of WYWW.
func (lhs Vec4uh) SwizzleWYWW() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[1],
		lhs[3],
		lhs[3],
	}
}

// SwizzleWZXX returns a new vector with the components of this
// vector in the order of WZXX.
func (lhs Vec4uh) SwizzleWZXX() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleWZXY returns a new vector with the components of this
// vector in the order of WZXY.
func (lhs Vec4uh) SwizzleWZXY() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleWZXZ returns a new vector with the components of this
// vector in the order of WZXZ.
func (lhs Vec4uh) SwizzleWZXZ() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleWZXW returns a new vector with the components of this
// vector in the order of WZXW.
func (lhs Vec4uh) SwizzleWZXW() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[2],
		lhs[0],
		lhs[3],
	}
}

// SwizzleWZYX returns a new vector with the components of this
// vector in the order of WZYX.
func (lhs Vec4uh) SwizzleWZYX() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleWZYY returns a new vector with the components of this
// vector in the order of WZYY.
func (lhs Vec4uh) SwizzleWZYY() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleWZYZ returns a new vector with the components of this
// vector in the order of WZYZ.
func (lhs Vec4uh) SwizzleWZYZ() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleWZYW returns a new vector with the components of this
// vector in the order of WZYW.
func (lhs Vec4uh) SwizzleWZYW() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[2],
		lhs[1],
		lhs[3],
	}
}

// SwizzleWZZX returns a new vector with the components of this
// vector in the order of WZZX.
func (lhs Vec4uh) SwizzleWZZX() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleWZZY returns a new vector with the components of this
// vector in the order of WZZY.
func (lhs Vec4uh) SwizzleWZZY() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleWZZZ returns a new vector with the components of this
// vector in the order of WZZZ.
func (lhs Vec4uh) SwizzleWZZZ() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

// SwizzleWZZW returns a new vector with the components of this
// vector in the order of WZZW.
func (lhs Vec4uh) SwizzleWZZW() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[2],
		lhs[2],
		lhs[3],
	}
}

// SwizzleWZWX returns a new vector with the components of this
// vector in the order of WZWX.
func (lhs Vec4uh) SwizzleWZWX() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[2],
		lhs[3],
		lhs[0],
	}
}

// SwizzleWZWY returns a new vector with the components of this
// vector in the order of WZWY.
func (lhs Vec4uh) SwizzleWZWY() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[2],
		lhs[3],
		lhs[1],
	}
}

// SwizzleWZWZ returns a new vector with the components of this
// vector in the order of WZWZ.
func (lhs Vec4uh) SwizzleWZWZ() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[2],
		lhs[3],
		lhs[2],
	}
}

// SwizzleWZWW returns a new vector with the components of this
// vector in the order of WZWW.
func (lhs Vec4uh) SwizzleWZWW() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[2],
		lhs[3],
		lhs[3],
	}
}

// SwizzleWWXX returns a new vector with the components of this
// vector in the order of WWXX.
func (lhs Vec4uh) SwizzleWWXX() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[3],
		lhs[0],
		lhs[0],
	}
}

// SwizzleWWXY returns a new vector with the components of this
// vector in the order of WWXY.
func (lhs Vec4uh) SwizzleWWXY() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[3],
		lhs[0],
		lhs[1],
	}
}

// SwizzleWWXZ returns a new vector with the components of this
// vector in the order of WWXZ.
func (lhs Vec4uh) SwizzleWWXZ() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[3],
		lhs[0],
		lhs[2],
	}
}

// SwizzleWWXW returns a new vector with the components of this
// vector in the order of WWXW.
func (lhs Vec4uh) SwizzleWWXW() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[3],
		lhs[0],
		lhs[3],
	}
}

// SwizzleWWYX returns a new vector with the components of this
// vector in the order of WWYX.
func (lhs Vec4uh) SwizzleWWYX() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[3],
		lhs[1],
		lhs[0],
	}
}

// SwizzleWWYY returns a new vector with the components of this
// vector in the order of WWYY.
func (lhs Vec4uh) SwizzleWWYY() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[3],
		lhs[1],
		lhs[1],
	}
}

// SwizzleWWYZ returns a new vector with the components of this
// vector in the order of WWYZ.
func (lhs Vec4uh) SwizzleWWYZ() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[3],
		lhs[1],
		lhs[2],
	}
}

// SwizzleWWYW returns a new vector with the components of this
// vector in the order of WWYW.
func (lhs Vec4uh) SwizzleWWYW() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[3],
		lhs[1],
		lhs[3],
	}
}

// SwizzleWWZX returns a new vector with the components of this
// vector in the order of WWZX.
func (lhs Vec4uh) SwizzleWWZX() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[3],
		lhs[2],
		lhs[0],
	}
}

// SwizzleWWZY returns a new vector with the components of this
// vector in the order of WWZY.
func (lhs Vec4uh) SwizzleWWZY() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[3],
		lhs[2],
		lhs[1],
	}
}

// SwizzleWWZZ returns a new vector with the components of this
// vector in the order of WWZZ.
func (lhs Vec4uh) SwizzleWWZZ() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[3],
		lhs[2],
		lhs[2],
	}
}

// SwizzleWWZW returns a new vector with the components of this
// vector in the order of WWZW.
func (lhs Vec4uh) SwizzleWWZW() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[3],
		lhs[2],
		lhs[3],
	}
}

// SwizzleWWWX returns a new vector with the components of this
// vector in the order of WWWX.
func (lhs Vec4uh) SwizzleWWWX() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[3],
		lhs[3],
		lhs[0],
	}
}

// SwizzleWWWY returns a new vector with the components of this
// vector in the order of WWWY.
func (lhs Vec4uh) SwizzleWWWY() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[3],
		lhs[3],
		lhs[1],
	}
}

// SwizzleWWWZ returns a new vector with the components of this
// vector in the order of WWWZ.
func (lhs Vec4uh) SwizzleWWWZ() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[3],
		lhs[3],
		lhs[2],
	}
}

// SwizzleWWWW returns a new vector with the components of this
// vector in the order of WWWW.
func (lhs Vec4uh) SwizzleWWWW() Vec4uh {
	return Vec4uh{
		lhs[3],
		lhs[3],
		lhs[3],
		lhs[3],
	}
}

func (lhs Vec4uh) XY() (x, y uint16) {
	x = lhs[0]
	y = lhs[1]
	return
}

func (lhs Vec4uh) XYZ() (x, y, z uint16) {
	x = lhs[0]
	y = lhs[1]
	z = lhs[2]
	return
}

func (lhs Vec4uh) XYZW() (x, y, z, w uint16) {
	x = lhs[0]
	y = lhs[1]
	z = lhs[2]
	w = lhs[3]
	return
}

func (lhs Vec4uh) ToVec4f() Vec4f {
	return Vec4f{
		float32(lhs[0]),
		float32(lhs[1]),
		float32(lhs[2]),
		float32(lhs[3]),
	}
}

func (lhs Vec4uh) ToWGPU() [4]float32 {
	return [4]float32{
		float32(lhs[0]),
		float32(lhs[1]),
		float32(lhs[2]),
		float32(lhs[3]),
	}
}

func (lhs Vec4uh) String() string {
	return fmt.Sprintf(
		"vec4(%v, %v, %v, %v)",
		lhs[0],
		lhs[1],
		lhs[2],
		lhs[3],
	)
}
