//go:build amd64 && !goexperiment.simd

#include "textflag.h"

TEXT ·mat4fMulSimd(SB), NOSPLIT, $0-24
    // load arguments into registers
    MOVQ m+0(FP),    SI
    MOVQ o+8(FP),    DI
    MOVQ res+16(FP), DX

    // fully unrolled 4x4 matrix multiplication
    // generated by compiling & translating c code.
    //
    // x86_64-unknown-linux-gnu-gcc -O3 -mfma -c -o /tmp/test.o _matp_amd64.c
    // x86_64-unknown-linux-gnu-objdump --disassemble=mul /tmp/test.o
    //
    BYTE $0xc5; BYTE $0xf8; BYTE $0x10; BYTE $0x1f;                         // vmovups (%rdi),%xmm3
    BYTE $0xc4; BYTE $0xe2; BYTE $0x79; BYTE $0x18; BYTE $0x2e;             // vbroadcastss (%rsi),%xmm5
    BYTE $0xc5; BYTE $0xf8; BYTE $0x10; BYTE $0x57; BYTE $0x10;             // vmovups 0x10(%rdi),%xmm2
    BYTE $0xc4; BYTE $0xe2; BYTE $0x79; BYTE $0x18; BYTE $0x66; BYTE $0x04; // vbroadcastss 0x4(%rsi),%xmm4
    BYTE $0xc5; BYTE $0xd0; BYTE $0x59; BYTE $0xeb;                         // vmulps %xmm3,%xmm5,%xmm5
    BYTE $0xc5; BYTE $0xf8; BYTE $0x10; BYTE $0x4f; BYTE $0x20;             // vmovups 0x20(%rdi),%xmm1
    BYTE $0xc5; BYTE $0xf8; BYTE $0x10; BYTE $0x47; BYTE $0x30;             // vmovups 0x30(%rdi),%xmm0
    BYTE $0xc4; BYTE $0xe2; BYTE $0x51; BYTE $0x98; BYTE $0xe2;             // vfmadd132ps %xmm2,%xmm5,%xmm4
    BYTE $0xc4; BYTE $0xe2; BYTE $0x79; BYTE $0x18; BYTE $0x6e; BYTE $0x08; // vbroadcastss 0x8(%rsi),%xmm5
    BYTE $0xc4; BYTE $0xe2; BYTE $0x59; BYTE $0x98; BYTE $0xe9;             // vfmadd132ps %xmm1,%xmm4,%xmm5
    BYTE $0xc4; BYTE $0xe2; BYTE $0x79; BYTE $0x18; BYTE $0x66; BYTE $0x0c; // vbroadcastss 0xc(%rsi),%xmm4
    BYTE $0xc4; BYTE $0xe2; BYTE $0x51; BYTE $0x98; BYTE $0xe0;             // vfmadd132ps %xmm0,%xmm5,%xmm4
    BYTE $0xc4; BYTE $0xe2; BYTE $0x79; BYTE $0x18; BYTE $0x6e; BYTE $0x10; // vbroadcastss 0x10(%rsi),%xmm5
    BYTE $0xc5; BYTE $0xd0; BYTE $0x59; BYTE $0xeb;                         // vmulps %xmm3,%xmm5,%xmm5
    BYTE $0xc5; BYTE $0xf8; BYTE $0x11; BYTE $0x22;                         // vmovups %xmm4,(%rdx)
    BYTE $0xc4; BYTE $0xe2; BYTE $0x79; BYTE $0x18; BYTE $0x66; BYTE $0x14; // vbroadcastss 0x14(%rsi),%xmm4
    BYTE $0xc4; BYTE $0xe2; BYTE $0x51; BYTE $0x98; BYTE $0xe2;             // vfmadd132ps %xmm2,%xmm5,%xmm4
    BYTE $0xc4; BYTE $0xe2; BYTE $0x79; BYTE $0x18; BYTE $0x6e; BYTE $0x18; // vbroadcastss 0x18(%rsi),%xmm5
    BYTE $0xc4; BYTE $0xe2; BYTE $0x59; BYTE $0x98; BYTE $0xe9;             // vfmadd132ps %xmm1,%xmm4,%xmm5
    BYTE $0xc4; BYTE $0xe2; BYTE $0x79; BYTE $0x18; BYTE $0x66; BYTE $0x1c; // vbroadcastss 0x1c(%rsi),%xmm4
    BYTE $0xc4; BYTE $0xe2; BYTE $0x51; BYTE $0x98; BYTE $0xe0;             // vfmadd132ps %xmm0,%xmm5,%xmm4
    BYTE $0xc4; BYTE $0xe2; BYTE $0x79; BYTE $0x18; BYTE $0x6e; BYTE $0x20; // vbroadcastss 0x20(%rsi),%xmm5
    BYTE $0xc5; BYTE $0xd0; BYTE $0x59; BYTE $0xeb;                         // vmulps %xmm3,%xmm5,%xmm5
    BYTE $0xc5; BYTE $0xf8; BYTE $0x11; BYTE $0x62; BYTE $0x10;             // vmovups %xmm4,0x10(%rdx)
    BYTE $0xc4; BYTE $0xe2; BYTE $0x79; BYTE $0x18; BYTE $0x66; BYTE $0x24; // vbroadcastss 0x24(%rsi),%xmm4
    BYTE $0xc4; BYTE $0xe2; BYTE $0x51; BYTE $0x98; BYTE $0xe2;             // vfmadd132ps %xmm2,%xmm5,%xmm4
    BYTE $0xc4; BYTE $0xe2; BYTE $0x79; BYTE $0x18; BYTE $0x6e; BYTE $0x28; // vbroadcastss 0x28(%rsi),%xmm5
    BYTE $0xc4; BYTE $0xe2; BYTE $0x59; BYTE $0x98; BYTE $0xe9;             // vfmadd132ps %xmm1,%xmm4,%xmm5
    BYTE $0xc4; BYTE $0xe2; BYTE $0x79; BYTE $0x18; BYTE $0x66; BYTE $0x2c; // vbroadcastss 0x2c(%rsi),%xmm4
    BYTE $0xc4; BYTE $0xe2; BYTE $0x51; BYTE $0x98; BYTE $0xe0;             // vfmadd132ps %xmm0,%xmm5,%xmm4
    BYTE $0xc4; BYTE $0xe2; BYTE $0x79; BYTE $0x18; BYTE $0x6e; BYTE $0x34; // vbroadcastss 0x34(%rsi),%xmm5
    BYTE $0xc5; BYTE $0xf8; BYTE $0x11; BYTE $0x62; BYTE $0x20;             // vmovups %xmm4,0x20(%rdx)
    BYTE $0xc4; BYTE $0xe2; BYTE $0x79; BYTE $0x18; BYTE $0x66; BYTE $0x30; // vbroadcastss 0x30(%rsi),%xmm4
    BYTE $0xc5; BYTE $0xd8; BYTE $0x59; BYTE $0xdb;                         // vmulps %xmm3,%xmm4,%xmm3
    BYTE $0xc4; BYTE $0xe2; BYTE $0x61; BYTE $0x98; BYTE $0xd5;             // vfmadd132ps %xmm5,%xmm3,%xmm2
    BYTE $0xc4; BYTE $0xe2; BYTE $0x79; BYTE $0x18; BYTE $0x5e; BYTE $0x38; // vbroadcastss 0x38(%rsi),%xmm3
    BYTE $0xc4; BYTE $0xe2; BYTE $0x69; BYTE $0x98; BYTE $0xcb;             // vfmadd132ps %xmm3,%xmm2,%xmm1
    BYTE $0xc4; BYTE $0xe2; BYTE $0x79; BYTE $0x18; BYTE $0x56; BYTE $0x3c; // vbroadcastss 0x3c(%rsi),%xmm2
    BYTE $0xc4; BYTE $0xe2; BYTE $0x71; BYTE $0x98; BYTE $0xc2;             // vfmadd132ps %xmm2,%xmm1,%xmm0
    BYTE $0xc5; BYTE $0xf8; BYTE $0x11; BYTE $0x42; BYTE $0x30;             // vmovups %xmm0,0x30(%rdx)

    RET
