//go:build arm64

#include "textflag.h"

TEXT ·mat4fMulSimd(SB), NOSPLIT, $0-24
    // load arguments into registers
    MOVD m+0(FP), R0
    MOVD o+8(FP), R1
    MOVD res+16(FP), R2

    // fully unrolled 4x4 matrix multiplication
    // generated by compiling & translating c code.
    //
    // aarch64-unknown-linux-gnu-gcc -O3 -c -o /tmp/test.o _matp_arm64.c
    // objdump --disassemble /tmp/test.o
    //
    WORD $0xa9bf7bfd // stp	x29, x30, [sp, #-16]!
    WORD $0x910003fd // mov	x29, sp
    WORD $0x4d40c830 // ld1r	{v16.4s}, [x1]
    WORD $0xad40781f // ldp	q31, q30, [x0]
    WORD $0x2d419031 // ldp	s17, s4, [x1, #12]
    WORD $0x2d438025 // ldp	s5, s0, [x1, #28]
    WORD $0x2d45e421 // ldp	s1, s25, [x1, #44]
    WORD $0x2d40c833 // ldp	s19, s18, [x1, #4]
    WORD $0x2d429827 // ldp	s7, s6, [x1, #20]
    WORD $0x2d448823 // ldp	s3, s2, [x1, #36]
    WORD $0x2d46ec38 // ldp	s24, s27, [x1, #52]
    WORD $0x6e3fde10 // fmul	v16.4s, v16.4s, v31.4s
    WORD $0xbd403c3a // ldr	s26, [x1, #60]
    WORD $0x4f8493e4 // fmul	v4.4s, v31.4s, v4.s[0]
    WORD $0x4f8093e0 // fmul	v0.4s, v31.4s, v0.s[0]
    WORD $0x4f9993f9 // fmul	v25.4s, v31.4s, v25.s[0]
    WORD $0xad41701d // ldp	q29, q28, [x0, #32]
    WORD $0x4f9313d0 // fmla	v16.4s, v30.4s, v19.s[0]
    WORD $0x4f8713c4 // fmla	v4.4s, v30.4s, v7.s[0]
    WORD $0x4f8313c0 // fmla	v0.4s, v30.4s, v3.s[0]
    WORD $0x4f9813d9 // fmla	v25.4s, v30.4s, v24.s[0]
    WORD $0x4f9213b0 // fmla	v16.4s, v29.4s, v18.s[0]
    WORD $0x4f8613a4 // fmla	v4.4s, v29.4s, v6.s[0]
    WORD $0x4f8213a0 // fmla	v0.4s, v29.4s, v2.s[0]
    WORD $0x4f9b13b9 // fmla	v25.4s, v29.4s, v27.s[0]
    WORD $0x4f911390 // fmla	v16.4s, v28.4s, v17.s[0]
    WORD $0x4f851384 // fmla	v4.4s, v28.4s, v5.s[0]
    WORD $0x4f811380 // fmla	v0.4s, v28.4s, v1.s[0]
    WORD $0x4f9a1399 // fmla	v25.4s, v28.4s, v26.s[0]
    WORD $0xa8c17bfd // ldp	x29, x30, [sp], #16
    WORD $0xad001050 // stp	q16, q4, [x2]
    WORD $0xad016440 // stp	q0, q25, [x2, #32]
    WORD $0xd2800000 // mov	x0, #0x0                   	// #0
    WORD $0xd2800001 // mov	x1, #0x0                   	// #0
    WORD $0xd2800002 // mov	x2, #0x0                   	// #0
    WORD $0xd65f03c0 // ret

    RET
