//go:build !nosimd && arm64

#include "textflag.h"

TEXT ·mat4fMulAssign(SB), NOSPLIT, $0-16
    // load arguments into registers
    MOVD m+0(FP), R0
    MOVD o+8(FP), R1

    // fully unrolled 4x4 matrix multiplication
    // generated by compiling & translating c code.
    //
    // aarch64-unknown-linux-gnu-gcc -O3 -c -o /tmp/test.o _matp_arm64.c
    // objdump --disassemble /tmp/test.o
    //
    WORD $0xa9bf7bfd // 	stp	x29, x30, [sp, #-16]!
    WORD $0x910003fd // 	mov	x29, sp
    WORD $0xbd403c1f // 	ldr	s31, [x0, #60]
    WORD $0x4c400839 // 	ld4	{v25.4s-v28.4s}, [x1]
    WORD $0x2d42cc14 // 	ldp	s20, s19, [x0, #20]
    WORD $0x2d46f81d // 	ldp	s29, s30, [x0, #52]
    WORD $0x2d43c412 // 	ldp	s18, s17, [x0, #28]
    WORD $0x2d41d416 // 	ldp	s22, s21, [x0, #12]
    WORD $0x2d459406 // 	ldp	s6, s5, [x0, #44]
    WORD $0x2d40dc18 // 	ldp	s24, s23, [x0, #4]
    WORD $0x2d449c10 // 	ldp	s16, s7, [x0, #36]
    WORD $0x4f929352 // 	fmul	v18.4s, v26.4s, v18.s[0]
    WORD $0x4d40c804 // 	ld1r	{v4.4s}, [x0]
    WORD $0x4f939353 // 	fmul	v19.4s, v26.4s, v19.s[0]
    WORD $0x4f9e939e // 	fmul	v30.4s, v28.4s, v30.s[0]
    WORD $0x4f949354 // 	fmul	v20.4s, v26.4s, v20.s[0]
    WORD $0x4f9d939d // 	fmul	v29.4s, v28.4s, v29.s[0]
    WORD $0x4f95935a // 	fmul	v26.4s, v26.4s, v21.s[0]
    WORD $0x4f9f939f // 	fmul	v31.4s, v28.4s, v31.s[0]
    WORD $0x4f85939c // 	fmul	v28.4s, v28.4s, v5.s[0]
    WORD $0x4f961332 // 	fmla	v18.4s, v25.4s, v22.s[0]
    WORD $0x4f971333 // 	fmla	v19.4s, v25.4s, v23.s[0]
    WORD $0x4f87137e // 	fmla	v30.4s, v27.4s, v7.s[0]
    WORD $0x4f981334 // 	fmla	v20.4s, v25.4s, v24.s[0]
    WORD $0x4f90137d // 	fmla	v29.4s, v27.4s, v16.s[0]
    WORD $0x4e39cc9a // 	fmla	v26.4s, v4.4s, v25.4s
    WORD $0x4f86137f // 	fmla	v31.4s, v27.4s, v6.s[0]
    WORD $0x4f91137c // 	fmla	v28.4s, v27.4s, v17.s[0]
    WORD $0x4e33d7de // 	fadd	v30.4s, v30.4s, v19.4s
    WORD $0x4e34d7bd // 	fadd	v29.4s, v29.4s, v20.4s
    WORD $0x4e32d7ff // 	fadd	v31.4s, v31.4s, v18.4s
    WORD $0x4e3ad79c // 	fadd	v28.4s, v28.4s, v26.4s
    WORD $0xa8c17bfd // 	ldp	x29, x30, [sp], #16
    WORD $0x4c00081c // 	st4	{v28.4s-v31.4s}, [x0]
    WORD $0xd2800000 // 	mov	x0, #0x0                   	// #0
    WORD $0xd2800001 // 	mov	x1, #0x0                   	// #0

    RET

TEXT ·mat4fScaleAssign(SB), NOSPLIT, $0-16
    // load arguments into registers
    MOVD m+0(FP),  R0
    FMOVS x+8(FP), F0
    FMOVS y+12(FP), F1
    FMOVS z+16(FP), F2

    WORD $0xa9bf7bfd // stp	x29, x30, [sp, #-16]!
    WORD $0x910003fd // mov	x29, sp
    WORD $0x3dc0081f // ldr	q31, [x0, #32]
    WORD $0xad400c04 // ldp	q4, q3, [x0]
    WORD $0x4f8293ff // fmul	v31.4s, v31.4s, v2.s[0]
    WORD $0xa8c17bfd // ldp	x29, x30, [sp], #16
    WORD $0x4f809084 // fmul	v4.4s, v4.4s, v0.s[0]
    WORD $0x4f819063 // fmul	v3.4s, v3.4s, v1.s[0]
    WORD $0x3d80081f // str	q31, [x0, #32]
    WORD $0xad000c04 // stp	q4, q3, [x0]
    WORD $0xd2800000 // mov	x0, #0x0                   	// #0

    RET

TEXT ·mat4fTranslateAssign(SB), NOSPLIT, $0-16
    // load arguments into registers
    MOVD m+0(FP),  R0
    FMOVS x+8(FP), F0
    FMOVS y+12(FP), F1
    FMOVS z+16(FP), F2

    WORD $0xa9bf7bfd // stp	x29, x30, [sp, #-16]!
    WORD $0x910003fd // mov	x29, sp
    WORD $0xad41701e // ldp	q30, q28, [x0, #32]
    WORD $0xad407c1d // ldp	q29, q31, [x0]
    WORD $0xa8c17bfd // ldp	x29, x30, [sp], #16
    WORD $0x4f8013bc // fmla	v28.4s, v29.4s, v0.s[0]
    WORD $0x4f8113fc // fmla	v28.4s, v31.4s, v1.s[0]
    WORD $0x4f8213dc // fmla	v28.4s, v30.4s, v2.s[0]
    WORD $0x3d800c1c // str	q28, [x0, #48]
    WORD $0xd2800000 // mov	x0, #0x0                   	// #0

    RET

