// Code generated by "stringer -type=AlphaMode"; DO NOT EDIT.

package byke2d

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AlphaModeOpaque-0]
	_ = x[AlphaModeMask-1]
	_ = x[AlphaModeBlend-2]
	_ = x[Premultiplied-3]
	_ = x[AlphaModeAlphaToCoverage-4]
	_ = x[AlphaModeAdd-5]
	_ = x[AlphaModeMultiply-6]
}

const _AlphaMode_name = "AlphaModeOpaqueAlphaModeMaskAlphaModeBlendPremultipliedAlphaModeAlphaToCoverageAlphaModeAddAlphaModeMultiply"

var _AlphaMode_index = [...]uint8{0, 15, 28, 42, 55, 79, 91, 108}

func (i AlphaMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AlphaMode_index)-1 {
		return "AlphaMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AlphaMode_name[_AlphaMode_index[idx]:_AlphaMode_index[idx+1]]
}
