package byke2d

import (
	"github.com/oliverbestmann/byke"
	"github.com/oliverbestmann/byke/byke2d/wgsl"
)

type EnvironmentMapLight struct {
	byke.Component[EnvironmentMapLight]

	// The blurry image that represents diffuse radiance surrounding a region.
	DiffuseMap *Texture

	// The typically-sharper, mipmapped image that represents specular radiance surrounding a region.
	SpecularMap *Texture

	// Scale factor applied to the diffuse and specular light generated by this component.
	// After applying this multiplier, the resulting values should be in units of cd/m^2.
	// See https://google.github.io/filament/Filament.md.html#lighting/imagebasedlights/iblunit
	Intensity float32

	// TODO
	// Rotation glm.Quat

}

func (e EnvironmentMapLight) ToWGPU() []byte {
	var w wgsl.StructWriter
	w.AppendFloat32(e.Intensity)
	return w.Bytes()
}
