name: CI
on:
  push:
  pull_request:

jobs:
  CompileNative:
    strategy:
      fail-fast: false

      matrix:
        config:
          - runner: ubuntu-latest

          - runner: ubuntu-latest
            goexperiment: simd

          - runner: ubuntu-24.04-arm

          - runner: ubuntu-24.04-arm
            goexperiment: simd

    runs-on: "${{ matrix.config.runner }}"

    env:
      GOEXPERIMENT: "${{ matrix.config.goexperiment }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -f -y libegl1-mesa-dev mesa-vulkan-drivers \
            libasound2-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev \
            libxkbcommon-dev libwayland-dev

      - name: Environment
        run: go env

      - name: Run tests
        run: |
          go test -v ./...

      - name: Run tests with no simd
        run: |
          go test --tags=nosimd -v ./...

      - name: Lints
        run: |
          go vet -v ./...

      - name: Build Examples
        run: |
          cd byke2d
          go build -v ./examples/*

  CompileWASM:
    runs-on: ubuntu-latest

    env:
      GOOS: "js"
      GOARCH: "wasm"
      CGO_ENABLED: "0"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Compile examples
        run: |
          cd byke2d
          go build -v ./examples/*
