name: CI
on:
  push:
  pull_request:

jobs:
  CompileNative:
    strategy:
      fail-fast: false

      matrix:
        config:
          - runner: ubuntu-24.04
            goexperiment: ""

          - runner: ubuntu-24.04
            goexperiment: "simd"

          - runner: ubuntu-24.04-arm
            goexperiment: ""

          - runner: ubuntu-24.04-arm
            goexperiment: "simd"

    runs-on: "${{ matrix.config.runner }}"

    env:
      GOEXPERIMENT: "${{ matrix.config.goexperiment }}"

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v7

      - name: "Setup Go"
        uses: actions/setup-go@v7
        with:
          go-version: 1.27.0-rc.2
          go-version-file: go.mod

      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -f -y libegl1-mesa-dev mesa-vulkan-drivers \
            libasound2-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev \
            libxkbcommon-dev libwayland-dev

      - name: "Run tests"
        run: |
          go test -v ./...

      - name: "Run tests with tag: nosimd"
        run: |
          go test --tags=nosimd -v ./...

      - name: "Run go vet"
        run: |
          go vet -v ./...

      - name: "Build all examples"
        run: |
          cd byke2d
          go build -v ./examples/...

  CompileWASM:
    runs-on: ubuntu-latest

    env:
      GOOS: "js"
      GOARCH: "wasm"
      CGO_ENABLED: "0"
      GOEXPERIMENT: "simd"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: 1.27.0-rc.2
          go-version-file: go.mod

      - name: Compile examples
        run: |
          cd byke2d
          go build -v ./examples/...
