name: Snapshots
on:
  push:
  pull_request:

jobs:
  Verify:
    strategy:
      fail-fast: false

      matrix:
        config:
          - runner: ubuntu-24.04-arm
            goexperiment: "simd"

    runs-on: "${{ matrix.config.runner }}"

    env:
      GOEXPERIMENT: "${{ matrix.config.goexperiment }}"

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v7

      - name: "Setup Go"
        uses: actions/setup-go@v7
        with:
          go-version: 1.27.0-rc.2
          go-version-file: go.mod

      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -f -y libegl1-mesa-dev mesa-vulkan-drivers \
            libasound2-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev \
            libxkbcommon-dev libwayland-dev


      - name: "Run examples"
        run: |
          EXAMPLES=$(for F in $(grep --files-with-matches -R shared.RunAppInTest byke2d/examples/) ; do dirname $F ; done)
          
          mkdir images
          
          FAILED=0
          for EXAMPLE in $EXAMPLES ; do
            echo "Run example $EXAMPLE"
          
            rm -f /tmp/image-*.png || true
          
            if ! ./run-example-test.sh $EXAMPLE ; then
              echo "::error::Example failed: $EXAMPLE"
              FAILED=1
            fi
          
            NAME=$(echo $EXAMPLE | tr '/' '_')
            
            IMAGE=$(find /tmp -maxdepth 1 -name 'image-*.png' | sort | head -n1)
            if [ -n "$IMAGE" ]; then
              cp "$IMAGE" "images/$NAME.png"
            fi
            
            echo 
            echo
            echo
          done
          
          exit $FAILED

      - name: "Upload images to github"
        if: always()
        uses: actions/upload-artifact@v7
        with:
          if-no-files-found: 'warn'
          name: 'snapshots'
          path: images/*.png
