name: Snapshots
on:
  push:
  pull_request:

jobs:
  Verify:
    strategy:
      fail-fast: false

      matrix:
        config:
          - runner: ubuntu-24.04-arm
            goexperiment: ""

          - runner: ubuntu-24.04-arm
            goexperiment: "simd"

    runs-on: "${{ matrix.config.runner }}"

    env:
      GOEXPERIMENT: "${{ matrix.config.goexperiment }}"

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v7

      - name: "Setup Go"
        uses: actions/setup-go@v7
        with:
          go-version: 1.27.0-rc.2
          go-version-file: go.mod

      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -f -y libegl1-mesa-dev mesa-vulkan-drivers \
            libasound2-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev \
            libxkbcommon-dev libwayland-dev


      - name: "Run example offscreen: cube"
        run: ./run-example-test.sh ./byke2d/examples/render3d/cube/

      - name: "Upload generated images: cube"
        uses: actions/upload-artifact@v7
        with:
          name: "Images cube GOEXPERIMENT=${{ matrix.config.goexperiment }}"
          path: "/tmp/image-*.png"


      - name: "Run example offscreen: animated-material"
        run: ./run-example-test.sh ./byke2d/examples/render3d/animated-material/

      - name: "Upload generated images: animated-material"
        uses: actions/upload-artifact@v7
        with:
          name: "Images animated-material GOEXPERIMENT=${{ matrix.config.goexperiment }}"
          path: "/tmp/image-*.png"


      - name: "Run example offscreen: blend-modes"
        run: ./run-example-test.sh ./byke2d/examples/render3d/blend-modes/

      - name: "Upload generated images: blend-modes"
        uses: actions/upload-artifact@v7
        with:
          name: "Images blend-modes GOEXPERIMENT=${{ matrix.config.goexperiment }}"
          path: "/tmp/image-*.png"


      - name: "Run example offscreen: rotation"
        run: ./run-example-test.sh ./byke2d/examples/transform/rotation/

      - name: "Upload generated images: rotation"
        uses: actions/upload-artifact@v7
        with:
          name: "Images rotation GOEXPERIMENT=${{ matrix.config.goexperiment }}"
          path: "/tmp/image-*.png"


      - name: "Run example offscreen: scale"
        run: ./run-example-test.sh ./byke2d/examples/transform/scale/

      - name: "Upload generated images: scale"
        uses: actions/upload-artifact@v7
        with:
          name: "Images scale GOEXPERIMENT=${{ matrix.config.goexperiment }}"
          path: "/tmp/image-*.png"


      - name: "Run example offscreen: pbr"
        run: ./run-example-test.sh ./byke2d/examples/transform/pbr/

      - name: "Upload generated images: pbr"
        uses: actions/upload-artifact@v7
        with:
          name: "Images pbr GOEXPERIMENT=${{ matrix.config.goexperiment }}"
          path: "/tmp/image-*.png"

