// Code generated by "stringer -type SupercompressionScheme"; DO NOT EDIT.

package ktx2

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SupercompressionSchemeNone-0]
	_ = x[SupercompressionSchemeBasisLZ-1]
	_ = x[SupercompressionSchemeZSTD-2]
	_ = x[SupercompressionSchemeZLIB-3]
}

const _SupercompressionScheme_name = "SupercompressionSchemeNoneSupercompressionSchemeBasisLZSupercompressionSchemeZSTDSupercompressionSchemeZLIB"

var _SupercompressionScheme_index = [...]uint8{0, 26, 55, 81, 107}

func (i SupercompressionScheme) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SupercompressionScheme_index)-1 {
		return "SupercompressionScheme(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SupercompressionScheme_name[_SupercompressionScheme_index[idx]:_SupercompressionScheme_index[idx+1]]
}
