// Code generated by "stringer -type TextureType"; DO NOT EDIT.

package ktx2

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TextureType1d-0]
	_ = x[TextureType2d-1]
	_ = x[TextureType3d-2]
	_ = x[TextureTypeCubemap-3]
	_ = x[TextureType1dArray-4]
	_ = x[TextureType2dArray-5]
	_ = x[TextureType3dArray-6]
	_ = x[TextureTypeCubemapArray-7]
}

const _TextureType_name = "TextureType1dTextureType2dTextureType3dTextureTypeCubemapTextureType1dArrayTextureType2dArrayTextureType3dArrayTextureTypeCubemapArray"

var _TextureType_index = [...]uint8{0, 13, 26, 39, 57, 75, 93, 111, 134}

func (i TextureType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TextureType_index)-1 {
		return "TextureType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TextureType_name[_TextureType_index[idx]:_TextureType_index[idx+1]]
}
